### ISSUE TITLE
Assignment 1 Ziqing Yuan

### ISSUE THREAD

**Issue by ZQYZQYZQ** [EstherPlomp/TNW-RDM-101#100]
### Introduction
Hi all, my name is Ziqing Yuan and I'm the Faculty's Chemical Engineering. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
Reliable hydrogen sensors are essential for the safe implementation of a large scale green hydrogen economy. Optical fibre hydrogen sensors seem the perfect candidate from a practical perspective; they are small, relatively cheap to make, and do not require an electronic detection device in the measurement area. This work presents research on the realisation and optimisation of such a system utilising metal hydride thin film as a sensing layer.

There are three dimensions that I will improved during my research. The first part is to extend the sensing temperature to lower temperatures, aiming to achieve a sensing range of 0.04% to 100% at -60℃. The second part is to optimize the micro-mirror metal hydride sensors by investigate possible new materials to improve the optical contrast. The third part of my research will continue to explore surface plasmon resonance fiber optic sensors.

For the realisation of low temperature sensing we have already a good basis on the use of Ta88Pd12. The problem that arises with this material and structure at -60℃ is the long reaction time due to the slow metal hydrogenation process. Regarding that this research will explore the effect of different materials and different layer thicknesses on the experimental results and add a cover layer to accelerate the dissociation of hydrogen
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes|
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes|
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
Good data management practices can prevent data loss and make experimental methods and data reproducible.

### What would you like to learn during this course? 
Systematically manage individual experimental data and save individual versions of Python code.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #66
- [ ] Respond to the GitHub discussion #67
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by EstherPlomp** [comment]
Thanks for now also handing in assignment 1 @ZQYZQYZQ! Don't forget to share assignment 3 - deadline was earlier today. Please let me know if you need any help with that!
