### ISSUE TITLE
Overview issue [your-name-here]

### ISSUE THREAD

**Issue by nicolastravnicek** [EstherPlomp/TNW-RDM-101#105]
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes|
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [ ] Respond to the GitHub issue #65 
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #66
- [ ] Respond to the GitHub discussion #67
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @nicolastravnicek! Thanks for already submitting your overview assignment! If you remove the #<!--  signs before and after your answers, they will show up in the submitted assignment. I removed it for you for the first answer as an example. Please let me know if you have any issues with that and we can go over it together!

**Comment by nicolastravnicek** [comment]
Attached you will find the link to my second assignment
https://surfdrive.surf.nl/files/index.php/s/Mq4rTzHWfusplXp

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 2 @nicolastravnicek! It looks clear! 

A question: 
- You use the closed access flag for all your data: why is this? In the overview assignment above you do not indicate that you work with industry? Why is the data confidential?

And some suggestions:
- Files stored locally on your laptop or measurement computers are not backed up, unless you're using network drives! Which network drive is the section using for the data?
- You mention labbooks in your notes but not in the data workflow: do you work with a lab book? If so it would be better to see that as a separate dataflow for the next assignment.

**Comment by xxmeryl** [comment]
Hi @nicolastravnicek ! Thanks for sharing your assignment, looks clear and very concise. I do have two questions:

- Is this the only data you will be dealing with over the whole course of the project, or only just now? 
- How do you make the distinction about what is important enough to write electronically down versus 'only'  in your labjournal? Wouldn't it be saver to somehow have an electronic back-up of your whole labjournal? Possibly scanning the pages every now and then, or using e-Labjournal?

**Comment by Adarsh-Shajimon** [comment]
Hi Nicolas! Thanks for sharing your Data Flow Map. It is concise.
Do you store confidential data only on your private laptop? If yes, I would suggest having a secure backup of it. @nicolastravnicek

**Comment by nicolastravnicek** [comment]
The second assignment can be found here:
https://surfdrive.surf.nl/files/index.php/s/Mq4rTzHWfusplXp 
(basically the same link as for the first assignment)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @nicolastravnicek! It looks clear! And thanks for your feedback as well @SiemEerden: great point about file formats and also the risks of file format conversions!

I'm still interested why all of your data is flagged as confidential? Even if you're part of a consortium at least part of your data (underlying articles and thesis chapters) should be allowed to be shared (as seems to be the case for the first dataset in slide 5?)

Some other thoughts/comments, of which the last point is particular important: 
- I like the self explanatory file naming style in the slides! 
- Regarding documentation: do you also not work with protocols and/or labnotes?
- For slide 6 the questions are about publicly sharing data and preserving data for the long term: your local laptop is not a solution for this. Project Drive is indeed better for long term preservation but does not provide public access. GitHub can indeed be publicly available, but it is not the same as a data repository as it does not have a long term preservation policy and it also doesn't assign DOIs to repositories (needed for data and code to be FAIR!). I'd recommend to have another look at the [Data Publication materials](https://estherplomp.github.io/DRA-RDM-1/08-Publication.html)!

**Comment by ezgidemiroz** [comment]
Hi Nicolas! Nice stucture for assignments 2 and 3. Looks very clear to me!
