### ISSUE TITLE
Folake Monsurat Babalola

### ISSUE THREAD

**Issue by FolakeBabalola** [EstherPlomp/TNW-RDM-101#106]
### Introduction
Hello! My name is Folake Babalola, and I am a student of IHE, affiliated with the Pure and Applied Sciences faculty at TU Delft

My research focuses on health and environmental risk assessments for sanitation service chains in humanitarian settings, by developing and piloting risk assessment tools in refugee communities and evaluating the usability and usefulness of the tools and their outputs for the humanitarian sectors.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
Losing the data I would generate during my research would be disastrous. RDM is crucial for me to complete my PhD program and have sufficient publications within the stipulated period (4 years). I want to avoid wasting time and the headache that comes with losing data due to poor backup.

### What would you like to learn during this course? 
During the course, I want to learn how I can reproduce my data by incorporating good data management practices into my research and having an efficient workflow.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://1drv.ms/p/c/f5c91a6b7fc6be5e/EbXYzWI6_1pOjHSnVDb2f3cBM4N9F2u4LP1xd-P56y41BA?e=gCoBAb
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103 
- [x] Respond to the GitHub discussion #102 
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://1drv.ms/p/c/f5c91a6b7fc6be5e/ETVO7bW5oslDkPDMOoHWFCkBHGAlGoTL07tkEi3YxmmscQ?e=oQCWdZ 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [ ] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**) https://surfdrive.surf.nl/files/remote.php/webdav/Data%20Flow%20Map%20Reflection_Folake.pptx
https://1drv.ms/p/c/f5c91a6b7fc6be5e/EQ-aL3gTyd9GpnSnh8_JkD4BDHZTycEgfehCj2eYhmr1NA?e=LSdMFo

**Comment by EstherPlomp** [comment]
Thanks for sharing Assignment 2 @FolakeBabalola! It looks very clear! Interesting combination of datasets!

Some suggestions/pointers: 
- I see you plan to use Google Drive for storage, which is fine for most data (although do note that the Google user terms do give them permission to reuse the data for their own purposes!) - but **not for the confidential data** that you'll collect (interviews, photographs and observations).
- For [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html) the file formats of your files will become more important to reflect upon. The file formats you use are currently only clear for the risk assessment data. 
- I hope your personal computer and OneDrive provide you with sufficient storage space!

**Comment by vgualtieri** [comment]
Hi Folake!

The plan looks clear, despite the use of some acronyms of which I have no idea. I do wonder about how much storage space all those data will require, and it google drive and one drive would be the better options (for both confidentiality and space). Maybe it would be worth it to check on university storages - might be a pain to learn about how to use them, but probably it will be better in the long run, even for future students that may build upon your research.

**Comment by adammubeen** [comment]
Great work on the data flow map. It gives a pretty clear picture of what you will be doing with the data.

You can potentially anonymise or remove identifiers from the data before storing them in those locations. 

@vgualtieri We have a considerable amount of space available for storage on surfdrive from both TU Delft and IHE, and probably gives us more space than the a normal google drive or one drive account has available. I think more space is available on request if the need is justified.

**Comment by EstherPlomp** [comment]
Thanks for the feedback @adammubeen! For SURFdrive the limit is currently 1 TB - Project Drive you can indeed continue asking for further storage extension.

**Comment by adammubeen** [comment]
One of the things I learned from this course and could also be beneficial for both of us may be a directory file for each folder that shows what is in the folders and files. I also think the location can be anonymised by giving it an ID instead of the place name directly if the data is sensitive in nature.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @FolakeBabalola - It again looks very clear! 

Some thoughts from my side:
- I miss an example of a file name and a bit more detail on your folder structure, so it is difficult to provide feedback on this aspect
- You are indeed using some open formats, but also closed/proprietary ones:  Atlas.ti or Excel/Word are proprietary and will need access to licenses of Atlas.ti or Microsoft to be able to fully interact with files. They can export files in open file formats such as .txt or .csv. That is not always needed and will be up for your consideration whether it is helpful or not!
- The Water and Development Partnership Programme (WDPP) doesn't look like they have their own respository? But the IHE Delft repository looks nice for your type of research if you can include it all in your thesis. Otherwise 4TU.ResearchData is also always an option! 

Is it also correct that I haven't received a DMP from you? Have you discussed this earlier with Jeff? Please let me know!

**Comment by FolakeBabalola** [comment]
Thank you, Esther, for the feedback. 
- The file name will be in this format: File name_date (e.g. Treatment performance_12-03-2024). Each file will be organised in subfolders (literature, methodology, results) in the case study area file (1. Imvepi and 2. Cox's Bazar). These will be embedded in the main folder (RISK-WASH Project)
- I appreciate the thoughts on file formats
- The wdpp repository is what we use in the project, and it is available on the IHE website. The 4TU.ResearchData is also a good option that I can explore
I did not discuss this earlier with Jeff; I have sent the feedback request to you. Sorry, I missed the action.

**Comment by FolakeBabalola** [comment]
> One of the things I learned from this course and could also be beneficial for both of us may be a directory file for each folder that shows what is in the folders and files. I also think the location can be anonymised by giving it an ID instead of the place name directly if the data is sensitive in nature.


I agree, implementing directory files for each folder and anonymizing location data with IDs can enhance organization and protect sensitive information in data management

**Comment by FolakeBabalola** [comment]
> Hi Folake!
> 
> The plan looks clear, despite the use of some acronyms of which I have no idea. I do wonder about how much storage space all those data will require, and it google drive and one drive would be the better options (for both confidentiality and space). Maybe it would be worth it to check on university storages - might be a pain to learn about how to use them, but probably it will be better in the long run, even for future students that may build upon your research.

Thank you @vgualtieri, for the nice suggestion. The university storages is also a good option

**Comment by FolakeBabalola** [comment]
> ### Introduction
> Hello! My name is Folake Babalola, and I am a student of IHE, affiliated with the Pure and Applied Sciences faculty at TU Delft
> 
> My research focuses on health and environmental risk assessments for sanitation service chains in humanitarian settings, by developing and piloting risk assessment tools in refugee communities and evaluating the usability and usefulness of the tools and their outputs for the humanitarian sectors.
> 
> ### My research entails the following aspects:
> Research Aspect	Answer
> Use/collect personal data (health data, interviews, surveys)	Yes
> Use/collect experimental data (lab experiments, measurements with instruments)	Yes
> Collaborate with industry	No
> Write/develop software as the main output of the project	Yes
> Use code (as in programming) for data analysis	Yes
> Work with large data (images, simulation models)	Yes
> Other:	N/A
> ### Reflections on the importance of RDM videos
> Losing the data I would generate during my research would be disastrous. RDM is crucial for me to complete my PhD program and have sufficient publications within the stipulated period (4 years). I want to avoid wasting time and the headache that comes with losing data due to poor backup.
> 
> ### What would you like to learn during this course?
> During the course, I want to learn how I can reproduce my data by incorporating good data management practices into my research and having an efficient workflow.
> 
> ### Checklist assignments
> * [x]  Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
> * [x]  Respond to the GitHub issue [Data Challenge #101](https://github.com/EstherPlomp/TNW-RDM-101/discussions/101)
> * [x]  [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://1drv.ms/p/c/f5c91a6b7fc6be5e/EbXYzWI6_1pOjHSnVDb2f3cBM4N9F2u4LP1xd-P56y41BA?e=gCoBAb
> * [x]  Provide feedback to at least one Assignment 2 from another participant
> * [x]  Respond to the GitHub discussion [Licenses #103](https://github.com/EstherPlomp/TNW-RDM-101/discussions/103)
> * [x]  Respond to the GitHub discussion [Folder Structure #102](https://github.com/EstherPlomp/TNW-RDM-101/discussions/102)
> * [x]  [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://1drv.ms/p/c/f5c91a6b7fc6be5e/ETVO7bW5oslDkPDMOoHWFCkBHGAlGoTL07tkEi3YxmmscQ?e=oQCWdZ
> * [x]  Provide feedback to at least one Assignment 3 from another participant
> * [x]  [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
> * [ ]  Respond to the GitHub discussion [Data Management Plan #104](https://github.com/EstherPlomp/TNW-RDM-101/discussions/104) if you have any questions (optional)
> * [x]  [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**) 
>   https://1drv.ms/p/c/f5c91a6b7fc6be5e/EQ-aL3gTyd9GpnSnh8_JkD4BDHZTycEgfehCj2eYhmr1NA?e=LSdMFo
