### ISSUE TITLE
Overview issue [Aimée Kok]

### ISSUE THREAD

**Issue by AimeeKok** [EstherPlomp/TNW-RDM-101#107]
### Introduction

Hi! My name is Aimée Kok and I'm a PhD student at the Bionanoscience department. :)

The main part of my research focuses on modelling the self-assembly of new viral particles inside host cells, specifically for the coronavirus SARS-CoV-2, based on experimental data from our collaborators. Moreover, I will work on side projects related to accuracy of biological signalling responses (right now, e.g., I'm working on the accuracy of the phototropism response in sunflower shoots).

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |

### Reflections on the importance of RDM videos
I believe that being open and transparant, like sharing the data and code for papers, is the essence of good science. The one example in the Markowetz video of where the analysis was wrong (aside from it being fraudulent, oof) due to being shifted by 1 array element, or his own example where his postdoc couldn't recover the analysis for giving the same model as before, makes me kind of scared that somehow a very silly mistake might slip through and impact the results. Also, losing research progress (code/data) in any way would be definitely be awful as well. 

### What would you like to learn during this course? 
In this course I'd like to learn general good practices for data management, especially in the context of collaborations. Until now, so in my MSc and BSc projects, it feels like I have always fumbled along a bit. For example, at the end of the projects I did provide commented code and the data used for the figures in the report, but I always had to redo stuff and look up and try to make sense of my folders and filenames at the end. I'd also want to be able to judge whether someone else's data management plan is adquate. For example, for the coronavirus research I have to use the DMP of the consortium to which this project is linked; I want to assess the quality of this DMP. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [ ] Respond to the GitHub issue #101
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #103
- [ ] Respond to the GitHub discussion #102
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [ ] Respond to the GitHub discussion #104 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by archana2810** [comment]
Hi Aimee,
I like how descriptive your data management plan is. I can't think of a better way to improve your plan at the moment. But i would like to appreciate your efforts on the details since it helped me rethink my plan as well. Cheers!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @AimeeKok! I can echo @archana2810's feedback that this looks fantastic! Well done on your super comprehensive back up strategy! 

I just have one thought:
- No worries should this change because of the consortium DMP, it is indeed good practice to follow the broader project DMP :) ( and good luck working in a big consortium, that can be overwhelming at times!)

And thanks also for all your great feedback on other people's assignments!

**Comment by maartjespaans** [comment]
Hi Aimee, 
Thank you for sharing your data flow map! As someone that won't use that much of coding during her PhD, it's interesting to see the different types of data that you will produce and how you have organized it. Amazing that you have such a good system for your back-ups! I could really learn from that :)

**Comment by olivierwitteveen** [comment]
Hi Aimee, cool to see your data flow map, it's super detailed. Your backup plan is super comprehensive. I'd be very interested to learn what your workflow is with SURFdrive / Project Drive and how you have things configured on your laptop, so I'll ask you at the office soon! I probably want to copy parts of it :)

**Comment by olivierwitteveen** [comment]
Hi Aimee, cool to see your updated data flow map!! Good point regarding Mathematica -- I had not considered that you can export it to e.g. PDF! It will indeed lose interactivity but if you comment the notebook really well, it can certainly be a helpful way to share results with others. I'll keep it in mind :)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 Aimée! As mentioned by Maartje - super detailed and comprehensive indeed! Well done!

Thanks Maartje and Olivier for the feedback!

Some small thoughts, as I have very little to add: 
- I like the idea of using ID numbers to shorten the file names - indeed, long file names are more descriptive but also not always ideal.
- Previous course participants were enthusiastic about Sphinx, so indeed perhaps just give it a try!
- Versioning with Git is indeed also documentation, especially if you comment on your changes!
- Indeed check with any consortium preferences for data/code sharing: consortiums should also have a DMP where this is outlined! You can also share your code/data in one upload on either Zenodo or 4TU.ResearchData and add the license information in the README to make a distinction for data and code. There is not really a wrong way of doing this, as long as there's a copy on a repository :) Zenodo is free up to 50 GB and 4TU.ResearchData allows up to 1 TB - which may push you towards one of them in terms of storage size requirements!
