### ISSUE TITLE
Overview issue [Loes Ettema]

### ISSUE THREAD

**Issue by lettema1** [EstherPlomp/TNW-RDM-101#108]
### Introduction

Hello everyone, my name is Loes and I'm a PhD student at the department of Imaging Physics. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

In our group, we work on a new imaging technique called Computational Scattered Light Imaging. With this technique, we can retrieve the direction of fibers or fiber bundles within biological samples (e.g. nerve fibers in a brain section). This is done by illuminating a sample from multiple angles with an LED light source, capturing the scattered light under normal incidence with a camera, and subsequently analyzing the change in intensity for each image pixel. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

The video shows good reasons of why RDM is important. I fortunately never lost my data, so I don't have a horror story. However, I do sometimes encounter problems when trying to remember how I performed my analysis some time ago. I therefore agree that it's important to work reproducibly.

### What would you like to learn during this course? 

During this course, I would like to learn how to save my data in a reproducible and save way and how the version control with Git works.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/2T0ISz9CZiHl2Jh
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/ZZ9xP0FmJvgEpRW 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by ignasisg** [comment]
I do feel the Data Flow Map 1 is very clear! It feels like you are dealing with more codes and images than me, which is interesting. Might need to consider some of your methods in the future.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @lettema1! And thanks for the feedback @ignasisg!

It looks very clear - well done! I only have a couple of pointers: 
- Some of the file formats are not super clear yet (I can guess from your descriptions!) - this becomes more important in [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html). 
- Project drive is indeed a secure and backed up solution!
- Great flag for the image sizes: that is indeed challenging!
- Some of the other course participants have also considered datasets like presentations, figures or meeting notes - you don't have to add these but you may want to consider them for your folder structure that you'll have to share https://github.com/EstherPlomp/TNW-RDM-101/discussions/102

**Comment by lettema1** [comment]
Thank you for the feedback!
About your question, I initially get the data from running a script in Python, after which I use that data in SPSS. In principle, I do not alter the data in SPSS, I only use some tools to visualize the data. However, it is possible to load the SPSS file in e.g. Python or R

**Comment by EstherPlomp** [comment]
Ah thanks for clarifying! Is there a way to do the visualisations with Python and/or R? That way even your visualisation would be reproducible!

**Comment by lettema1** [comment]
Yes, that would also be possible. However, since I'm not so familiar with programming, I preferred using different software
