### ISSUE TITLE
Overview issue Meryl

### ISSUE THREAD

**Issue by xxmeryl** [EstherPlomp/TNW-RDM-101#109]
### Introduction

Hi everybody! My name is Meryl Copray, I am 24 years old and I recently started as a PhD-candidate at the BioProcess Engineering group of the Biotechnology Department. I live in Rotterdam together with 2 friends and our furry friend George. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is a collaboration between the Bioprocess Engineering department of TU Delft and the Transplantation Institute of Erasmus MC focusing on determining organ viability during machine perfusion. In this project under the flagship 'Organ transplantation, making unsuitable organs suitable' I aim to: (i) investigate different high-end analytical methods to analyze the functioning and state of a donor liver, (ii) design and develop a sensor that can determine the health state via selected biomarkers and (iii) integrate the sensor in the organ perfusion set-up at EMC. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

The video was a good reminder of why we need data management. As I am starting to collect data and writing code to process this, I keep reminding myself to nicely document what and why I am doing things. Personally, I haven't heard any data horror stories (yet....)

### What would you like to learn during this course? 

Naming your documents nicely. Documenting the code writing process. Setting up a good filing system and having an overview of all the data and where everything is located. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/mcopray_tudelft_nl/EUVRrJZkhA1PuqPpVaMDfBkBflOh5SmC1_DRPep6UTQowg?e=uE0rKn 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/mcopray_tudelft_nl/EYJKB0UHl-9EnGAcBNhbhAwBpwgghtANRhUdCm7fdrmgTQ?e=FZSd3D 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [ ] Respond to the GitHub discussion #104 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 2 @xxmeryl, and also thanks to @ivyliang98 for the feedback!

This looks fantastic! Very nice and clear overview and I like how you separated the workflows and colourcoded them! Great use of flags as well for personal data and checking what you are allowed to do with data from collaborators!

My only suggestion is to perhaps consider to use version control for your scripts, and perhaps TU Delft Gitlab (a secure solution for personal data/code).

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 Meryl! It looks very clear and comprehensive again, well done!

I agree with Lena's comment on organising things in years - some of that goes very well (for example, Graduate School courses, conferences, presentations, meeting notes), whereas other things may not (projects and literature files). Perhaps something to take into consideration still!

Other than that I have some small thoughts: 
- While Excel/Word files are now more interoperable than they were before, they are still not open file formats as you'll need a microsoft office license to fully interact with these types of files. Open alternatives include .csv and .txt. 
- SURFfile sender is indeed a great solution to transfer data - don't do this via the TU Delft email or other external solutions with this type of data.
- 4TU.ResearchData also provides the option to share the data under restricted access. If one of your supervisors is publishing the data and listed as a contact person, any access requests will go directly to them. This may be an option for any data that cannot be publicly shared. 
- When sharing any Python scripts you'll have to consider a different type of license than those from data (see [here for the TU Delft approved licenses and more information](https://estherplomp.github.io/TNW-OS-support/posts/software-licenses/)). 

I hope this helps!
