### ISSUE TITLE
Overview issue Valentina Gualtieri

### ISSUE THREAD

**Issue by vgualtieri** [EstherPlomp/TNW-RDM-101#110]
### Introduction

Hi all! My name is Valentina Gualtieri and I am a 2nd year PhD in the Quantum Nanoscience Department. I have one fluffy black cat back home in Italy!

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

 My research focuses on the development of a new AI method to automatize the tuning of a specific quantum device.
By using some measured data, the goal is to train ML models to automatically set the quantum computer in the desired state to perform the computation or analysis we want to do.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  | Yes
| Collaborate with industry  | No  | No
| Write/develop software as the main output of the project  | Yes  | Yes
| Use code (as in programming) for data analysis | Yes  | Yes
| Work with large data (images, simulation models) | Yes | Yes
| Other:  | N/A  |
### Reflections on the importance of RDM videos

The first project I worked one was to take up the master thesis of a previous master's student and make a proper python package out of it. It was so poorly documented that I had spent more than 8 months reading, understanding, getting rid of useless code, fixing mistakes, and properly ordering it. By the end, I knew the code by heart basically. It would have probably taken less to redo it at once. This is how RDM became a number one priority to me for my work, but unfortunately I still fail every now and then.

### What would you like to learn during this course? 

I would love to get out of the course with a clear checklist to apply and check everyday to make sure I am doing the documentation right.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://tud365-my.sharepoint.com/:p:/r/personal/valentinagualt_tudelft_nl/Documents/RDM101_Assignment1_Week1_DataFlowMap_Template.pptx?d=wb02e4b60fd754a04a856a5e04aed775a&csf=1&web=1&e=wjj0yh 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/valentinagualt_tudelft_nl/EaBgvAAQaU5HuRoJT2jK3zEBJj0torL7H1oAPo1sjsGvew?email=E.Plomp%40tudelft.nl&e=70MgeK 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [ ] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 2 @vgualtieri - and for adjusting the access permissions :) 

It looks very clear! Nice to see the Python packages :). Some other pointers/suggestions:
- 4TU.ResearchDataset/Zenodo are data repositories to publicly share the data/code. For the current assignment the internal storage solutions were meant. The data repositories come back in the next assignment, so I guess you've already sorted that!
- Note that unless you're using your personal drive (H:) or network drives on the lab computer, files stored locally on your laptop/lab computer are not backed up! Other solutions such as the network drives / OneDrive and SURFdrive are better solutions for this!
- Nice use of the flags for memory required!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @vgualtieri! It again looks very clear and comprehensive! Thanks for sharing your folder structure and metadata information in detail! Well done!

I have very little feedback, just two thoughts/comments: 
- Other people mentioned [Sphinx](https://www.sphinx-doc.org/en/master/) for documentation purposes 
- Perhaps you already had this in mind, but please do make sure that any code that you share via gitlab/github also has a snapshot of it in a repository so that it will be preserved for the long term and will have a DOI assigned to it (and is following the FAIR principles!) Information on how to make code citable using GitHub/Lab and Zenodo can be found here: https://the-turing-way.netlify.app/communication/citable/citable-cite.html#citing-software

**Comment by EstherPlomp** [comment]
Finally @vgualtieri  I don't see your data challenge in #101 - Please still add that to complete the course!
