### ISSUE TITLE
Overview issue Maartje

### ISSUE THREAD

**Issue by maartjespaans** [EstherPlomp/TNW-RDM-101#111]
### Introduction
Hi my name is Maartje, I'm a PhD student at IMB.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
In my research I aim to develop distinctive beverage flavors through the engineering of (brewing) yeasts. I work on both the development of interesting flavors during the brewing process and expanding the genetic toolbox for engineering of brewing yeasts. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

Especially when I continue working on previous work from previous (PhD) students I notice how much easier the transition goes when the person had a proper RDM. In addition, I recognize myself in the anecdote "I did this analysis 6 months ago. Of course I
can’t remember all the details after such a long time" and praise or detest my past-self depending on how proper my RDM was for that research line. 

### What would you like to learn during this course? 
 Within my PhD I do not expect to use a lot of coding, however I do expect to produce a lot of data within the lab. Especially in the early stages of my research I produce a lot of data that does not seem very relevant yet, but end up being quite useful later on. I would like to learn how to structure my data more efficiently even though the data doesn't seem that useful in the first place. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [ ] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/hXLXrkVdAkRmkQJ
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/LnCt2SpXocmp2C0
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by AimeeKok** [comment]
Hi Maartje,

As feedback for your assignment 2: 
You mention your data is confidential, however the [storage solutions page](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/) states that the Staff-Group Drive (:M) (and also (:N), but you mention that is temporary) is not suitable for confidential data. Maybe an idea to switch to a Project Drive (:U) instead? It is also recommended to have at least one more back-up solution, maybe SURFdrive or anything your industry partner might have access to? As for the question mark at the master copy, I believe the master copy is meant as the most 'current' version of your data from which you make backups.

Hope this helps!

**Comment by EstherPlomp** [comment]
Thanks for sharing Assignment 2 @maartjespaans! It looks very clear!

Some suggestions:
- As @AimeeKok already indicated - while the :M is indeed backed up it can also be accessed by others, so please do check the access right before storing confidential data there. I think you're already aware, but the :N is not backed up so please do remove/transfer data from there as soon as possible!
- You haven't added the file formats yet, this will become more important for [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html).
- Other people have also included datasets such as Literature, presentations, meeting notes and so forth. You don't have to include those but these are also files/data to manage during your PhD!

**Comment by archana2810** [comment]
Hey Maartje, 
It flow from assignment 3 looks very clear to me, I was especially very interested to see how data involving industrial partners are treated. As said in class, I learnt a lot from everyone's work along with the material I used to prepare my own. Thanks!
