### ISSUE TITLE
Overview issue Mariana Carvalho

### ISSUE THREAD

**Issue by mcesarcarvalho** [EstherPlomp/TNW-RDM-101#112]
### Introduction
Hi all, my name is Mariana Carvalho and I'm a PhD candidate at the biotechnology department. I'm Portuguese and last year I decided to come to Delft to start this new adventure! :) 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research is focused on the development of an optimized laboratory setup specifically designed for purifying a biopharmaceutical product. For that, automated monitoring and control of process/product parameters as well as computational tools will be employed. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | Yes |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
Reproducibility and open science are crucial in my view, as they ensure reliability, transparency, and advancement of knowledge. I had issues with data management before. I find it challenging to establish and sustain a consistent, clear structure for my own data, particularly during busy periods when the primary focus is on achieving results. Also, as I'm working with modeling in my project, it's hard to understand data used in literature and replicate it independently.

### What would you like to learn during this course? 
I would like to learn how to work reproducibly to ensure that my work can potentially be developed further in the future. Also, I personally struggle to establish an effective structure that allows me to consistently locate data and comprehend it. Furthermore, since I'm working in collaboration with industry I have some confidentially concerns, which I would like to clarify before starting to store my data. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/j2DQLNE3oOzugu0
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/LqKywggBWwdZoAW
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by MaxThFe** [comment]
Your data flow map looks comprehensive, and it seems you have put a lot of thought into the different types of data you will create! Two things open questions that remain for me are: 

1. Do you use GitHub/GitLab to store code? ' If not, I can highly recommend it
2. What kind of data formats do you expect from the lab data?

**Comment by mcesarcarvalho** [comment]
Thank you for the feedback Max! :)
1. I never used GitHub/GitLab to store code. Is it relevant when I'm the only one working on the code? I have only heard about its benefits when working in a group, but maybe it's also useful when working alone to better track changes. 
2. I have no idea yet.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @mcesarcarvalho! And thanks for the feedback @MaxThFe! 

It looks very comprehensive so I have very little feedback:
- Do indeed pay attention to the file formats, this will become more important for [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html). 
- If you work locally with version control, maybe it is less needed, but I do like to be able to track when I did what and go back to older versions where needed using GitHub (and I also don't collaborate with others on code). Perhaps give it a go and just see if it will fit with your ways of working? For confidential data I would use [GitLab from TU Delft ](https://gitlab.tudelft.nl/)since that is a secure solution compared to GitHub. 
- You can also consider things such as figures, thesis chapters, presentations and so forth as a sort of dataset. You don't have to include them, but you may want to consider them in your folder structure!

**Comment by mcesarcarvalho** [comment]
Thank you so much for your feedback @EstherPlomp! I'll definitely consider your suggestions. :)

**Comment by MaxThFe** [comment]
Thanks for sharing your Data Flow Map (Part 2)!. Your overview looks very extensive. I especially like that you have also thought about data organization for other aspects of your PhD, e.g. Teaching, Meetings, Graduate School. I will try to implement a similar approach for my folder structure organization. 

Regarding access to Project Drive Folders for students, I am in a similar situation. I also want to share specific folders with students while keeping others hidden from them. Maybe in our next lesson we can exchange some ideas on how to implement that!

**Comment by mcesarcarvalho** [comment]
Thank you for your feedback @MaxThFe! Indeed, there's an interesting discussion to have. :)

**Comment by EstherPlomp** [comment]
Thanks for the feedback @MaxThFe! A good discussion to have indeed @mcesarcarvalho: Unfortunately, access management with the Project Drive is not great.. You may want to consider using OneDrive for this: students have their own accounts which might make it easier to interact with this rather than SURFdrive, but both could work if you need better access management compared to Project Drive!

Thanks also for sharing assignment 3 @mcesarcarvalho! It again looks very clear and comprehensive! I like how you share your information even when you're still in the 'consideration' phase of things and not yet in the implementation! :)  
- I'm glad to see that the course is inspiring you to try out some new things to organise the data/code!
- Excel is an interoperable format nowadays, but not an open format since you'll need a Microsoft license to fully interact with the files. An open alternative is .csv. Conversion may not always make sense here, especially if you have formulas in the Excel sheets which will be lost in any conversions. 
- You can indeed create a project drive just for a particular project for a particular student - there are no restrictions to how many you can requests (although you probably get flagged if you start requesting 50 of them :)). I would recommend asking new ones for students so that you do not have to worry about protecting your own folders/files from any accidental deletion/adjustments and/or for confidential reasons!
- U: / Project drives are indeed used for long term data storage - these drives are not deleted when a contract ends (unlike the personal drive H: and the One/SURFdrives!) So that is indeed a good storage location for the long term preservation of any restricted access data!
- And a bit of a repeat from the [license thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/103?sort=new#discussioncomment-8681868): please do let me know if you need any help with the software licenses!
