### ISSUE TITLE
Overview issue Siem Eerden

### ISSUE THREAD

**Issue by SiemEerden** [EstherPlomp/TNW-RDM-101#113]
### Introduction

Hi everyone! I'm Siem Eerden. I'm a PhD researcher in the Environmental Biotechnology group in the Biotechnology department. I'm originally from the Netherlands, and I live in Delft for quite some years already. I enjoy playing board games. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is about polymers produced by bacteria to form biofilms in wastewater treatment plants. Currently discarded as a waste product, but potentially useful as resource. I try to figure out how and why these bacteria actually make them, if that can be steered.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No |
| Write/develop software as the main output of the project  | No |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A |
### Reflections on the importance of RDM videos

It is a good reminder that proper RDM can save you a lot of time and trouble. You easily become complacent and think "Nope, these horror stories won't happen to me", until they do.. And then you wish you did this extra effort. I don't have a horror story myself (luckily), but I already learnt from practice that you should keep the structure of your data and scripts transparent to improve reproducibility (keep your workflow as centralized as possible i.e.).

### What would you like to learn during this course? 

How to set up a reliable backup strategy? How to best organize your files? How to use github for my python scripts? How do I handle dependencies from scripts to files?

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). [Link](https://tud365-my.sharepoint.com/:p:/g/personal/saeerden_tudelft_nl/EalWBi5LDM9InX13tuPp5HABB6ZLktq-S-TWVr1KU3gg_Q?e=cieYd6)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). [Link](https://tud365-my.sharepoint.com/:p:/g/personal/saeerden_tudelft_nl/ETfIxjAtfx9Jkifjn6cdBSMBf272Q2tBDRCnrdWgVwWFDw?e=2AbahP)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**). [Link](https://tud365-my.sharepoint.com/:p:/g/personal/saeerden_tudelft_nl/EUW5YnkVV_JIt98Oul0UVwIB8ZakuQqzwGYNHIUk20CDCw?e=JRe9uO)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @SiemEerden! This looks very clear - I like how you split all the different data workflows and your extensive backup strategy! Well done!

Some other suggestions/pointers:
- Regarding the reuse of data from databases: which databases will you use and under what license do they share this data? That will be important to check what you can do with the data! We'll talk about [licenses in the upcoming modules](https://estherplomp.github.io/TNW-RDM-101/07-FAIR-principles.html#data-and-code-licences).
- Data from databases/repositories are often protected by long term preservation strategies - so this data should not disappear, but it is always good to occasionally check or store a copy on the group/project drives if you want to make sure. I'm not sure how big these datasets are - but the project drive should be able to handle up to 100-200 TB, so that is hopefully sufficient. Don't forget to also delete this data again after a project is finished: if it is already available on a data repository and you have no active need of it any more, it is better to clean up the data that you don't use anymore and save the institute some costs for the storage space :)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 Siem! This looks very clear and comprehensive, well done again!

Some thoughts from my side: 
- Your folder structure and file naming looks organised! I did miss an example of the file naming.
- It sounds like you have the file formats more than sorted! Indeed, any conversions can result in loss of information so it may not always be the best option. 
- I assume that you found the (meta)genomes and HMMer profiles online via a data repository? This type of data is generally released under a CC0 license - so it is not just available online but freely reusable for others (which is not the case for all online content due to copyright!). 
- Indeed, if the data is already hosted by a data repository, resharing may not be necessary. You can link to this data in the [data availability statement](https://the-turing-way.netlify.app/communication/citable/citable-cite.html#citing-data) of publications/your generated datasets. 
- Publishing data in the supplementary files is not following the FAIR principles - the DOI is only for the article, and not for the supplementary files unfortunately! Some journals may also ask you to share the data in a data repository.
