### ISSUE TITLE
Overview issue Ezgi

### ISSUE THREAD

**Issue by ezgidemiroz** [EstherPlomp/TNW-RDM-101#114]
### Introduction

Hello, I'm Ezgi Demiröz. I'm at Catalysis Engineering section of Applied Sciences.
### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
 I am working on a hydrogen storage technology called "Liquid organic hydrogen carriers". They are basically liquids that can store and release hydrogen. I am loading hydrogen to them using electricity (electrocatalysis).

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/XFynN5cuJZb98Ye
- 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/qgnsdNxxqevNi6C
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by ezgidemiroz** [comment]
https://surfdrive.surf.nl/files/remote.php/webdav/Documents/RDM101_Assignment1_ED.pptx

**Comment by EstherPlomp** [comment]
Hi @ezgidemiroz! Thanks for adding a link to assignment 2! Can you please check the link? It looks like you shared a direct link which needs your login details instead of a public sharing link. Let me know if you need any help with that!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @ezgidemiroz! It looks very clear! 

Just some thoughts from my side: 
- Is there a confidential data flag because of IP/patent application possibilities? 
- I think most of your data will be collected in spreadsheets and .xlsx formats? File formats become more important for [assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html)! 
- Some other people also included datasets such as figures or presentations - you don't have to include these in your assignment but it can be helpful to also consider these data/files for your folder structure!

Can you please still share assignment 3 as well? Thanks!

**Comment by Adarsh-Shajimon** [comment]
Hi Ezgi! Thanks for sharing the assignment.
It looks clear and well structured.

You only mentioned the file formats for visualization studies. What other file formats do you work with? ( including spreadsheets Is it .csv or .xlsx or some other format? If it is .xlsx, switching to .csv would make it interoperable.)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @ezgidemiroz! 

Some comments/suggestions:
- Very nice folder structure overview on slide 1! This looks clear
-  For documentation: what information needs to be in the procedure/methods? Will you collect that in the form of a protocol or lab notes?
- For file formats in slide 4 the question is more about the format that the data is in: for example the .mp4 files you indicate for the last dataset. The file formats are not clear for the rest of your datasets (as indicated in earlier feedback), so it is difficult to see if you're working with open file formats or not from your assignment. This is important to keep in mind when you share and preserve the data for the long term!
- I think your data should probably be open, and not restricted access. You only indicate confidential data for the first dataset and even then the data underlying the publications should be published in the majority of the cases! As indicated in the feedback on your DMP: you may want to have another look at the [Data Publication materials](https://estherplomp.github.io/TNW-RDM-101/10-Realising-FAIR-Publication.html) to select a data repository to share the data. You'll indeed need to discuss this with your supervisors, and this is why the DMP is part of your Go/No-Go to ensure that everyone agrees with the plan!
