### ISSUE TITLE
Overview issue [Archana Sivaraman]

### ISSUE THREAD

**Issue by archana2810** [EstherPlomp/TNW-RDM-101#115]
### Introduction

Hello, I am Archana Sivaraman, I am a second-year PhD Student in the Department of Bionanoscience at the Faculty of Applied Sciences. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on correlating the sequence of DNA/RNA to the structure that it folds into and its biological function using a high throughput single molecule method. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

In my PhD, i have just dived into the phase of acquiring data. I can already foresee that it is important for me to document and organize my data in a very clear fashion that I or my colleagues can revisit at any point of time.

### What would you like to learn during this course? 

I would like to know about the tools in use and learn about best practices for organizing my data. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://tud365-my.sharepoint.com/:p:/r/personal/archanasivaram_tudelft_nl/Documents/Coursework/RDM/[RDM101_Assignment1_Week1_DataFlowMap_AS.pptx](https://tud365-my.sharepoint.com/:p:/r/personal/archanasivaram_tudelft_nl/Documents/Coursework/RDM/RDM101_Assignment1_Week1_DataFlowMap_AS.pptx?d=w3b3f73d2b7454aa0bad58174e5930daa&csf=1&web=1&e=psYgbh)?d=w3b3f73d2b7454aa0bad58174e5930daa&csf=1&web=1&e=psYgbh
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  https://docs.google.com/presentation/d/1H-CY4K2Yoz6wehYRkONGd9zbH0G8tItm/edit?usp=drive_link&ouid=116141702537938784226&rtpof=true&sd=true
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by AimeeKok** [comment]
Hi Archana,
your assigment link does not seem to work properly, it gives a '404 error not found' message :(

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 2 @archana2810! and for fixing the access rights - Well done!

@AimeeKok; can you try: https://tud365-my.sharepoint.com/:p:/r/personal/archanasivaram_tudelft_nl/Documents/Coursework/RDM/RDM101_Assignment1_Week1_DataFlowMap_AS.pptx ? Thank you for checking! 

Some pointers/suggestions from my side:
- Be careful of 'occassional' transferring of notes - ensure that this is in some sort of schedule that will trigger you to do this regularly (for example, end of the week, first or last day of the month, after you've finished a procedure, and so forth). 
- You haven't added information on the file formats yet: this will become more important for [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html).
- Another thing to consider are perhaps any figures you generate, any presentations/publications you'll work on and literature you'll use. 

And a question: 
- You added a red microscopy flag: is that because of the large file sizes? Or because you don't always have access to this? Is the data coming from a collaborator? 

I hope you'll get to try out OneDrive or SURFdrive soon! Let me know if any help is needed :)

**Comment by EstherPlomp** [comment]
And as promised the feedback for assignment 3 @archana2810! It looks very clear! I think you may have skipped over the metadata slide or is there another reason why that one is empty? 

Some thoughts:
- Keep in mind that the file names should also not be too long (I think here it is more the description that is resulting in a long name, which is probably fixed by shorter main attributes of the sample in the resulting file names)
-  For the file formats it doesn't become clear what file formats you use, apart from Python scripts which are indeed open!: so it is difficult for me to judge whether those are open or not. 
- I think your data will probably be classified as open - but do discuss it with your supervisor. If you do not work with any commercial data/companies/consortia in general the default is open. It will be important which data repository you'll use in that case!
