### ISSUE TITLE
Overview issue: Adam Mubeen

### ISSUE THREAD

**Issue by adammubeen** [EstherPlomp/TNW-RDM-101#116]
### Introduction

Hello, I am Adam Mubeen. I'm an external PhD candidate and I'm from an island. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is about bringing together knowlegde and experiences in water engineering, risk management, and landscape design together to explore how to design nature-based solutions. It also dives deeper into accounting for uncertainties in climate projections during design and how we can be safer even when the measures fail.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  |  No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  |  No  |
| Collaborate with industry  |  No  |
| Write/develop software as the main output of the project  |  Yes  |
| Use code (as in programming) for data analysis |  Yes  |
| Work with large data (images, simulation models) |  Yes  |
| Other:  |  N/A  |

### Reflections on the importance of RDM videos

Is it a bad project, bad data, or just bad management, processing or visualisation. 
It's a trap!?! Take a better look at what I'm receiving before agreeing to do anything. 
We need to manage information and knowledge better collectively if we don't want to repeat the same mistakes or spend excessive amounts of time, energy and money on finding stuff that's already been done.

### What would you like to learn during this course? 

What are the data management mistakes I am making, and how I can correct it.
What resources are available within the faculty for this purpose, and how I can incorporate that into my workflow
How we can share the things that we cannot publish

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/YX2tzplH3EfjlXZ
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/YX2tzplH3EfjlXZ
- [x] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [ ] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by FolakeBabalola** [comment]
In your research aspect, I was hoping that your research would focus on software development without the use of personal data. Gowing by your data flow map, it becomes clear that personal data is an integral part of your research.

**Comment by adammubeen** [comment]
> In your research aspect, I was hoping that your research would focus on software development without the use of personal data. Gowing by your data flow map, it becomes clear that personal data is an integral part of your research.

Most of my work involves building, improving and bringing together existing models within the project. 
The interviews are meant to be stakeholder interviews, but not necessarily anything where I collect personal information, for determining whether the framework is performing as expected.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @adammubeen, and for the feedback @FolakeBabalola!

It looks very comprehensive and clear, so I only have a couple of pointers and a question: 
-If your data is stored both on SURFdrive in the cloud and locally you should have everything backed up. If everything is just in the cloud for SURFdrive maybe you want to sync this in another location as well to just be sure. 
- Great use of flags!
-  For some of the datasets you haven't indicated the file formats yet, that becomes more of a consideration for [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html)!
- Will the 1TB for SURFdrive provide you with sufficient space? Or are these models/spatial data not huge in data size?

**Comment by adammubeen** [comment]
@EstherPlomp The model itself isn't very large but the input files, output and many runs required may need more space. However, I do not expect it to exceed 1 TB as long the files are not duplicated, or the data from trials and previous iterations are removed in a timely manner.

**Comment by EstherPlomp** [comment]
Great, then you should not run in any trouble @adammubeen! 

Thanks also for sharing assignment 3 - it again looks very comphrensive and clear again, so not a lot of feedback from my side: 
- Great considerations with ArcGIS and QGIS, as well as the European environmental agency's geospatial data guide

Well done!

**Comment by vgualtieri** [comment]
Hi Adam!
Here is my feedback:

1. Data organization:  it is nice to see that you have a structured approach. It would have been even nicer to have a visual representation of the folder structure, just to help for the understanding :) I liked the naming convention.

2. Documentation: Very clear and comprehensive!

3. Metadata: I don't know the details of your files, so I can't really give feedback here, however, I have the impression that it might be more detailed/more information could be added.

4. File formats: that 'yes and no' answer sparked my curiosity. what do you mean? Feel free to elaborate a bit.

5. Data access & data publication: everything looks good!

Congrats on the job!

**Comment by EstherPlomp** [comment]
Great feedback @vgualtieri - thanks for such a comprehensive review!
