### ISSUE TITLE
Overview issue Ignasi

### ISSUE THREAD

**Issue by ignasisg** [EstherPlomp/TNW-RDM-101#117]
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

Very interesting video, but I liked the paper better. I felt it was clear and fun to read.
### What would you like to learn during this course? 

I guess how to work safely with my data, ensure I have enough back-ups and know where to store those.
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [ ] Respond to the GitHub issue #101
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #103
- [ ] Respond to the GitHub discussion #102
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [ ] Respond to the GitHub discussion #104 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @ignasisg! It looks like the sharing link broke for your assignment 2 and 3:  Could you please check and re-share the links? They were working before!

**Comment by EstherPlomp** [comment]
Thanks for updating the links @ignasisg! Assignment 2 looks very comprehensive, well done! 

I have a couple of questions: 
- If you use webdrive you're probably using one of the network drives of TU Delft - is that the project drive or the Bulk drive (:M)? Webdrive is the software/service that we use to access these network drives.
- I find your red flag interesting - is it because it is difficult to share data with others in TU Delft?
- what is lb? (you use to indicate data sizes?)

**Comment by EstherPlomp** [comment]
And some feedback for assignment 3 as well: 

Indeed, the template is a bit repetitive sometimes - you found a nice way around it :) 

- Glad to hear that you're using the README file and an ORCID!
- Python is also an open format/language.
- You did not add your preferred repository to the assignment, but I saw [4TU.ResearchData](https://data.4tu.nl/) in your data management plan. I hope that is indeed the intended repository?

Let's discuss licenses before session 2 or during the break/after? I can also walk by your office in the morning of the 12th if that is easier!

**Comment by xxmeryl** [comment]
Hi @ignasisg , your assignment 3 looks nice! The only question/remark I have: it seems like your file naming system is very long (>30 something characters which is recommended). Is it possible to abbreviate somethings, or is this the best way for you to incorporate all the important parameters?

**Comment by ignasisg** [comment]
Good point @xxmeryl! I'll think my way through your recommendation. :)
