### ISSUE TITLE
Overview issue Olivier Witteveen

### ISSUE THREAD

**Issue by olivierwitteveen** [EstherPlomp/TNW-RDM-101#118]
### Introduction

Hi, my name is Olivier and I am a PhD student in theoretical biophysics at the Bionanoscience department. 

### Describe your research in 2-3 sentences to someone that is not from your field

I use tools from information theory and statistical physics to understand biological systems, particularly gene expression. The expression of genes needs to be regulated precisely, especially when these genes encode proteins that are important for an organisms to develop in a healthy way. How do organisms maintain this regulatory precision, despite the noise in molecular signaling networks?

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I do share the anxiety that a small mistake in one's research leads to catastrophic consequences. I wouldn't want to be deceived by a mistake I made myself. This is, of course, where Open Science and reproducibility plays an important role -- one can always prove you had good intentions, plus having more eyes on the back-end of the project may prevent these mistakes in the first place. Further, losing data is always a scary concept but in principle everything I do should be backed up in the cloud. But perhaps during this course I will learn how to minimise this risk even further. 

### What would you like to learn during this course? 

I find it difficult to organise my data and scripts in a way where I keep what is important, and remember what everything was for. Especially in early stages of research projects, one might try many things that you may not use in the end. But I'll still keep all the scripts in case it's useful later. I now have folders called "old" in most of my projects' directories that keeps all the out-dated things, but obviously this isn't a super clear way of keeping track. I do find myself digging in this folder surprisingly often, so I would like to learn a better way of handling this. Further, I'd be interested to learn how to better share and communicate code/data with collaborators. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). [Link](https://tud365-my.sharepoint.com/:p:/g/personal/ozjwitteveen_tudelft_nl/EXSdsD7jQl5PkgBUtpTrKPQBY5eR9jwjKH3nbkdWCqKyPg?e=XT6iim)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). [Link](https://tud365-my.sharepoint.com/:p:/g/personal/ozjwitteveen_tudelft_nl/EVcpI4n4K71Mqd9yTrTlbUAB_0e1qFwFwVGw-22zYHtBIA?e=idW7KF)  
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by AimeeKok** [comment]
Hi Olivier,

some feedback for Assignment 2: 
I would recommend using GitHub for version controlling your notebooks (it is not overkill :P), though searching back through old commits can also be a hassle if you don't write proper commit messages (I'm very guilty of that lol). I'm not sure how iCloud specifically works, can you access it like a folder on your laptop? Because in that case you can set up a daily automatic backup to any other location (your OneDrive folder e.g.) with a backup tool like borg (Pietro showed me this, might be nice!)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @olivierwitteveen! And thanks also for the helpful feedback @AimeeKok! Version control is rarely an overkill indeed :) 

I think this is a very nice/clear overview! 

Some pointers/suggestions for your assignment:
- You haven't included file types/sizes yet: the file types will be more important for the upcoming [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html)
- Very nice that you got a digitalised note taking workflow! Instead of backing this data up 'occasionally' - I would suggest to set a standard date: a certain number in the month or the first Monday of the month for example. Or when you round up a laboratory procedure. This way you get triggered to actually do the back ups! Borg (mentioned above by Aimée) also sounds interesting - if your backups can be done automatically, this would be preferable because otherwise you're likely to forget it at the wrong moment!
- If all your OneDrive files are also backed up locally on your computer itself and not just in the cloud, you are also following proper back up procedures - but I can also imagine if you want to have an additional back up of important data :)
- I also linked this in your data challenge, but just copy pasting it to be comprehensive here: Some information on version control and jupyter notebooks can be found here: https://coderefinery.github.io/jupyter/version-control/.

**Comment by maartjespaans** [comment]
Hi Olivier, 
Thanks for sharing your data flow map. I especially appreciate your thinking about where to store your notes. It made me realize that I actually should also think about where and how I store my notes, so thanks for that! :)

**Comment by AimeeKok** [comment]
Hi Olivier,

some feedback for Assignment 3:
Your folder structure is really clear! (and seems like it was already pretty well organized in the Folder Structure discussion haha) Also with the documentation it seems you were already implementing a lot of good practice and the additions will only help make it better. Also not from your side but the experimentalist side, I wonder why they just not use .csv files in the first place? Anyway, everything else looks good as well. Great job! 👍

**Comment by maartjespaans** [comment]
Hi Olivier, 
Thank you for sharing your dataflow map. I think you have a proper and well organized data organization. One advice for your naming convention, if you use the order YYYYMMDD, your files will be automatically ordered by date. For me that works best to keep my folders organized. Hope this is useful. :)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @olivierwitteveen! It again looks very nice, clear and comprehensive: well done! Especially the folder structures as Aimee and Maartje are highlighting! Thanks both for your feedback as well!

I therefore have very little feedback: 

- For sharing any data/code: prioritise getting it into the article instead of supplementary files, or share it in a data repository as the supplementary materials are not in accordance with the FAIR princples. It is ok to not know right now where to share these materials, especially if you're dependent on collaborators. Keep it in mind/describe your preferences in your data management plan so you'll at least be aware of your options!
- Perhaps ask your supervisor whether they can sponser a dropbox subscription for your project? It sounds like you're heavily reliant on it and dropbox is safer than our emails. If you want to send files to your collaborators you can also use [SURFfilesender](https://filesender.surf.nl/).
