### ISSUE TITLE
Overview issue [Ivy Liang]

### ISSUE THREAD

**Issue by ivyliang98** [EstherPlomp/TNW-RDM-101#119]
### Introduction

Hi everyone, my name is Ivy Liang, I'm a PhD student in Gijsje Koenderink's lab in the department of Bionanoscience. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I study the human wound healing process at the cellular level. I look at how the direct environment of cells determine the outcome of wound healing, so whether it heals correctly or you're left with significant amount of scar tissue.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I understand the importance of good data management. For me, a horror story was that I was analyzing microscopy images on my laptop, but my laptop had some issues. So, the screen turned black after a while, and I was panicking that I had lost my results of the analysis. Luckily it still turned on and I made a back up immediately. 

### What would you like to learn during this course? 

How to properly/professionally manage my data, so that it's easy to find and easy to find back what I've done.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/ivyliang_tudelft_nl/EX8k1eDUWFpHkwrz2V34VGQB4VJKjwyW5wdbvmkilH3iJQ?e=Unx0lJ 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/ivyliang_tudelft_nl/EXW3uHZMpc1IpBmj5q_Ye7AB6VOlRiX3RZ3OWzlY6AHMTQ?e=biG8lO 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by lettema1** [comment]
Hi Ivy,
I had a look at your Data Flow Map, and I think it looks good!
You've included a lot of different types of data. Using the M: drive and a proper back-up seems to be a safe way for storing all your data. Looking at all types of data, I can imagine that (as you mentioned in the Data Challenge discussion) it can be hard to find a good way of structuring your data and results.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @ivyliang98! And thanks for the feedback @lettema1!

It looks very clear and comprehensive: well done! I therefore have very little feedback: 
- I like how you're also considering your presentations and literature files in the data workflow!
- Perhaps you already included lab notes in the protocol dataflow: this is indeed also information is also data that should be managed! 
- For managing your R-scripts you may also want to consider using version control, or GitHub/GitLab: we'll go a bit into that in the [documentation module](https://estherplomp.github.io/TNW-RDM-101/09-Realising-FAIR-Documentation.html).

**Comment by SIM1-S** [comment]
Hi Ivy, I've taken a look at your Assigment 3, and i'm very impressed! Your slides are quite detailed and you have clear answers to most questions. I do have some comments:

- I read that you plan to make folders for each year of your PhD. I could imagine for (sub)projects that span more than 1 year (or start and finish in different years) that this might be a bit confusing. 

- Further, it also strikes me that your file names are a bit long. This might be difficult to read, especially for someone outside of your project.

- Lastly, you do not have any metadata mentioned with your Edited images from the Microscopy Data. I could be useful to also save metadata (or notes) with these images, as you could specify what edits have you made to the images and how could someone else achieve the same.
