### ISSUE TITLE
Assignment 1 - Adarsh Shajimon

### ISSUE THREAD

**Issue by Adarsh-Shajimon** [EstherPlomp/TNW-RDM-101#120]
### Introduction

Hi, my name is Adarsh Shajimon and I'm a PhD Candidate at the Environmental biotechnology section of the Biotechnology department in the faculty of Applied Sciences. I am from India, and I started my position here in May, last year.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on developing a bioflocculant from biopolymers extracted from wastewater sludge. These biopolymers, called extracellular polymeric substances (EPS) are extracted by hot-alkali extraction, and they have properties similar to flocculants (polyelectrolyte). My research is trying to understand what the driving factors for flocculation are in these EPS, and to fine-tune them to develop an environmentally friendly bioflocculant.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I think it should be an essential part of a proper scientific research methodology. It has more benefits than downsides and will definitely help researchers in their work. Personally, I don't have much horror stories with data so far, but I had previous experiences with bad file organization which led to a lot of time wasted in searching for a particular file from a sea of files.

### What would you like to learn during this course? 

I would like to understand and learn how to properly store, share and collaborate data using a cloud platform like Github so that I can use it for my projects in future.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/QMltevzD4sVTVSP
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/1eddfdM2KInzG2I 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by EstherPlomp** [comment]
Thanks @Adarsh-Shajimon for sharing assignment 2 - it looks very clear! Well done! I like how you also included presentations in your data workflow!

Some suggestions/pointers: 
- We go a bit into lab journal management in the [FAIR documentation module](https://estherplomp.github.io/TNW-RDM-101/09-Realising-FAIR-Documentation.html). If you're using paper it is of course fine, but do make a copy of it somewhere so that you don't loose data/information when you loose the physical lab notebook!

And a question:
- What does the for future flag mean? Is this about a future project? (as long as it is clear to you it is also fine, but I'm just curious now!)

**Comment by 18810704625** [comment]
Hi Adarsh, I read your data flow map. It is very clear to store all different data according to their sources and types. There is only one advice: 
Since you've only listed your raw data storage method, it would be better to clarify them by their relation and consolidate some data in one place. Otherwise, end up with too many different files.

**Comment by EstherPlomp** [comment]
Hi @Adarsh-Shajimon! I don't see a link or comment with your assignment 3: Please still add this as soon as possible!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @Adarsh-Shajimon! It looks very clear, well done!

A couple of suggestions/thoughts: 
- Nice file naming convention! I'm happy to hear that the course is inspiring you to reorganise the files according to your new file naming convention!
- For metadata, are 'Equipment details, measurement software, measurement file formats' indeed the only metadata you'll need?
- Indeed, sometimes with file format conversions information will be lost (particularly in powerpoint files and spreadsheets). Sometimes conversion makes less sense - that will be up to you to consider :)
