### ISSUE TITLE
Issue Lena F.

### ISSUE THREAD

**Issue by lenafasching** [EstherPlomp/TNW-RDM-101#121]
### Introduction

Hi all, my name is Lena. I am a PhD student at PPE in Chemical Engineering. Besides work, I really enjoy hiking, skiing, doing basically anything outside in the sun. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research aims to develop a wearable sweat sensor,  a small device that can be worn on the skin, that measures certain proteins in a person's sweat. By doing so, we would be able to tell the person something about their health status, for example, if they are at risk of developing an infection or a disease. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes/No  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I think the videos made clear how important good data management is, not only for other people but also for ourselves. It is not only about integrity and fraud but also about sharing valuable knowledge and avoiding the repetition of mistakes and waste of time. 
One horror story I can share is that during the first few weeks of my master's end project, I was doing it at a company, I had to go through some data of a colleague to collect useful information and avoid making the same mistakes. It took me hours and hours to even understand how he was storing data, and hours again to extract useful information. With one text file explaining that, I could have managed to the same job in less than one day most probably. 

### What would you like to learn during this course? 

I would like to learn and get to know some best practices of others, that I can adapt for my own system, in particular collecting and analysing of experimental data.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [X] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: [RDM101_Assignment1_DataFlowMap_LF.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/14343263/RDM101_Assignment1_DataFlowMap_LF.pptx)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Sorry for the handwriting, I am currently not able to use my laptop. link: 
[RDM101_Assignment1_DataFlowMap_LF.pdf](https://github.com/EstherPlomp/TNW-RDM-101/files/14558812/RDM101_Assignment1_DataFlowMap_LF.pdf)

- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

[RDM101_Assignment1_DataFlowMap_LF.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/14343263/RDM101_Assignment1_DataFlowMap_LF.pptx)

**Comment by SIM1-S** [comment]
Hi Lena, i took a look at your assignment 2, and it was very clear! I am wondering if you could provide more detail on the explanation for what each of the data folders actually contains? 
Also, is it possible for you to separate your data folders from your experimental results a bit more? What is going to happen to the processed results from the XPS Elemental analysis for instance? (graphs?) In what format are these files?

**Comment by lenafasching** [comment]
Thanks, Simone! Very good points, I will try to address them!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @lenafasching! It looks very clear and comprehensive, well done! I like how both you and @SIM1-S also incorporated literature, and also things such as meeting notes. These are indeed also files/data that need management :)

Thanks also for the feedback @SIM1-S!

Similar feedback as in @SIM1-S's issue: A thing to consider is whether you could use GitLab/GitHub for managing your analysis scripts! We'll go a bit into that in the [documentation module](https://estherplomp.github.io/TNW-RDM-101/09-Realising-FAIR-Documentation.html).

**Comment by lettema1** [comment]
Hi Lena,
I just had a look at your assignment 3. You use very clear and complete names for your data, so I don't think you'll encounter any problems when trying to find the data back again after some time. 
However, I can only see the first 4 slides. Maybe something went wrong with uploading the pdf file?

**Comment by EstherPlomp** [comment]
Thanks for sharing assigment 3 @lenafasching! I agree with @lettema1 that your file naming conventions look very clear - well done! 

It does indeed look like this is only part of the assignment - can you please check again and share the rest of the assignment as well? Thank you!

**Comment by EstherPlomp** [comment]
Thanks for updating your assignment 3 @lenafasching! It looks clear, especially your folder structure sharing is great - well done! 

Some minor things: 
 - Slide 9, Q3 does not seem applicable to your research data, so you can leave that as it is. For Q1 on where to publicly share the data/code: GitHub is great to share and collaborate on code, but it is not a long term preservation platform and it also doesn't assign DOIs. For that you will need to use a combination with a data repository such as indeed the one that is managed by TU Delft: [4TU.ResearchData](https://data.4tu.nl/). 
 - Indeed, always discuss these things with your supervisors, especially if they are also listed as a contributor or author on the dataset!
