### ISSUE TITLE
Assigment 1 Simone Smink

### ISSUE THREAD

**Issue by SIM1-S** [EstherPlomp/TNW-RDM-101#122]
### Introduction
Hi,
My name is Simone. I am from Eindhoven, the Netherlands and I am a first year PhD at the department of Chemical Engineering. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
Although I do work in the ChemE group, my research focuses more on biological processes. I am particularly interested in the exact mechanisms of cancer metastasis and how to study this outside of the body using microfluidic devices.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  |No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
It is to my experience very important to work with proper RDM. I have previously worked for the department of Experimental Pharmacology at Utrecht University. As some people might know, the content of the storage system of the entire university (YODA) was deleted through human error. This left quite a few people with a lot of issues, including myself.

### What would you like to learn during this course? 
I would like to get a clear plan for myself on how to store my current and future data. Along side some tips how to store and access large amounts of data. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**).  
[RDM101_Assignment1_Week1_DataFlowMap_SimoneSmink.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/14345681/RDM101_Assignment1_Week1_DataFlowMap_SimoneSmink.pptx) [Surf drive Link](https://surfdrive.surf.nl/files/index.php/s/QUns0b3N7RCsPWg)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link:  
[RDM101_Assignment3_DataFlowMap_SimoneSmink.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/14493471/RDM101_Assignment3_DataFlowMap_SimoneSmink.pptx) [SurfDrive Link](https://surfdrive.surf.nl/files/index.php/s/ZdpjO9B5dvd9X4r)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by lenafasching** [comment]
Hi Simone, 

I had a look at your Assignment 2 (as promised :) ). I think you did a really good job! Very clear and detailed, and very well structured. The only thing I noticed is that the lab journal was not explicitly noticed. I think you include it in the protocols, but since it is the key to all your experimental data in a way, I think you could include it as an extra point. I personally also include some text files with my data, where I note some experimental details and explanatory notes but that is only a side note and I guess also personal preference.
But very well done!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @SIM1-S: it looks fantastic - well done!

Hats off to @lenafasching as well for the feedback on the lab journal or notes - I think that might be the only thing that is missing here, so I have no further feedback! (Other than perhaps a good luck with working with these different datasets and large data!)

**Comment by ivyliang98** [comment]
Hi Simone, I had a look at your 3rd assignment. It looks very good. I like how detailed it is; it gives me some inspiration for my own data :)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @SIM1-S! Like @ivyliang98 is saying, it looks very clear and comprehensive! Well done!

A couple of suggestions/thoughts:
- Very clear data organisation structures and file naming conventions!
- Nice to read that you're using README files for the experimental setup!
- Great metadata overview(s)!
- MATLAB is actually proprietary, so resulting files are not open and you would need a MATLAB license to interact with them. An open example would be Python. 
- Why is restricted access needed for the image data and design data? I don't see any confidential flags here! 
- GitHub is great to share code indeed, but it is not a long term preservation platform and it does not assign DOIs to the code - [Zenodo has a nice integration with GitHub](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) that shares a snapshot of the repository on Zenodo and assigns this DOI that you then can link back to your GitHub Repo. That way your code becomes citable as well! (See also the [citation.CFF file,](https://the-turing-way.netlify.app/communication/citable/citable-cff) with an [upcoming event about this on 19th of March](https://docs.google.com/forms/d/e/1FAIpQLSejkAFCkQTH6yUIs0wue4w1lNj1WQmbIPol-BjwXaqg22DLDw/viewform)!)
- Genomics Data Commons looks like a great way to share your data!
- With NoteNote do you mean OneNote? (slide 37) Or do I need to look further for NoteNote :) 
- Note that microsoft office files (.xlsx / .docx) are interoperable nowadays but not open - you'll need microsoft office licenses to fully interact with the files. Open alternatives can be .csv and .txt. For the purpose of accessibility/interoperability this is fine though!
