### ISSUE TITLE
Overview issue Max Theisen

### ISSUE THREAD

**Issue by MaxThFe** [EstherPlomp/TNW-RDM-101#124]
### Introduction
Hi all, my name is Max Theisen. I am from Bonn in Germany and I am a first-year PhD student in Chemical Engineering. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research group focuses on the application of AI in Chemical Engineering. I specifically work on AI for process operations. For that, I simulate data or take data from literature and industry.

### My research entails the following aspects: 
| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | No  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

Good data management is key in research because it helps us use and share findings easily. Bad code from colleagues or not being able to repeat others' experiments are big problems that I have experience myself. With better organization, we can all work together more smoothly. A good example for this is AI research, a bad example chemical engineering research.
### What would you like to learn during this course? 
I am always curious about better ways to make my code and data available. Especially managing large datasets is sometimes challenging.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **15 February, 10:00**)
- [x] Respond to the GitHub issue #101
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **22 February 13:00**). Link: [Assignment 2](https://tud365-my.sharepoint.com/:f:/g/personal/maxtheisen_tudelft_nl/Euo3x_UJwatPosEngEp8i0EBnESsZI3nUlyY-842wh-oDg?e=Ep6lFo)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #103
- [x] Respond to the GitHub discussion #102
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **5 March 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/maxtheisen_tudelft_nl/EULK-Rc7hWhFkfkmVScwpc4BAuV5Yq03dTw_8K41oVyqVQ?e=jHel2r
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **8 March, 13:00**)
- [x] Respond to the GitHub discussion #104 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **11 March, 17:00**)

**Comment by mcesarcarvalho** [comment]
Hi Max! Your data flow map is well-structured and clear. 😊 Good that you considered your file formats and sizes. I think we have similar projects in terms of our data (sensor data and trained ML models) and I was wondering about your backups, because OneDrive is limited to 1TB. The project U-Drive allows for up to 5TB. Have you considered the criteria for choosing which files to include in the backup?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @MaxThFe! It looks super nice and clear! 

Good question @mcesarcarvalho - thanks for the feedback!

Some other suggestions/pointers:
- If you work with the industrial productional data, which is confidential data, will the process simulation data also become confidential or not? 
- Under what licenses are the public production data shared? This will determine what you can do with the data. We will discuss [licenses in a future module](https://estherplomp.github.io/TNW-RDM-101/07-FAIR-principles.html#data-and-code-licences)!
-  Do consider that GitHub may not be a suitable solution for the confidential data/code: TU Delft doesn't have agreements with GitHub so Microsoft may do what they like with your data/code that you share there. If you have confidential data/code, [TU Delft GitLab](https://gitlab.tudelft.nl/) is more secure. If the code is not confidential it is no problem to use GitHub.

**Comment by ignasisg** [comment]
Hi Max, 

Your Data Flow Map 2 is very clear to me, even though I have no idea about your topic. Would be interesting to have a F2F chat regarding everything related to codes. I feel you know better how to save and manage those, and I am starting to implement more in my research.

**Comment by mcesarcarvalho** [comment]
Hi @MaxThFe! 
I think your assignment 3 is really well thought. It seems like you have a clear overview on how to document code (e.g., automatic code documentation) and experiments and to control versions. That is something I would like to discuss with you because I feel like you know a lot about it. 
As you are also collaborating with an industrial partner, I was wondering about the type of license that you will use. Do you think CC BY will bring problems regarding confidentiality? This topic is still a bit vague in my mind, because they are very strict with the content that is published.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @MaxThFe! It looks super comprehensive and clear! Well done!

I have very little feedback, only some notes on the use of GitHub below!
- Previous course participants were positive about Sphinx: good luck with trying things out!
- I had not heard about WandB before, so I also have some checking out to do!
- Nice to learn about de DEXPI standard as well - great initiative!
- I assume you use private GitHub repositories for the confidential code? [GitLab repositories managed by TU Delft](https://gitlab.tudelft.nl/) are a securer solution for that - but if your industrial partners do not mind it is fine of course.  
- GitHub is great to share code indeed, but it is not a long term preservation platform and it does not assign DOIs to the code - [Zenodo has a nice integration with GitHub](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) that shares a snapshot of the repository on Zenodo and assigns this DOI that you then can link back to your GitHub Repo. That way your code becomes citable as well! (See also the [citation.CFF file,](https://the-turing-way.netlify.app/communication/citable/citable-cff) with an [upcoming event about this on 19th of March](https://docs.google.com/forms/d/e/1FAIpQLSejkAFCkQTH6yUIs0wue4w1lNj1WQmbIPol-BjwXaqg22DLDw/viewform)!)
- CC-BY is a license used for data but generally not for code: please check out the [TU Delft approved software licenses](https://estherplomp.github.io/TNW-OS-support/posts/software-licenses/): MIT, BSD, Apache, CC0, GPL, AGPL, LGPL, EUPL.

Thanks also for your feedback @mcesarcarvalho! I think the licenses are perhaps not the most stressing issue regarding confidentiality - the issue will probably be more focused on what you can and cannot publicly share. Once you share it publicly with a license, it is out there and perhaps some competitive advantage is lost - which is generally what the industrial partners care most about. So as long as you have the permission to share, I doubt they'll be on top of the license much! It is still important to discuss this with them of course :) Hope that helps a bit in making this less abstract!
