### ISSUE TITLE
Overview issue [Roald van der Kolk]

### ISSUE THREAD

**Issue by rjhvanderkolk** [EstherPlomp/TNW-RDM-101#129]
### Introduction

Hello, My name is Roald van der Kolk, I do a PhD in 2D materials, Quantum optics and superconducting devices. I also have the personality of a cat.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

To quote my supervisor, just before I started giving a talk in the optics cluster; Just a disclaimer, I have no idea what he is doing. Anyway; my research is on Quantum optics, 2D materials, superconducting diodes transistors, single photon detectors and integrated photonics. lots of fun!

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | nope, I think  |

### Reflections on the importance of RDM videos

there was an image of two cute dogs and the appearance of statistics wizards was also pretty cool. Anyew, a lot of solid examples on what not to do. Should add that ironically sometimes the laptop is safer as one of the server rooms of the TU Delft was once almost flooded. Most interesting to me is that it improves the amount of citations, so very nice! Also like the idea of being able to change already published work more easily.

### What would you like to learn during this course? 

Improve a bit on organization of data, pick up some new tricks

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/ziOHDIonmmS4bRW
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/tC1zVJAfZ8Mgu8S
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @rjhvanderkolk! It looks (mostly) clear, well done!

- The measurement data is not entirely clear to me - is this because you only just started your project? What are these different softwares? Are these proprietary? 
- I agree with @mmsavic that only storing your files locally is not ideal - your local drives are not automatically backed up so you're prone to loose data if anything happens. As long as you have a back up of the files on the U:/ drive this is of course solved!
- Since you're working with code/Python, you may want to consider using GitHub/GitLab to manage your code. TU Delft has a GitLab instance for example: https://gitlab.tudelft.nl/

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @rjhvanderkolk !

- don't forget to share your [folder structure in the discussion thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/127) as well! What you're saying in this assignment seems clear, but an overview of a structure makes it a bit easier to provide feedback on!
- Do you need to document any variables used in your scripts? Is sample/location/time really the only information? 
- I'm a bit confused by the answers you're giving regarding public data - if you share it publicly on Zenodo people do not need to make a request to be able to access/reuse the data/code. Zenodo also gives a DOI for any upload! 
- Indeed, always discuss sharing data/code with your collaborators/supervisors!

**Comment by EstherPlomp** [comment]
Hi @rjhvanderkolk ! You marked assignment 4 as complete but I don't have any request for feedback or a copy of the plan in my inbox that I can find. Could you please (re)send this? Thank you!

**Comment by rjhvanderkolk** [comment]
> Hi @rjhvanderkolk ! You marked assignment 4 as complete but I don't have any request for feedback or a copy of the plan in my inbox that I can find. Could you please (re)send this? Thank you!

I forgot to click ''request feedback'' , should now be clicked!

**Comment by EstherPlomp** [comment]
@rjhvanderkolk Fantastic: I received it now!
