### ISSUE TITLE
Overview issue Esther Spruit

### ISSUE THREAD

**Issue by EstherSpruit** [EstherPlomp/TNW-RDM-101#130]
### Introduction
Hello everyone, I'm also called Esther. About three months ago I started a PhD at the research group Applied Radiation & Isotopes. 
In my free time, I like to row. This year I am training for the Ringvaart Regatta, at which I will row 100 km in one day. For the rest, I also like to go running or mountain biking.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My PhD will be about the separation of alpha-emitting radionuclides with inorganic materials. Currently, organic materials are used for this, but those are damaged by the alpha-radiation, losing their functionality. I will investigate if inorganic materials, which are more resistant to this radiation damage, can be used for the separation.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | ?  |
| Work with large data (images, simulation models) | No  |
| Other:  | -  |
### Reflections on the importance of RDM videos

I was quite shocked about the example that researchers had included results from a patient multiple times to obtain a larger data set. 
I do agree that making your data available is important, but I question whether someone really has the time to go through all your data to find any mistakes, which seems a very cumbersome task to me. But maybe I should find a way to better organize my data, such that this is not the case. 
I also wonder about the part of using R or Phyton instead of Excel. In the past, I used both Phyton and Excel, but I think I would have made more mistakes by only using Phyton, because Excel does give a nice overview of the data while you are processing it, while with phyton this is not always as clear.

### What would you like to learn during this course? 

How to write a data management plan, which is mandatory for PhD students. 
During my master's end project, I experienced that data gathered from experiments can become very chaotic. I hope that this course can teach me how to set up a good naming convention/ documentation of what sample is what, facilitating the data processing.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://surfdrive.surf.nl/files/index.php/s/xk5IqlnxbJhnAS8): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://surfdrive.surf.nl/files/index.php/s/aHQKtDDjDEhKB5p): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://surfdrive.surf.nl/files/index.php/s/PeUvJFtXqVhcSqW): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @EstherSpruit! 

I had some discussions about physical sample management with some colleagues, but I'm not sure if we have any improvements for your workflow unfortunately... A summary of the discussion: 

-  Consider tracking of errors and needing to rename files (which I'm sure you're already very aware of, but this was brought up so including it for completeness :))
- Positions in boxes or in flowhood may also convey information (if it is really your flowhood and no one else is moving things!)
- Use 3 letter codes for everything so that you save space as you don't have to include - or _ to separate codes
- Having unique identifiers and then the detailed information elsewhere (which we discussed and was not ideal, but again, including it for completeness)

Sorry that I'm not of much more help here!

**Comment by EstherPlomp** [comment]
Hi @EstherSpruit! Thanks for handing in assignment 2: it looks super clear, well done!

- I like the flag for the XRD data only being available on the XRD-computer! (Although I get that this is annoying on your side :))
- Do you also have any protocols with information on sample processing? I miss a red flag on your challenge that we discussed after the first session, perhaps it can be included in this way? (Only a suggestion, you do not have to)
- Indeed, after the project has ended the data will need to be transferred from SURFdrive because the storage space will close when your contract ends - excellent point!

**Comment by EstherSpruit** [comment]
I have a question about the documentation of data, about the data dictionary.
In the theory it is mentioned that this should be a separate file, for me this sound impractical, as then you have to search for the matching files; one with the data and the corresponding data dictionary.
Is it also allowed to make a separate sheet in the same excel file with the data dictionary. In this way, their is a clear link between the data dictionary and to which file it corresponds.

I have another question about the file formats. I now use Word and Excel documents. These are not open, but they make my life easier compared to using unpaid (open) options. I am afraid that when I save the Word or Excel documents as the open file type that I will lose function. (For example for excel that formula's are not saved, but only the calculated value.)
Is it really bad to safe Word and Excel files? I believe that these programs are so comment, that most people will have access to it, even though it is not a open file type.

**Comment by EstherPlomp** [comment]
Good questions! 

It is definitely also allowed to have this incorporated into an existing file, especially if that is easier within your workflow! The only thing to keep in mind is when you export excel files to .csv files you will need to export each sheet in the file separately. 

Word/Excel files are indeed proprietary, but nowadays interoperable enough to also be opened with other software. You will indeed loose functionality when exporting it to open options (or end up with more files since you have to export sheets seperately as described above). I would recommend to only export it to the open file types whenever you upload it to a data repository, and only if that makes sense (if you have loads of files this can be too cumbersome, but if it is only a couple of excel files/sheets, it is doable). Then you can share a copy of the data in both Word/Excel and in an open file format, having the benefits of the usability as well as the benefits of the format more likely to be opened in the long term. For internal use I would not bother saving two copies in two different file types, that will be too messy to manage. 

I hope that makes sense!

**Comment by EstherPlomp** [comment]
And some minor feedback on your assignment 3 @EstherSpruit: it looks very clear and it looks like we already discussed most of your questions above! 

- You won't be able to change the metadata of some files, for example pictures taken. That is often not even desirable as some of this data is very helpful to maintain
- You can always update the accompanying metadata via the readme file or the information that you provide in the article (although after publication that becomes more effort to change!).  

I hope this makes sense? Let me know if that didn't address your question about changing metadata!

**Comment by RiteshDas2000** [comment]
Hi @EstherSpruit , nice to know your data is automatically backed up on surfdrive. I see you Word files for XRD data, would it perhaps be more convenient to use Excel or csv files instead?
I would also recommend storing the data on two cloud servers, one on-campus and one personal.

**Comment by RiteshDas2000** [comment]
From assignment 3, I see you favor jpg or TIFF files which are notoriously huge, or scale badly in quality and are most often not easily editable. Perhaps you may consider .svg or .eps files? Even .png would be a better alternative to .jpg.

**Comment by LonghengZhang** [comment]
Thanks for sharing your assignment 2! It is very elaborate!
