### ISSUE TITLE
Overview issue [Alvaro Bermejillo]

### ISSUE THREAD

**Issue by abermejillo** [EstherPlomp/TNW-RDM-101#131]
### Introduction

Hi! My name is Álvaro Bermejillo and I am a PhD candidate in the Quantum Nanoscience department in Applied Physics :) 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I investigate some of the smallest magnets that can ever exist, they are layers of down to only one atom thick! My goal is to study how magnetism in these materials interacts with vibrations to characterize their properties and learn how to make them functional. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I totally agree with the conclusions. Proper data management is not only important for the outside world and a basic principle in science. It also makes the life of any scientist so much easier. I've had my own horror stories trying to figure out the data of a colleague who is not around anymore. Where is it stored, how is it stored, how do I access it, how did he analyze it... Some things I never discovered.

### What would you like to learn during this course? 

Learn in what way to organize my data such that it is FAIR. I would like to get used to proper documentation and make my data accessible to others. 
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: 
https://tud365-my.sharepoint.com/:p:/g/personal/abermejillosec_tudelft_nl/EWi11Zm0iIBOsh7gFj40cyABkVhV49G88_Zdou7sbE8Szg?e=wubsU7
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  
https://tud365-my.sharepoint.com/:p:/g/personal/abermejillosec_tudelft_nl/EWi11Zm0iIBOsh7gFj40cyABkVhV49G88_Zdou7sbE8Szg?e=do22ll
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**) https://tud365-my.sharepoint.com/:f:/g/personal/abermejillosec_tudelft_nl/EtM5yb9e1iNLmrP4OfI75NgBvIlkGhaRfyGkg926l8NBsg?e=i7QxHa

**Comment by EstherPlomp** [comment]
Hi @abermejillo! I don't see a link or comment with your  [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html). Could you please still share this as soon as possible? Thank you!

**Comment by abermejillo** [comment]
Yes,  sorry @EstherPlomp. I had problems with my One Drive not updating. Thanks for the reminder.

**Comment by rjhvanderkolk** [comment]
looks nice Alvaro! Did you know Zenodo ? you can add your code there for publication, also code to make plots is often uploaded there (for instance as seen in https://scipost.org/submissions/2307.04830v1/        at ''code repository'' )

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 2 @abermejillo - no worries, stuff happens! It looks very clear and comprehensive, well done!

- Thanks for sharing Zenodo information @rjhvanderkolk! We'll dive a bit deeper into this in the FAIR data part of the course, as Zenodo is a public repository!
- Before sharing it publicly on Zenodo, you may also want to internally manage your code using a platform that uses version control, such as GitHub or GitLab. TU Delft has a GitLab instance: https://gitlab.tudelft.nl/. Both GitLab and GitHub can be used together with Zenodo (see here for more information: https://the-turing-way.netlify.app/communication/citable/citable-cite.html#citing-software

**Comment by irisforkink** [comment]
Nice and clear assignment 3. If I understand it correctly you will combine all your final data in one powerpoint, nice idea! Will you do this at the end of each experiment or will you maintain this during your work? And will you use a general structure for these powerpoints to make sure you don't miss anything?

**Comment by abermejillo** [comment]
@irisforkink I typically do it along the experiments! It's the PowerPoint I also use to show updates in meetings. I don't have a super defined structure but it's typically just a chronological story of the experiments.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @abermejillo! It looks super comprehensive and clear, well done! 

I therefore have very little feedback, other than the question why your data would fall under restricted access, as you are not indicating red flags for working with confidential data. Note that in order to defend you will need to make the data/code underlying the articles/chapters of your thesis available in line with the FAIR principles (see the [policy summary](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary)), unless there are good reasons not to do so. From your assignment I think your data/code could indeed be open! 

I see that you marked assignment 4 as complete, but I don't think I received a copy of your DMP or a feedback request - can you please still send this? Thank you!

**Comment by abermejillo** [comment]
Thanks for the feedback @EstherPlomp . I set it as restricted access because that is, I believe, the current practice in my field. You don't typically have access to other people's data straight away but you ask for it from the authors if you want to do something with it. I understand that that does not align with the FAIR principles, but I am not sure that is completely up to me. I will discuss it with my supervisor. Perhaps that is because this has been activated since 2019 and its taking some time until it is reflected in publications. 

I asked for feedback on my DMP so that you can see it. It was marked as private, sorry for that.

**Comment by EstherPlomp** [comment]
Sounds fair! (In a different manner than the FAIR principles ;)). 

And no worries: I received the feedback request, thank you!

**Comment by rjhvanderkolk** [comment]
assignment 3 looks nice! You could, possibly, add some of the proprietary for some of the AFM's perhaps.

**Comment by abermejillo** [comment]
what do you mean @rjhvanderkolk ?
