### ISSUE TITLE
Overview issue Martina Savic

### ISSUE THREAD

**Issue by mmsavic** [EstherPlomp/TNW-RDM-101#132]
### Introduction

Hi everyone! My name is Martina and I'm a PhD candidate in Mars Lab (ImPhys). I have plenty of hobbies, but my favorite ones are yoga, power walking and of course spending time with my friends. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research area is quantitative MRI, which entails collecting and quantifying information about different imaging parameters of tissues in the human body. As for the specific project, I'm looking into how magnetic field inhomogeneities induces by the difference in magnetic susceptibility affect the MR signal.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | Yes(-ish)  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I think that the video very concisely raises awareness of different issues that can arise if we don't manage our research data properly. While I haven't had a horror story happen to me, I think at this point with the way I'm managing my data (not very organized) losing my laptop would set me back at least a month.

### What would you like to learn during this course? 

I am excited about learning how to keep my data organized in general but what I want to learn the most is how to use Python and R to help me keep track of my research.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/NHBBhRr55ZGWMy4
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/NHBBhRr55ZGWMy4
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @mmsavic! We don't go in a lot of details on how use Python and R to keep track of your research, other than a folder structure template that you will find in the data organisation part of the course. 

We do have a list of [R and reproducible resources](https://github.com/Delft-RCafe/resources/blob/gh-pages/index.md#r-for-reproducible-research) and I have listed some Python resources in the PhD newsletter ([here](https://github.com/EstherPlomp/TNW-PhD-Newsletters/tree/main?tab=readme-ov-file#software), but then scroll down a bit until you reach the Python part!). Previous course participants were enthousiastic about using  [Sphinx ](https://www.sphinx-doc.org/en/master/) to improve documentation practices. Hopefully that will provide you a starting point!
-

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @mmsavic! It looks very clear, well done!

- I agree with @abermejillo that having a hard drive as a back up is not ideal because it is indeed not automatic and more prone to breakage. If you store data on the :H / personal drive it is backed up automatically, but if it is only stored locally on your computer it is not! Perhaps you can extend your storage in SURFdrive since you're already making use of this? That would work similarly as OneDrive suggested by @abermejillo.
- Do you need access to these consent forms? If not, it is more ideal to not have access to them. It is already safely stored at the hospital so it is not a big concern, but any minimising of personal data handling would be best. 
- Others have also included things such as literature/presentations in their data flow map. You don't have to add these, but do consider where you store these files as well of course!
-

**Comment by abermejillo** [comment]
Hi @mmsavic, nice flow map. It seems like your data management is pretty much defined in the group as a whole and it's figured out. I don't know how it works for you but in my case, we often show data to other people, let's say a theorist, to discuss. In your case, since the data is related to patients, so you need to be careful about how and with whom you share it. Is this defined anywhere?

**Comment by mmsavic** [comment]
Hi @abermejillo , thanks for the insight and great question! Volunteer data (that is images) from the hospital are completely anonimyzed, without any personal data that could indicate who the scan originates from. This is why it is not an issue.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @mmsavic! It looks very clear, well done!

- Do you know what ELN you will be using? Did you [try out one of the TU Delft ones](https://estherplomp.github.io/TNW-RDM-101/09-Realising-FAIR-Documentation.html#assignment-electronic-lab-notebooks-optional)?
- For your project's data it may indeed not be possible to share the data - especially if the MRI images are also from the hospital? You could double check this with your supervisor what the agreements are. Ideally data is open where possible, but if this has not been asked in the consent forms or if you're working with other people's equipment it may not be possible to share all the results publicly (/ it may not be yours to share publicly but the hospital's rights, and/or Philips?). 
- If you indeed cannot share the data/code, it would be good to include clear information on how to contact your supervisor in the data availability statement of the article. See here for some examples: https://the-turing-way.netlify.app/communication/citable/citable-cite.html#data-availability-statement-examples

**Comment by EstherPlomp** [comment]
Hi @mmsavic! You marked assignment 4 as complete but I don't have any request for feedback or a copy of the plan in my inbox that I can find. Could you please (re)send this? Thank you!

**Comment by RiteshDas2000** [comment]
Hi @mmsavic . Regarding assignment 2. You have a clear plan for the storage and backup. I was wondering if the external hard drive is easy to read and useful to access files on the fly? Since the size of data is very low, does it make sense to use an external hard drive as backup instead of using another drive, e.g. google drive linked to your personal ID? Or better, both.

Also, you mention you use .jpeg or .fig files. These are notoriously bad in quality unless huge in size, and often not as editable. Perhaps you may consider using .svg or .eps files?

**Comment by RiteshDas2000** [comment]
From Assignment 3, I see you use Latex often. Perhaps you can consider overleaf as a platform to edit LaTeX documents. This will allow you to store them on a secure cloud and provide easy access to collaborators.
