### ISSUE TITLE
Assignment 1 Dimitri van der Lee

### ISSUE THREAD

**Issue by demiteach** [EstherPlomp/TNW-RDM-101#133]
### Introduction

Hi everyone, I am Dimitri, and I am a PhD candidate in the department of biotechnology, working on microbial electrosynthesis. Pleased to meet you all!
### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

The goal of my research is to overcome the limitations that are currently preventing microbial electrosynthesis to be scaled up. 
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

In my opinion, data is often very easy to get lost in. It is so easy to collect a lot of data, but then be unable to get order in it. For this reason, I believe it would be very helpful to already have a plan on how to handle your data and its analysis, before you even start collecting this data.
### What would you like to learn during this course? 

During this course, I would like to get a standard in how I manage my data in a safe way, which couses me and everyone around me to be able to easily find and access my data. 
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/dimitrivanderl_tudelft_nl/ETDprba7as5PrgAoC22REFABwCcuR0M4Uw6HqLWsQt6Fng?e=GKiAXp
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/dimitrivanderl_tudelft_nl/EUEqSY5LvWpPln4uvK0TaoIBKJZy8HoxnI9Q_QOqE3_uvQ?e=QReyhZ
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [ ] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by BhaveshSChavan** [comment]
Nice DFM and overview. I am a bit doubtful on whether a master copy should be on personal laptop.

**Comment by demiteach** [comment]
Thank you for your feedback. Yes, that was a matter of concern for me as well. however, I am doubtfull where I could store my master data copy while still using onedrive. (you got any ideas?) The data will always be on onedrive and/or the U:drive, so there will alsways be a backup available.

**Comment by linghangdelft** [comment]
It's a good data flow map. I am curious whether your onedrive is based on TU Delft account or not? Are your csv files containing experimental data always edited on onedrive?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @demiteach! It looks very clear, well done!

- I agree with your concerns @BhaveshSChavan! Only having the files locally stored is not ideal. Good to see you already addressed these concerns @demiteach! Indeed, using both OneDrive on your computer locally already solves this because then your files are not just stored locally but also in the cloud. Having another back up available on the U: drive is then the safest way to go!
- @linghangdelft - OneDrive should be provided by TU Delft indeed! 
- I like how you included your manuscripts as data as well! Others have also included things such as presentations/literature. You don't have to include those in the assignment, as long as they are also backed up of course :)

**Comment by irisforkink** [comment]
Nice overview :). How do you back-up your OneDrive? Do you do this manually every week?

**Comment by linghangdelft** [comment]
Good assignment 3, I think you have thought about most of the aspects of FAIR principle. Do you consider using version tools like Git for your data mangement?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @demiteach! Looks very clear - so I have very little feedback from my side!

 - If you want to try out Jupyter notebooks, these lesson materials might be of interest: https://coderefinery.github.io/jupyter/. Previous participants were also enthusiastic about Sphinx for documentation: https://www.sphinx-doc.org/en/master/
 -   Indeed, always discuss with supervisor(s) and collaborator(s) what data is shared, and where!

**Comment by LonghengZhang** [comment]
Thanks for sharing! Very nice and clear!
