### ISSUE TITLE
Overview issue [Ritesh Das]

### ISSUE THREAD

**Issue by RiteshDas2000** [EstherPlomp/TNW-RDM-101#134]
### Introduction
<I am Ritesh Das. I am a doctoral candidate at the quantum nanoscience department at TNW. I am a theoretical physicist working on spin waves in antiferromagnets. I am from India.>

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
<My research involves looking at excitations in magnetic materials, known as magnons or spin waves, and their propagation under the presence of different external factors. I also examine their coupling with other degrees of freedom like optical or elastic excitations.>

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Potentially  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
<The most eye-opening statement was that 9 laptops were stolen from this faculty, which makes me consider the very real threat of having my laptop stolen. I have already been made aware of the importance of reproducibility through a particularly tough review process. My horror story has less to do with the storage of the data but rather the management of the code written. The code was written in a way that made sense to very few people and, at times, didn't make sense to me either. This made it extremely difficult for a particularly thorough reviewer to reproduce my results.>

### What would you like to learn during this course? 
<The most efficient way to store data. Updating code/manuscripts while keeping old iterations available and making changes that are easily reversible.>

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://docs.google.com/presentation/d/1F_fsv21M3p7dZsH62aqzsPL33ZBzRS4q/edit?usp=sharing&ouid=114654806524082640610&rtpof=true&sd=true
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://docs.google.com/presentation/d/1MyWtT7Qj3_-1r0qylqUAyWw9vSucpgfb/edit?usp=sharing&ouid=114654806524082640610&rtpof=true&sd=true
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**): https://docs.google.com/document/d/1FTyTCv0MUkX0btDJ4q8UQodk-s1IwBnS/edit?usp=sharing&ouid=114654806524082640610&rtpof=true&sd=true
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**):https://docs.google.com/presentation/d/1iUHHrubYbVmnw9ljbikft-CsnrkwSFl-iRTP6r2PGI4/edit?usp=sharing

**Comment by EstherPlomp** [comment]
For keeping track of changes in your code I can recommend version control! We do not discuss that in detail in this course, but sometimes TU Delft organises a [workshop on version control](https://www.tudelft.nl/en/library/research-data-management/r/training-events/training-for-researchers/version-control-collaborative-development-for-research-software). You can also check out the Carpentries workshop materials on version control: https://swcarpentry.github.io/git-novice/
Or the Turing Way on version control: https://the-turing-way.netlify.app/reproducible-research/vcs.html

For manuscripts tools such as OneDrive / Google Drive may be more userfriendly, especially if you have to collaborate with multiple people! 

We do go into how/where to store your data - hopefully assignment 2 is providing some helpful pointers for that!

**Comment by EstherPlomp** [comment]
Hi @RiteshDas2000! I see you marked Assignment 2 as complete but I don't see a link yet. Can you please still share the assignment as soon as possible! Thank you!

**Comment by RiteshDas2000** [comment]
Hi Esther! Sorry I forgot to add the link, added now.

**Comment by kmertiri** [comment]
Hi Ritesh! For manuscripts, and sometimes notes, I use Overleaf. The university also provides access to the premium version so that you can collaborate with others.

**Comment by EstherPlomp** [comment]
Thanks for still sharing your assignment 2 @RiteshDas2000! 

- I don't think your assignment is complete? I don't see your answers to the questions on where the data is stored?
- For the experimental data: what formats is the data in? Since you'll receive this data from collaborators, will you have all the information you need to work with the data? Are there any restrictions on sharing the eventual results of your research?
- Since you're working with code you can also consider using a platform that implements version control to manage the code, such as GitHub and GitLab. TU Delft has a Gitlab instance: https://gitlab.tudelft.nl/users/sign_in
- I agree with @kmertiri that Overleaf is a nice solution to collaboratively work on manuscripts with others! Thanks for sharing @kmertiri!

**Comment by RiteshDas2000** [comment]
Hey @EstherPlomp ,

I seem to have uploaded the incorrect file before. I have added the answers to the ppt in the link now. I have also added answers to the questions related to the experimental data. @kmertiri, thanks for the advice. I already use Overleaf, but I did not know the university has access to premium, I shall be making use of that. Thanks.

Ritesh

**Comment by EstherPlomp** [comment]
Thanks @RiteshDas2000, also for the update! 

- Do make sure your collaborators are alright with their data being stored on Google drive. You do automatically give Google permission/rights to data stored on these storage solutions. If everyone is happy with this, there is no harm for 'regular' research data being stored there. 
-  With making weekly backups to your personal computer, do you mean that OneDrive is syncing your files? Sounds like a solid strategy!
- Fantastic to see that you're already using version control/GitHub!

**Comment by mmsavic** [comment]
Hi Ritesh!

Very nice presentation! I'm curious about one thing, which is sharing data through Microsoft Teams during the project. Is it easy to keep track of who you sent what to, and in which situations would you choose that over google drive/some other online cloud?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @RiteshDas2000! It looks very clear, well done!
 
- I would recommend to add the date to the filename in the following format: YYYYMMDD, that is easier to follow consistently and you can then also organise your files/scripts chronologically. (see also the [folder structure thread for feedback](https://github.com/EstherPlomp/TNW-RDM-101/discussions/127#discussioncomment-9548897))
- Like you already mention, it may not always make sense to convert proprietary formats to open formats - if Mathematica is a commonly used language within your field it is not an issue to remain using that language where you need it. 
- You mention both ArXiv and GitHub to share your research: it would make more sense to make the code available via GitHub and then also share a snapshot of your repository on Zenodo or 4TU.ResearchData so that there is a version preserved for the long term and that you have a DOI associated with the code!

**Comment by EstherPlomp** [comment]
Hi @RiteshDas2000: don't forget to submit [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html)! The deadline was earlier today!

**Comment by RiteshDas2000** [comment]
Thanks for the reminder! Done now.

**Comment by RiteshDas2000** [comment]
Regarding assignment 5. Since I am not present in person. I have added what I planned to say in the speaker's notes.

**Comment by EstherPlomp** [comment]
@RiteshDas2000 thanks for sharing assignments 4 and 5! 

I hope you get the tabs under control ;)

**Comment by EstherPlomp** [comment]
@RiteshDas2000 - the only thing I'm missing from your side is your data challenge in the [discussion thread on data challenges](https://github.com/EstherPlomp/TNW-RDM-101/discussions/125) / #125. If you could add yours there, you're all set!

**Comment by kmertiri** [comment]
Hi Ritesh, nice work on Assignment 3! I like the folder structure.

**Comment by EstherPlomp** [comment]
@RiteshDas2000 - I can't provide comments directly in the google doc of your data management plan, so I'll share it here instead: 

I think the only thing you'll still need to look at is which data repository you'll use to preserve a snapshot of the code repository on GitHub for the long term. Both [Zenodo](https://zenodo.org/) and [4TU.ResearchData](https://data.4tu.nl/) are suitable for this. Zenodo has a nice integration with GitHub: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content.

**Comment by abermejillo** [comment]
Hi @RiteshDas2000 ! We went through your slides and everything seems very reasonable. For the tab issue you can also get an extra screen and then things are easier to find. If you keep up with your promises you'll do fine.
Signed, GROUP 2
