### ISSUE TITLE
Overview issue Klaiv

### ISSUE THREAD

**Issue by kmertiri** [EstherPlomp/TNW-RDM-101#135]
### Introduction

Hi, my name is Klaiv and I am a Phd student in Quantum Nanoscience.
### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on quantum effects in the transport of electrons in different materials. These materials include metal conductors, superconductors etc. 
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | No  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

RDM is really important in my field, despite our theoretical focus and lack of big datasets. Storing your work and results correctly not only helps with avoiding mistakes, but also makes your work transparent to others. Storing it in the cloud also helps with unforeseen events such as theft or fire. 
### What would you like to learn during this course? 

I would like to learn more about Github.
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/kmertiri_tudelft_nl/EWZbtNZL6cRKlmCs2sYreUcBWkG4LjSCDcFx-h06lRtVCA?e=usZDos
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/kmertiri_tudelft_nl/ETrDVFHtd-9BppTscrrMmU8BbBFY_XsVQkdXMDiKfe0pcQ?e=zPQzZa
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Other than using the GitHub platform we don't delve into the details of using it to manage your code - hopefully the [additional resources from assignment 1](https://estherplomp.github.io/TNW-RDM-101/03-Assignment-GitHub-1.html#more-github-tutorials) provide some pointers there. You can also experiment around with this repository :)

**Comment by EstherPlomp** [comment]
Hi @kmertiri! Thanks for handing in assignment 2! It looks very clear! I do have some concerns about your current storage strategy: 

- I see that in this issue you marked that you're not handling personal data, but in your data flow map I see that you process videos from interviews. Videos from interview with people are personal data - so please also make sure you follow the [procedures set out by our Human Research Ethics Committee](https://www.tudelft.nl/en/strategy/integrity-policy/human-research-ethics/hrec-approval-1-application) before you start with these interviews. And indeed: restricting access to this data is crucial in managing it properly! These videos should not be stored on Google Drive, and instead be stored on TU Delft managed solutions (such as your laptop, network drives, SURF/OneDrive)!
- Ideally, video recordings are transcribed, so that only the text of the video is available. This is a separate dataset as this type of data can be de-identified and when it is de-identified it is no longer personal data (next to it being available in a different file format).
- Instead of using google drive for storage of code, I would recommend GitHub or GitLab. [TU Delft has a GitLab instance](https://gitlab.tudelft.nl/) where members of your lab can all access the code and it will be version controlled. Google Drive also has version control but GitLab/Hub is specialised for code so it will be easier to work with!
- Pending where you store the data on your PC it may not be backed up. the H drive is backed up, the local storage on your laptop itself is not! So do be careful if it is only stored locally on your PC.

**Comment by kmertiri** [comment]
Hi @EstherPlomp! The 'interview videos' object was part of the example that came with the assignment and I forgot to remove it. I am sorry for the confusion. Thank you for your comments, they are very helpful!

**Comment by EstherPlomp** [comment]
That makes more sense! No worries, and I'm glad the comments are of use!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @kmertiri! It looks very clear, well done!

I therefore only have some pointers: 
- It may be helpful to have a look at the Coderefinery lessons on [code documentation](https://coderefinery.github.io/documentation/) and [Jupyter Notebooks](https://coderefinery.github.io/jupyter/). Previous course participants were enthusiastic about [Sphinx](https://www.sphinx-doc.org/en/master/) for documentation.
- Don't forget to have another think about your license preference! (See [the license thread](https://www.sphinx-doc.org/en/master/))
