### ISSUE TITLE
Overview issue [Leanid_Kresik]

### ISSUE THREAD

**Issue by lkresik** [EstherPlomp/TNW-RDM-101#136]
### Introduction

Hi everyone :) My name is Leanid and I'm a PhD candidate in Dimphna Meijer's group at the Bionanoscience department. 
 
### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I am interested in the underlying molecular mechanisms of neuronal network formation, specifically in synapse assembly. To investigate it, I am developing a simplified cellular model to study the trans-cellular interaction of key synaptic cell adhesion molecules. Such a model has the potential to help overcome the challenges faced when using more complex neuronal cells and synapses for such studies. In my research, I use a combination of focused-ion-beam milling and cryo-electron tomography.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

The video showed some examples of how poor data management can ruin the scientific experience, and I find it extremely important to develop the habit of keeping data "tidy".  I had a few very stressful situations of that kind in the past. One took place relatively recently, I was asked by my former supervisor to modify some figures and include more data in a paper based on research that had been done before I joined my current research group at TUDelft. It was a difficult task to gather all the data since it was scattered across various email accounts and drives, some of which I no longer had access to.

### What would you like to learn during this course? 

I want to learn new tools and ways to store the data and not get lost in it. I usually run a lot of different experiments that are connected and require good tracking of samples and high volumes of data. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/tItKqDtAPWldnMa
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [X] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/UV3eLPRsvmfq6mi
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/jXwbVxMF62X7VdG
- [ ] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @lkresik! I don't see a link or comment with your  [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html). Could you please still share this as soon as possible? Thank you!

**Comment by lkresik** [comment]
Hello @EstherPlomp. I am sorry about that. Unfortunately, I got overloaded with my project stuff and had a feeling that the deadline was later than it was. I will do it as soon as possible. 

Thank you for understanding.

**Comment by lkresik** [comment]
Hi @EstherPlomp. You can find the link to my SURFdrive folder attached to the issue.

**Comment by EstherPlomp** [comment]
Fantastic @lkresik, thank you very much! 

Hope you can take some rest over the long weekend to recover from the overload!

**Comment by EstherPlomp** [comment]
And hereby the feedback from my side! 

- Your flowmap looks very comprehensive and detailed: well done! I have very little feedback due to this :) 
- I like the reproducibility flag: is this because it is difficult to take the same image or set up the same model again? Or are there further concerns here?
- With the amount of data you'll produce you probably only have the choice of the TU Delft network drives indeed.. Staff/Group drive is great for this, as long as it is fine that others may also have access to your data. If it becomes more important to restrict access to data it could be that :U / Project drive is a more suitable solution!

**Comment by lkresik** [comment]
> And hereby the feedback from my side! 
> 
> 
> 
> - Your flowmap looks very comprehensive and detailed: well done! I have very little feedback due to this :) 
> 
> - I like the reproducibility flag: is this because it is difficult to take the same image or set up the same model again? Or are there further concerns here?
> 
> - With the amount of data you'll produce you probably only have the choice of the TU Delft network drives indeed.. Staff/Group drive is great for this, as long as it is fine that others may also have access to your data. If it becomes more important to restrict access to data it could be that :U / Project drive is a more suitable solution! 

Hi Esther!
Thank you for your feedback. 

The reproducibility flag in my case means to make sure all the conditions/parameters/steps are noted in case exactly same experiment should be reproduced.

**Comment by EstherPlomp** [comment]
Thanks for clarifying @lkresik! Great flag indeed - that can be a hassle 👍

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment @lkresik! It looks very clear and comprehensive, well done!

I therefore only have a couple of thoughts:
- Nice overview of your data organisation! I see a small inconsistency in your file naming, where in your example you don't put dashes in the date and in the folder structure you do (so 2404204 vs 2024-03-27). Additionally, if you add the date in front of the file name you may be able to organise your files chronologically as well
- Lovely to see that most of your metadata is collected automatically! Thanks for sharing the example!
- From your answers to slide 5 it is not entirely clear which file formats are proprietary or not. It is indeed fair to use commonly used file formats within the discipline - it may then not make a lot of sense to convert these to open file formats (which are more beneficial for long term preservation). 
- Fantastic to see that you can use disciplinary specific repositories! PDB and EMDB are great solutions!

**Comment by lkresik** [comment]
> Thanks for sharing assignment @lkresik! It looks very clear and comprehensive, well done!
> 
> I therefore only have a couple of thoughts:
> 
> * Nice overview of your data organisation! I see a small inconsistency in your file naming, where in your example you don't put dashes in the date and in the folder structure you do (so 2404204 vs 2024-03-27). Additionally, if you add the date in front of the file name you may be able to organise your files chronologically as well
> * Lovely to see that most of your metadata is collected automatically! Thanks for sharing the example!
> * From your answers to slide 5 it is not entirely clear which file formats are proprietary or not. It is indeed fair to use commonly used file formats within the discipline - it may then not make a lot of sense to convert these to open file formats (which are more beneficial for long term preservation).
> * Fantastic to see that you can use disciplinary specific repositories! PDB and EMDB are great solutions!

Thank you Esther. 

I will keep an eye on a consistency in the namings. And thank you for the tips and feedback!

**Comment by RiteshDas2000** [comment]
Hi @lkresik , you have a nice plan for storage and backup. I have a few comments to offer (Assignment 2):
1. You mention physical hard drives. Are these harddrives connected to a PC at all times, or are they external drives that can be connected quickly? If not, it may be complicated to access data on them on the fly.
2. I see you use excel files. Is it easy to incorporate them into code written in, say, Python without going through some intermediate file format like csv? If you go through csv, then perhaps you might also considering saving the csv files.
3. You extensively use the TUDelft storage drive, which is very useful, however, you might wanna save the most important files in say Github or a personal drive that you can access when you are no longer at the TU.
4. .png files are notorious for losing quality and their non-editable nature. Perhaps something like eps or SVG makes more sense?

**Comment by RiteshDas2000** [comment]
I have some more comments on assignment 3:
1. Data organization:  Your folders have a lot of abbreviations. Perhaps they make sense to you, but when you upload the data to a public repository, some people might find it difficult to tell what is what.
2. Documentation: Like Esther mentioned, it is nice that the metadata is collected automatically.
3. Metadata: No comments other than above.
4. File formats: It is great that the file formats are standard and easily accessible by others in your field. I was wondering if files such as .mdoc can be opened in the browser itself or something simpler like notepad? As they look simple enough. That would save people the trouble of downloading huge files without knowing whats in them.
5. Access: If you collaborate, perhaps you can consider overleaf for manuscripts with multiple co-authors.

**Comment by lkresik** [comment]
> Hi @lkresik , you have a nice plan for storage and backup. I have a few comments to offer (Assignment 2):
> 
> 1. You mention physical hard drives. Are these harddrives connected to a PC at all times, or are they external drives that can be connected quickly? If not, it may be complicated to access data on them on the fly.
> 2. I see you use excel files. Is it easy to incorporate them into code written in, say, Python without going through some intermediate file format like csv? If you go through csv, then perhaps you might also considering saving the csv files.
> 3. You extensively use the TUDelft storage drive, which is very useful, however, you might wanna save the most important files in say Github or a personal drive that you can access when you are no longer at the TU.
> 4. .png files are notorious for losing quality and their non-editable nature. Perhaps something like eps or SVG makes more sense?

Hi Ritesh,


1. I am using external LaCie hard drives that can be easily transferred and connected to other machines. That is the main point of having them, for me) 
2.

**Comment by oonimabisht** [comment]
Hi @lkresik . Your plan seem very comprehensive. I have a few comments.
1. It is nice to see reproducibility as a flag. 
2. I see a lot of techniques that you are using to produce results. Do you also use codes to process them. If it is so, maybe you can add a box for that as well and a description about that.
3.
