### ISSUE TITLE
Overview issue Iris Forkink

### ISSUE THREAD

**Issue by irisforkink** [EstherPlomp/TNW-RDM-101#137]
### Introduction

Hi everyone, I am Iris. I'm doing my PhD at the Applied Sciences Faculty, in the Biotechnology Department. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is about genetic engineering of yeast. My goal is to improve it's ability to grow without the presence of oxygen. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

While watching the video I realized that I should ensure that my data is available from different devices. I personally think that the chances of such a horror story are small but if it happens the consequences are big. After this course I hope that I have found a way to improve my data management. 

### What would you like to learn during this course? 

I want to find a way to clearly and correctly store my data. And to do this in such an easy way that it doesn't take me too much time/effort as I think that this will help me to keep doing it during my PhD.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/irisforkink_tudelft_nl/EU1-s4NiOWxPpX6Y4yYH8EQBSaj5QjJZDCk50ce29h_uxg?e=aJZwC0
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/irisforkink_tudelft_nl/Ecgalf4L8kFNnXQLjFOLxCABDEl0EF_qUKWWBCJZPyj1lQ?e=wsvcdJ
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by BhaveshSChavan** [comment]
Nice Data flow map. However, I am not sure how you can backup the lab journals notes?

**Comment by demiteach** [comment]
Hi Iris, 

Your DFM looks good, it is very clear that your data is very secretive (I guess because of stakes from companies). 
You might want to consider storing your data in a U:drive as well. That way, your supervisor can access it after you are gone. 

Regarding your lab journal, I guess you can easily resolve this issue by making a digital version as soon as possible. Especially methods you used and data sheets, as these are the most fragile and can result in months of extra work if lost.

**Comment by linghangdelft** [comment]
Good DFM. I am also thinking about how to store genomic sequencing data properly. For the 3rd question, I think you can ask for space in U drive (Project data) and use that as an additional backup to Staff-Groups folder

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @irisforkink: it looks very clear, well done!

- I share @BhaveshSChavan's question on the back up of lab journal notes: are these stored digitally somewhere as well to ensure that you don't loose information if your notebook is gone?
- I agree with @demiteach that the U: / project drive may be a better solution for you to share the data with your supervisor. This drive allows you to determine who has access to the drive, unlike the staff/group drive where anyone of your research group could have access to the data! If you want to copy from SURFdrive to these drives I'm afraid you'll have to do that manually, so consider a workflow where you'll do this in a manner that you don't forget.
- Thanks also for your feedback @linghangdelft! I would select either the group/staff folder or the project folder to avoid having too many versions of the data stored everywhere. That could also end up in some confusion. All these storage solutions are hosted by TU Delft, so in case of catastrophe both of these solutions use the same software/hardware (at TU Delft and back up in Leiden). Data stored on OneDrive/SURFdrive is stored in other locations, so this could then be another way to back up the data.  
- To manage the code you're working with you can also consider using GitLab. TU Delft hosts an instance of GitLab which is safe for confidential code: https://gitlab.tudelft.nl

Thanks all for the feedback! @irisforkink don't forget to provide feedback on an assignment of a peer as well :)

**Comment by lkresik** [comment]
Hi Iris, 
Great data management plan! We come from a similar field where there is less code but more wet lab data :)
For the e-lab book, I can suggest eLabjournal, it works well. It also allows you to make a customisable sample inventory where you can link the storage and samples with your experiments, which may be useful if you have plenty of DNA samples to work with.

As a backup solution from Q3, I agree with others about U: / project drive, you can also consider physical hard drives.

**Comment by DimitrivanderLee** [comment]
Hi Iris, 

I have a few comments based on your assignment 3:
- In order to link your excell data with the FASTA files, you may consider copying a figure of your plasmid layout and past it into excel (figures are supported in excell). you could write the respective name of the FASTA file in order to make clear where the figure came from, and where you can find more information
- As far as I know, SnapGene is actually a paid platform, and Benchling is usually free. However, Benchling is still an online platform, so you should first read the terms of use on what thay can do with your code. SnapGene is a completely offline tool, as far as I know. 
- Personally, I thought that a 'proprietary format' means that it is in a file format that can only be opened and read by paid software, which means it cannot be openly shared. 
- For data that is not used for publications or comparable: you should still store them in your U:drive. You will have records of the experiments you did to obtain them in your lab book, so someone might want to work on it later on. At the end of your project, you may want to make a separate folder for such data, so people can easily find it. 
- At the final slide, you give no information about how you will publish the metadata about restricted access data. However, you do mention that your data will be restricted access. So I think you should give this some thought.

**Comment by EstherPlomp** [comment]
Hey @irisforkink! Thanks for sharing Assignment 3! 

- Well done on the data/folder organisation! It looks even more organised than your previous folder structure! I hope this is a workable solution for you!
- You could indeed try out eLabJournal as @lkresik is mentioning - we do have [TU Delft licenses](https://www.tudelft.nl/en/library/research-data-management/r/manage/electronic-lab-notebook) for this so it will be safe to use for the confidential data. So indeed be careful with using other tools such as Benchling highlighted by @demiteach (thank you for your great feedback @demiteach!) These electronic lab note books would allow you to link all your files/experiments/results!
- What is meant with a metadata standard is a standard way of structuring data across a discipline. So if you want to set that up yourself that could actually require setting up a big research project in order to manage this, because that will require involvement and input from the entire research field to get that done. It is not an easy process, which is why many fields still don't have these metadata standards. So no worries if you could not find relevant standards, as long as you document your data appropriately it should not be an issue! Pending on which NCBI database you're using, they may also use metadata standards, so that is already a great step towards this direction.
- Word/Excel are actually also proprietary files - which means that you can indeed still share them but it is not fully open as @demiteach is mentioning. Nowadays these files are also openable using other software, so they are at least interoperable. To convert these files to open file formats you could use .txt, .pdf or .csv. This conversion may result in some formatting losses - so it is not always worthwhile to do this. Open formats are preferred by data repositories because it allows them to guarantee access to files for a longer time period compared to proprietary formats.
- Sharing data in supplementary files is not in line with the FAIR principles, as these do not get their own persistent identifier assigned. So these supplementary files could be shared openly in 4TU.ResearchData it seems! You can also share restricted access datasets on 4TU.ResearchData, so that people can use the data repository to request access to the data. Like @demiteach already said: here it requires some thought about what information you'll provide people publicly to ensure that the data is still discoverable. 

I hope this makes sense! Please do let me know if not :)

**Comment by BhaveshSChavan** [comment]
Nice, @irisforkink, I can imagine a lot of similarities between yours and my DFM! Well done.
