### ISSUE TITLE
Overview issue [Linghang]

### ISSUE THREAD

**Issue by linghangdelft** [EstherPlomp/TNW-RDM-101#138]
### Introduction
My name is Linghang and I'm from the Department of Biotechnology. I like music and sports in my spare time.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research focuses on engineering microorganisms to purify wastewater. More specifically, I am researching an innovative biotechnology developed in TU Delft, and trying to optimize the process control to achieve better wastewater treatment.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  |Yes|
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
The examples of losing data given in the video are really scary, but they are possible to happen in our lives. These examples make me realize the importance of RDM skill better. Luckily, I don't have a horror story in my past research. But I did find it difficult to find the pictures I needed when I was writing, which can be solved with better RDM skill.

### What would you like to learn during this course? 
An organized way to back up and synchronize data. More specifically, a better way to organize different types of data (excel, word, pictures).

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/Va1VwmGf9tlCLEi
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/voW8kmngffmsTcl
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by linghangdelft** [comment]
My assignment 2 link: https://surfdrive.surf.nl/files/index.php/s/Va1VwmGf9tlCLEi

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @linghangdelft! It looks very clear and comprehensive, well done! 

I have two questions: 
- Do you also have a back up of your written lab notes? 
- In Q3 you mention that you'll back up the project drive on a monthly basis - where is this back up stored?  
- Other people have also included things such as literature or presentations in their assignment - you don't have to do that of course, but a back up of these files can also be crucial!

**Comment by irisforkink** [comment]
Nice overview! Just like you I also have lab notes, do you already know how you want to back them up? Our group is going to start with an electronic labjournal (pilot starts in September), maybe this could also benefit your project?

And do you already know how you are going to store your pictures so that they are easily accessible? Do you have a way in which you want to name them clearly?

**Comment by linghangdelft** [comment]
> Nice overview! Just like you I also have lab notes, do you already know how you want to back them up? Our group is going to start with an electronic labjournal (pilot starts in September), maybe this could also benefit your project?
> 
> And do you already know how you are going to store your pictures so that they are easily accessible? Do you have a way in which you want to name them clearly?

Hi Iris, thanks for sharing your comment. All the questions you mentioned are very relevant. For backup of lab journals, it is indeed difficult, but your mentioning about electronic lab journal sounds very useful. For storing pictures, I will keep them in the shared drive, but I have no idea about how to manage them better and this is the important challenge I am interested in solving.

**Comment by linghangdelft** [comment]
> Thanks for sharing assignment 2 @linghangdelft! It looks very clear and comprehensive, well done!
> 
> I have two questions:
> 
> * Do you also have a back up of your written lab notes?
> * In Q3 you mention that you'll back up the project drive on a monthly basis - where is this back up stored?
> * Other people have also included things such as literature or presentations in their assignment - you don't have to do that of course, but a back up of these files can also be crucial!

Thanks for bringing these questions to discuss. Backup of written notes is indeed an issue I don't have clear idea about. But I have tried to convert those important data and notes to my Excel, which will help a bit. For backup of project data, maybe another drive like SURF drive will help. Literature and presentation are indeed important, I will store them together with my lab data in the project drive.

**Comment by EstherPlomp** [comment]
Hi @linghangdelft ! I don't see a link or comment with your [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html). Did something go wrong in updating the issue? Could you please still share this as soon as possible? Thank you!

**Comment by linghangdelft** [comment]
> Hi @linghangdelft ! I don't see a link or comment with your [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html). Did something go wrong in updating the issue? Could you please still share this as soon as possible? Thank you!

Hi Esther, sorry, I was busy recently so I didn't manage to finish it. I will try my best to finish the assignment these two days

**Comment by EstherPlomp** [comment]
Thanks for sharing @linghangdelft! I'll get back with feedback on Monday! 

In the meantime I might suggest using SURFdrive/OneDrive as your active storage location and from there maintaining a backup to the project drive - SURF/OneDrive are a bit more userfriendly and you can work on files offline as well, which is more complicated with the project drive. It is up to you of course!

**Comment by EstherPlomp** [comment]
And as promised, some feedback on assignment 3 @linghangdelft! It looks very clear and comprehensive, well done! 

I therefore have little feedback, mostly the question on why you consider your data to be suitable for restricted access? It looks like you're not working with any confidential data so that would mean that any results could be made openly available.  Note that this is one of the [requirements before you defend your thesis](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary): to make the code/data underlying the publications and thesis chapters available according to the FAIR principles!

**Comment by linghangdelft** [comment]
> And as promised, some feedback on assignment 3 @linghangdelft! It looks very clear and comprehensive, well done!
> 
> I therefore have little feedback, mostly the question on why you consider your data to be suitable for restricted access? It looks like you're not working with any confidential data so that would mean that any results could be made openly available. Note that this is one of the [requirements before you defend your thesis](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary): to make the code/data underlying the publications and thesis chapters available according to the FAIR principles!

Thanks for checking. I think it's probably because in my field, the data included in published papers is not much different from the original data, but in a more organized way. Therefore, showing the complete data doesn't give more information but might cause more confusion. 
Usually, the data amount in my field is small but with a lot of context, so making every detail open is not very helpful but can cost much more time if the data need to be very clear. A common way in our field would be adding an appendix to include extra data, if someone really wants some specific detailed data they can contact the author. 
But after taking this course, I will think about how to make my data more open.

**Comment by BhaveshSChavan** [comment]
Thanks for sharing the assignment, @linghangdelft ! Very clear!
