### ISSUE TITLE
Onima Bisht

### ISSUE THREAD

**Issue by oonimabisht** [EstherPlomp/TNW-RDM-101#139]
### Introduction
Hi, I am Onima Bisht from India, PhD in Quantum Nanoscience. I love cooking, and doing yoga. Apart from that, I am learning how to crochet. I have joined TU about 8 months ago and I am really enjoying my life and work here.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research deals with the investigation of light-matter interaction with nanoscale. Light matter interaction has been extensively studied at a macroscale. However, it still needs a lot of research at the nano-scale and this is what we are doing. My research particularly deals with studied the near-field using our home built near field optical microscope. Using the microscope, we can study a lot that is happening at the nanoscale. I am spending my time researching on how light interacts with hypergratings (a combination of hyperbolic metamaterials and Fresnel gratings ) and analyzing the structure of light near these materials

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  | 
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |  
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | No |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
I never thought of my laptop being lost or my office set into fire, but since that has happened (which I was unaware of) , it could happen to anyone. I think being more careful is the only way to prevent such disasters.

### What would you like to learn during this course? 
I want to learn how I can manage my data efficiently using Github. I am very new to this and want to learn more about this. I have heard data loss stories from my colleagues and want to avoid such disasters by proper documentation

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://tud365-my.sharepoint.com/:p:/r/personal/oonimabisht_tudelft_nl/Documents/01_DFM_Template_Power_Point%20(1).pptx?d=wc16c15c2138b4b689ce17cae945f32bd&csf=1&web=1&e=lAUhbE
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/r/personal/oonimabisht_tudelft_nl/Documents/01_DFM_Template_Power_Point%20(1).pptx?d=wc16c15c2138b4b689ce17cae945f32bd&csf=1&web=1&e=76AgGZ
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
GitHub may not be the best place to manage data actually! It is primarily aimed at software and text files. We don't go into a lot of details on how to use GitHub for actual software management, but hopefully the a[dditional GitHub resources](https://estherplomp.github.io/TNW-RDM-101/03-Assignment-GitHub-1.html#more-github-tutorials) from assignment 1 can help you along further!

**Comment by EstherPlomp** [comment]
Hi @oonimabisht! I don't see a link or comment with your  [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html). Could you please still share this as soon as possible? Thank you!

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment @oonimabisht! It looks clear, well done! 

- I see you're using code/software: you may want to try out a platform that uses version control to manage your code. You could try out GitHub or GitLab for example. TU Delft has a GitLab instance: https://gitlab.tudelft.nl/
- Do you have an estimate for the storage size of the data? You don't have to be precise, an estimation is sufficient!
- Other people have also included files such as presentations/manuscripts and literature: You don't have to add this, but these files also need to be stored somewhere securely!

**Comment by oonimabisht** [comment]
> Thanks for sharing your assignment @oonimabisht! It looks clear, well done!
> 
> * I see you're using code/software: you may want to try out a platform that uses version control to manage your code. You could try out GitHub or GitLab for example. TU Delft has a GitLab instance: https://gitlab.tudelft.nl/
> * Do you have an estimate for the storage size of the data? You don't have to be precise, an estimation is sufficient!
> * Other people have also included files such as presentations/manuscripts and literature: You don't have to add this, but these files also need to be stored somewhere securely!

**Comment by EstherPlomp** [comment]
Hi @oonimabisht: I think you already closed your issue as completed, but as the course is still ongoing I'll reopen it. Otherwise it will be difficult for your peers to provide feedback on your assignments!

**Comment by oonimabisht** [comment]
Dear Esther,
I think I closed it by mistake. Thank-you for looking into it!

Best
Onima

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EstherPlomp** [comment]
No worries! Thanks for sharing assignment 3 as well @oonimabisht ! It looks very clear and comprehensive, well done!

I only have a couple of thoughts:
- Nice to see that you have a group wiki, that sounds very helpful! 
- Will you use any other documentation than readme files to document your Python code, such as comments within the code?
- For Q2 on slide 9 they don't necessarily mean ownership, but rather what type of software would be needed to open your files. I think for you this isn't a big issue as Python is indeed open, and word/Excel is proprietary but indeed interoperable with open software nowadays. People may need Microsoft licenses to fully interact with that part of the data!

**Comment by lkresik** [comment]
Hi @oonimabisht. Can you please provide me access to your Assignment 3? I've requested it already in the SharePoint :)

**Comment by oonimabisht** [comment]
HI, I just did it

**Comment by EstherPlomp** [comment]
Thanks @oonimabisht! Don't forget to provide feedback on other people's assignments as well!

**Comment by lkresik** [comment]
> No worries! Thanks for sharing assignment 3 as well @oonimabisht ! It looks very clear and comprehensive, well done!
> 
> I only have a couple of thoughts:
> 
> * Nice to see that you have a group wiki, that sounds very helpful!
> * Will you use any other documentation than readme files to document your Python code, such as comments within the code?
> * For Q2 on slide 9 they don't necessarily mean ownership, but rather what type of software would be needed to open your files. I think for you this isn't a big issue as Python is indeed open, and word/Excel is proprietary but indeed interoperable with open software nowadays. People may need Microsoft licenses to fully interact with that part of the data!

I agree with Esther about Wiki, it is indeed very useful not only for you but also for others trying to reproduce your results or implement your findings in own research. Also, auto-generated README files for your experimental data are of great help to you and can save you a lot of time, I suppose :) Nice that you have this option! 
Overall, you have a great plan to take care of your data. I hope it will make things easier for you to avoid stressful situations in the future. The only thing I would like to suggest is to store your code on platforms like GitHub. I am not really into programming/coding, but it seems like a convenient place to do that :)
