### ISSUE TITLE
Overview issue Daphné Cette

### ISSUE THREAD

**Issue by DaphneCette** [EstherPlomp/TNW-RDM-101#140]
### Introduction

Hi all! My name is Daphné Cette and I work at the Reactor Institute. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I am working on americium-based RTGs (radioisotope thermoelectric generators) which are batteries used to power spacecrafts in deep space missions. I am combining experimental work and thermodynamic modelling to determine the best composition of the radioisotope source. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | Yes |
| Write/develop software as the main output of the project  | No |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A |
### Reflections on the importance of RDM videos

My main take away from the video is that maintaining a great data management plan is profitable for everyone: colleagues, partners, other scientists, publishers, readers, and me. 
My horror story is when, as an intern, I was handed the code of someone that had already left the company. I had to work on how to fix the Python code and improve it with new features. The code was very difficult to read and there were no explanations given. I ended up starting from scratch and writing my own code. 

### What would you like to learn during this course? 

I have been working on my literature review since I started my PhD (3 months ago) and I feel like I already have a lot of data from articles. I would love to learn about some tricks to keep them organized and managed as I wouldn't want to lose time having to find those articles again.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://mega.nz/file/BP4QmZAA#tdQlXqd41FRTqJJdsXgTsZOjKgB0nhca8JTl0j1htIA
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link: https://mega.nz/file/VexB0bDZ#pY4VfGprznW0JMTTr0BxNeHzr0rrlHe-SVXWk3Mn_g8
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @DaphneCette! I don't see a link or comment with your  [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html). Could you please still share this as soon as possible? Thank you!

**Comment by DaphneCette** [comment]
Hi Esther,

I am having some technical difficulties uploading my assignment on Github.
For some reason, I don't receive the 2FA code needed to sign in. I tried
several times but it still doesn't work.

Maybe it has something to do with the fact I am in the US at the moment for
a conference. I tried to sign in to the VPN of TU Delft but they also ask
me for a code and I also don't receive it.

I will try again later. I attached my assignment to this email in case it
doesn't work.

Sorry for the inconvenience. Let me know if you have an idea of what might
help.

Kind regards,
Daphné

Le mer. 8 mai 2024 à 11:26, Esther Plomp ***@***.***> a
écrit :

**Comment by DaphneCette** [comment]
It worked!
Sorry for the inconvenience.
Kind regards,
Daphné

**Comment by EstherPlomp** [comment]
Thanks @DaphneCette for managing all the technical difficulties while being at a conference! Enjoy the rest of it!

**Comment by EstherSpruit** [comment]
Hi Daphné,

I had a look at your assignment 2. 
For the literature articles, you made a red flag indicating restricted access. Do you mean that in the future you might not be able to access them anymore? Then you can consider downloading the papers you read and storing them in a literature folder (also convenient when you want to make digital notes). 
As format you mention Word+Excel. Is this to organize the articles? Have you considered using a reference manager? Personally, I use Jabref, this really helped me to organize papers, with labels/subfolders and some comments for each paper. But there are many other good reference managers as well. 

For the OSEC experimental data. You mention that you also do the analysis in the Excel file. Keep in mind that you also store a raw version of your experimental data (preferably in a separate file), if something goes wrong with the analysis then you can start over, without having to do all experiments over.

You will store the master copy of your data on the U-drive. One of the advantages of the U-drive is that is can be easily shared. However, if other people have edit rights that can also mess up your stuff. Do others have access to your U-drive? If so, have you considered how you can prevent your collaborators from affecting your master copy?
For the rest, I think a copy on your own computer and on the U-drive is compliant with the 3-2-1 rule.

**Comment by EstherPlomp** [comment]
Thanks for all your feedback @EstherSpruit! I agree with all the comments and I have some feedback from my side as well: 

- Regarding the U: drive: this is indeed secure for confidential data! Especially with the U: drive you control who has access to the drive. That does indeed mean like Esther already said that whoever has access to the drive has the same rights for the entire drive. So if you allow them to have editing rights they may indeed affect your data. The Staff/Group drive is generally accessible by more people, so chances of anything happening are much higher there. And whether these solutions are then suitable for confidential data depends on your agreements with collaborators. Generally collaborators are fine with sharing data within the research group, but in some instances they are much stricter. Do check this with your supervisor in case of doubt!
- No worries that you don't know what data you'll generate yet: You should still be able to complete the majority of assignment 3 despite this!

@DaphneCette, Please let me know if you have further questions about all of these storage drives!

**Comment by EstherPlomp** [comment]
Hi @DaphneCette ! I don't see a link or comment with your [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html). Could you please still share this as soon as possible? Thank you!

**Comment by EstherSpruit** [comment]
Hello Daphné,
Theme (2) looks oké. Cool that you made your own reference manager, I think it is important to do what works for you, whether this is an excel sheet or an existing reference manager.
In the last class, you discribed a very handy excel file to keep track of you samples and the corresponding files. I assume you will implement that again during you PhD? I really liked your idea, so much that I now have implemented a similar system myself :)

For the documentation, I missed something that describes what is in which file. Have you considered adding read-me files or a data dictionary to your folders?

About access. Have you considered how you will share your data with students (when you will be supervising BEP/MEP students)? And is it allowed to share data with students or is that forbidden by the company that funds your project?

Small details about the data publication, don't forget to include your licence. (For instance: cc by)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @DaphneCette! It looks very comprehensive, well done!

- It looks like there is some room for improvement with ThermoCalc! No worries to keep file formats in proprietary files if this is the main programme/file format used within the discipline. 
- Do you really not need any other metadata other than the metadata generated with the raw data? That is very nice!
- Just a note that it is not recommended to share data via supplementary files in journal articles, as it is not in line with the FAIR principles. In this case a data repository would be a better solution. If you don't have any supplementary files and you can share all of the information via the article it is not needed of course, but it sounds like it may be worthwhile to still have a look at what data repository you could use for this!

And thanks also for your great feedback @EstherSpruit! Indeed don't forget to share your license preferences in the [license discussion thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/126) @DaphneCette !

**Comment by EstherPlomp** [comment]
Hi @DaphneCette: don't forget to submit [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html)! The deadline was earlier today!

**Comment by RiteshDas2000** [comment]
Hi @DaphneCette , like @EstherSpruit mentioned, you may wanna store the raw data in some format. I would recommend something like .csv files as they can be accessed easily by humans and machines/ codes alike. They are also relatively small in size.

**Comment by DaphneCette** [comment]
Hi Esther,

Hereby is my Assignment 5 for tomorrow. Let me know if I need to
change anything!

Kind regards,
Daphné

Le jeu. 30 mai 2024 à 15:01, RiteshDas2000 ***@***.***> a
écrit :

**Comment by EstherPlomp** [comment]
@DaphneCette - I don't see a link or attachment with your assignment 5, sorry: Can you try to send it again/share a link to the file? Thanks!

**Comment by RiteshDas2000** [comment]
You mention that you use U-drive for storage, which is nice. I notice for the assignments you chose to share via "MEGA". In assignment 3 you mentioned that a company funds your project and you share data with them. I would advice against ever using MEGA for this purpose. MEGA has a reputation for being unsafe and used by illegal file sharers.
