### ISSUE TITLE
Overview issue [Anish Kumar Kodyingal]

### ISSUE THREAD

**Issue by anish8194** [EstherPlomp/TNW-RDM-101#142]
### Introduction
Hi, my name is Anish Kumar Kodyingal. I am a PhD candidate in the RPNM group in Reactor Institute in TU Delft.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research deals concerns the modelling of a novel zinc-air battery which will lend itself better to cycling operation. The current zinc-air battery technology is a primary battery meaning that it cannot be cycled so our research would like to make it cyclable.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |

### Reflections on the importance of RDM videos
How important reproducible research is. Why is reproducible research important from a selfish stand point.

### What would you like to learn during this course? 
Yes, I want to create a really good data management plan since I am working on code for my PhD and I would like to learn the best practices in the field since my previous experience has been with wet lab experiments mostly.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/i5VaEiuYI6WiN18
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/i5VaEiuYI6WiN18 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [ ] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by Nico7575** [comment]
Your DMP is concise and clear. Just one question: do you think the codes will occupy more storage than the experimental data/output of the models? (usually code doesn't take a lot of space)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @anish8194! It looks clear, well done!

- In your data challenge you mentioned 'extremely large simulation' - this does not seem to result in a lot of data from your estimations in your data flow map though? Can you clarify what you mean with extremely large simulation? See also [your data challenge for some tip](https://github.com/EstherPlomp/TNW-RDM-101/discussions/125#discussioncomment-9417002)s - if these are not helpful, please also let me know! 
- That ties in with @Nico7575's feedback as well on the storage estimates: thanks for the feedback!
-  Other people have also considered files such as manuscripts/presentations/literature. You don't have to add these in the data flowmap but they do need to be securely stored! SURFdrive sounds like a great solution for this.

**Comment by anish8194** [comment]
Thanks @Nico7575  and @EstherPlomp for you comments. 

1. The reason I put extremely large simulations was that some of the simulations will be in COMSOL and the way that I am storing these files is both the code file along with mesh generated and the solutions set in a simulation file. Thus the total file size is higher than just the output files which usually are just .txt file. Ofcourse these are just my expectations at the moment so I will get a better idea as I progress in my PhD.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @anish8194! It looks very clear and comprehensive, well done! 

I therefore have very little feedback: 
- GitHub itself does not assign DOIs: will you share a copy of the repository on 4TU.ResearchData or Zenodo to get the DOI assigned? 
- will you stick with MIT license for the code? ([as discussed in the License thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/126#discussioncomment-9534097)) 
- Previous course participants were also enthusiastic about [DrWatson](https://juliadynamics.github.io/DrWatson.jl/dev/)[DrWatson](https://juliadynamics.github.io/DrWatson.jl/dev/) when working with Julia.

**Comment by Nico7575** [comment]
Hi @anish8194! Your assignment 3 is very well done, I do not have particular remarks or feedbacks to give you. 
Just one question came up while reviewing it. In the slide on Data Organization you have "model+output", where with "output" I guess you refer to simulations done with a certain version of your code; how do you then differentiate between the code versions and the simulations correlated to them in your folder structure/naming convention?

**Comment by anish8194** [comment]
Thank you @EstherPlomp and @Nico7575 for your comments.

1. Yes, I will share the code on 4TU.ResearchData for sharing and get a DOI assigned there. 
2. Yes, for now the MIT license makes sense based on the consortium agreement. However, this is early on so this is open to discussion with other consortium members who might have other ideas. So, it might change based on the discussions we have in the future.
3. Thank you for sharing the DrWatson link. It seems promising as a Workflow manager for Julia!
4. Yes you are right. It is indeed planned to save with various changes in parameters and versions in code. The idea was to keep saving the files as different versions using the naming conventions 20240529-1 and then update them in a master Excel file which I use to keep track of changes in code.
