### ISSUE TITLE
Assignment 1 [Bhavesh Chavan]

### ISSUE THREAD

**Issue by BhaveshSChavan** [EstherPlomp/TNW-RDM-101#143]
### Introduction

Hi, my name is Bhavesh Chavan and I am a first year PhD candidate in chemical engineering and come from India. I did my masters from University of Twente. I currently reside inside the university.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on using atomic layer deposition in water electrolyzers. I am mainly focusing on the development of electrocatalysts and other electrolyzer componenets using atomic layer deposition.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

The most important aspect of Science is that it should be reproducible and transparent. RDM helps in creating openness among the researchers and creates continuation of the work within the same group, university or even in various corners of the world. 

### What would you like to learn during this course? 

I aim to create my PhD data to be safe, easily accessible to not just me but also for the future use.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://tud365.sharepoint.com/:p:/r/sites/MyPhD637/Gedeelde%20documenten/General/My%20GS/RDM%20101%20AS/Assignment%202%20Bhavesh%20Chavan.pptx?d=w09f2970781b44d198ecce084e7200004&csf=1&web=1&e=PAuFja
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link: https://tud365.sharepoint.com/:p:/s/MyPhD637/ERuXpViDtd9AkubGcl9ts40BmxUsHPVP8JsIOShgCr1OiQ?e=DJQkb2
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**) (Link: https://tud365.sharepoint.com/:p:/r/sites/MyPhD637/Gedeelde%20documenten/General/My%20GS/RDM%20101%20AS/Assignment%205.pptx?d=w21d982a6e9874fe5930c59ed6994fa5f&csf=1&web=1&e=dsLuUV)

**Comment by EstherPlomp** [comment]
Hi @BhaveshSChavan! I don't see a link or comment with your  [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html). Could you please still share this as soon as possible? Thank you!

**Comment by demiteach** [comment]
Hey Bhavesh, 

It is a nice and extended overview of all the data you think your are going to collect. One notion: I don't completely understand where the 'personal data' red flag is coming from. You are not working with the interview/questionaire data, are you?

**Comment by linghangdelft** [comment]
Very detailed map. Does your department project folder mean "Staff Group Data" or "Project Data"? And I see your data are considered as confidential data, have you thought about any special ways to keep them confidential?

**Comment by EstherPlomp** [comment]
Hi @BhaveshSChavan! Thanks for sharing Assignment 2! It looks very clear, well done!

- I agree with @demiteach that it is not clear what type of personal data you are processing: Do you mean the names in the articles and your own thoughts regarding your experiments? I do see your point there as researchers name's are indeed personally identifiable, but we don't really consider this personal research data because it is not the same as them participating in your research project and this information is already public. Regarding thoughts on your experiments - this is normally more about the decisions and choices you faced, which may not necessarily lead back to you. Could you please elaborate or update this in your Assignment 3? If you are working with personal data, then @linghangdelft is right that you need to consider more where you store this type of data. The Staff group data/department storage is not a good storage location if other people have access to your folders/directories there! For confidential data it depends what you have agreed upon with the collaborators - if they are not putting additional restrictions on access to data by the rest of the research group it is fine. 
- I really like your structured back up procedure in that you have standard dates to do the back up! What happens if the 1st of the 15th falls in a weekend? 
- Very clear indication of the experimental data!

**Comment by irisforkink** [comment]
Hi Bhavesh, nice overview, it's very clear. Do you know how you are going to store your lab journal data? Will you copy it onto your computer? Or have you considered an electronic lab journal? My group will start working with this in September, might be useful for you as well? Saves a lot of time of copying information :)

**Comment by EstherPlomp** [comment]
Hi @BhaveshSChavan ! I don't see a link or comment with your [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html). Could you please still share this as soon as possible? Thank you!

**Comment by BhaveshSChavan** [comment]
> Hey Bhavesh,
> 
> It is a nice and extended overview of all the data you think your are going to collect. One notion: I don't completely understand where the 'personal data' red flag is coming from. You are not working with the interview/questionaire data, are you?

It is because the personal data would also include novel ideas for experimentation. As per my supervisor, this novel data should be strictly confidential unless consortium agrees on making it public. For example, having limitations on delivering data in posters and presentations in conferences.

**Comment by BhaveshSChavan** [comment]
> Hi Bhavesh, nice overview, it's very clear. Do you know how you are going to store your lab journal data? Will you copy it onto your computer? Or have you considered an electronic lab journal? My group will start working with this in September, might be useful for you as well? Saves a lot of time of copying information :)

As of now, I try to put less data on hard copy lab journal but I am shifting to electronic version for example having lab journal documents using an iPad stored in teams folder as per the dates.

**Comment by BhaveshSChavan** [comment]
> Very detailed map. Does your department project folder mean "Staff Group Data" or "Project Data"? And I see your data are considered as confidential data, have you thought about any special ways to keep them confidential?

I still need to decide with my supervisor, to what extend it should confidential to even my research group members.

**Comment by BhaveshSChavan** [comment]
> Hi @BhaveshSChavan! Thanks for sharing Assignment 2! It looks very clear, well done!
> 
> * I agree with @demiteach that it is not clear what type of personal data you are processing: Do you mean the names in the articles and your own thoughts regarding your experiments? I do see your point there as researchers name's are indeed personally identifiable, but we don't really consider this personal research data because it is not the same as them participating in your research project and this information is already public. Regarding thoughts on your experiments - this is normally more about the decisions and choices you faced, which may not necessarily lead back to you. Could you please elaborate or update this in your Assignment 3? If you are working with personal data, then @linghangdelft is right that you need to consider more where you store this type of data. The Staff group data/department storage is not a good storage location if other people have access to your folders/directories there! For confidential data it depends what you have agreed upon with the collaborators - if they are not putting additional restrictions on access to data by the rest of the research group it is fine.
> * I really like your structured back up procedure in that you have standard dates to do the back up! What happens if the 1st of the 15th falls in a weekend?
> * Very clear indication of the experimental data!

Hi Esther, thank you for your comments.
The personal data will involve novel ideas, decisions, and reasoning. 
About the department storage, it is still yet to be decided on the level of confidentiality with the supervisor.
About your comment on 1st or 15th on weekend, the solution would be do it next Monday after the weekend.

**Comment by EstherPlomp** [comment]
Thanks for elaborating @BhaveshSChavan! Novel ideas, decisions and reasoning are not considered to be personal data, as they do not lead to the identification of a person. I'm not sure what to rename your flag, as I would personally not consider this a flag but a key part of the research process? What do you think? 

Don't forget to still share assignment 3!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @BhaveshSChavan! It looks very clear and comprehensive, well done! 

I therefore only have a question: what do you mean that 4TU.ResearchData will also provide a DOI for patent information? Will you share the patent application on 4TU.ResearchData once completed? I'm not sure if that is possible for patent information!

**Comment by EstherPlomp** [comment]
Hi @BhaveshSChavan: don't forget to submit [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html)! The deadline was earlier today!

**Comment by BhaveshSChavan** [comment]
> Thanks for sharing assignment 3 @BhaveshSChavan! It looks very clear and comprehensive, well done!
> 
> I therefore only have a question: what do you mean that 4TU.ResearchData will also provide a DOI for patent information? Will you share the patent application on 4TU.ResearchData once completed? I'm not sure if that is possible for patent information!

Hi Esther,
Do you have any suggestion?

**Comment by EstherPlomp** [comment]
Can you perhaps elaborate a bit on what you would like a suggestion on? On how to share patent information or what you should use 4TU.ResearchData for? Let me know!
