### ISSUE TITLE
Overview issue [Fenghuan]

### ISSUE THREAD

**Issue by LonghengZhang** [EstherPlomp/TNW-RDM-101#144]
### Introduction
Hi, I am Fenghuan, a first year PhD candidate in applied physics department. I am an easygoing person and I like making friends. In my spare time, I would play sports such as tennis, badminton and going to the gym. Besides, I really like play video games, especially baldur's gate 3.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research concentrates on the manipulating quantum state of a single atom on a surface. In order to do this, temperature and pressure should be maximally reduced and the surface should be extremely flat, so that the influence from environment is minimized. We use a technique called scanning tunnellng microscopy to find and generate the picture of the single atom, and apply a radiofrequency magnetic field to the single atom to manipulate its quantum state.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
As a first year PhD, I haven't started dealing with data for my PhD project. During my master, I mainly do finite element simulation and optimization, which generate lots of data which has different parameters. Besides, I have to work with another simulation PC and a computational cluster, and the transfer between different platform could cause messy if some operations are not done right. Therefore, I start realizing that data management is very important because we save times and avoid mistakes by doing this. Then I decide to learn about research data management, so that I can do it right at the beginning.

### What would you like to learn during this course? 
I want to learn about the "standard" way of data processing.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/mQabHqBIQNfCDnD
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #126
- [x] Respond to the GitHub discussion #127
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/XadgtDpFTba1UKE
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [x] Respond to the GitHub discussion #128 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @LonghengZhang! I don't see a link or comment with your  [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html). Could you please still share this as soon as possible? Thank you!

**Comment by LonghengZhang** [comment]
> Hi @LonghengZhang! I don't see a link or comment with your [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html). Could you please still share this as soon as possible? Thank you!

Hi @EstherPlomp! Sorry for the delay! I have looked through the material and finish the assignment 2!

**Comment by EstherPlomp** [comment]
Thanks for sharing @LonghengZhang! It looks very clear - well done!

I don't have a lot of feedback from my side, just: 
- You can also use a platform that implements version control to manage your code, such as GitHub or GitLab. TU Delft hosts a GitLab instance: https://gitlab.tudelft.nl
- Others have also included files such as presentation/manuscripts in their map. You don't have to add these to your map, as long as the files are stored securely somewhere :)

**Comment by EstherPlomp** [comment]
Hi @LonghengZhang! I don't see a link or comment with your [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html). Could you please still share this as soon as possible? Thank you!

**Comment by EstherPlomp** [comment]
Hi @LonghengZhang : don't forget to submit [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html)! The deadline was earlier today!

**Comment by LonghengZhang** [comment]
Hi @EstherPlomp! I am a bit confused about the last assignment. Is the slide I should submit the one I used in the assignment 2 and 3?

**Comment by EstherPlomp** [comment]
Apologies about the slow reply @LonghengZhang! You only need to submit 1 slide - so if you can tell your challenges/next steps from one of the slides from your previous assignments, you can submit that. But it may be easier to just submit a slide that addresses the questions asked!

**Comment by EstherPlomp** [comment]
And hereby your feedback for assignment 3 @LonghengZhang!

It looks very clear - well done! 

- You didn't add the MIT license yet to the last slide, but I saw it in the discussion thread and in your data management plan. 
- The lessons by the [Code Refinery on code documentation](https://coderefinery.github.io/documentation/) might be of use!

**Comment by oonimabisht** [comment]
Hi @LonghengZhang . Your plan looks very clear. I had a few comments
1. In data organization, for the folder structure, I see the folder Raw data in which you have data. Instead of having all data files, maybe you can make folders with different dates and store your data in them. This might save you from writing dates on every data that is saved. This is what we do, and find it simpler. Maybe you can do it as well.

Rest of it looks well understood!
