### ISSUE TITLE
Overview issue [your-name-here]

### ISSUE THREAD

**Issue by BhaveshSChavan** [EstherPlomp/TNW-RDM-101#145]
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes/No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes/No  |
| Collaborate with industry  | Yes/No  |
| Write/develop software as the main output of the project  | Yes/No  |
| Use code (as in programming) for data analysis | Yes/No  |
| Work with large data (images, simulation models) | Yes/No  |
| Other:  | N/A  |
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (the overview issue) (before **30 April, 10:00**)
- [x] Respond to the GitHub issue #125
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **7 May 13:00**). Link: Onedrive link- https://tud365.sharepoint.com/:p:/r/sites/MyPhD637/Gedeelde%20documenten/General/My%20GS/RDM%20101%20AS/Assignment%202%20Bhavesh%20Chavan.pptx?d=w09f2970781b44d198ecce084e7200004&csf=1&web=1&e=PAuFja 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #126
- [ ] Respond to the GitHub discussion #127
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **21 May 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **29 May 13:00**)
- [ ] Respond to the GitHub discussion #128 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **30 May, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @BhaveshSChavan! I think you accidentally opened up a new issue to hand in your assignment. I'll close this issue as otherwise your comments/feedback will be scattered over multiple issues. No need to respond or do anything in particular from your side for this!
