### ISSUE TITLE
Assignment 1 Riccardo Dal Mas

### ISSUE THREAD

**Issue by RiccardoDalMas** [EstherPlomp/TNW-RDM-101#69]
### Introduction
Hi all, my name is Riccardo Dal Mas and I'm a PhD student at TNW/Chemical Engineering. I work with CO2 and sustainability!

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research focuses on the development of system analyses for processes using CO2 and renewable electricity to produce chemicals and fuels! CO2 could become a relevant raw material in the process industry if coupled with low-carbon power sources, substituting fossil hydrocarbons in relevant supply chains. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | No  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I think that RDM is very important to ensure traceability of the sources of the data I use for the simulations, both with respect to the input values (where do they come from, etc.) and the output (what are they the result of, etc.). Even though I don't have personal horror stories as such, I have experienced the importance of properly documenting calculation and analysis for large project which come to a stop but might be restarted at some point in the future.

### What would you like to learn during this course? 

Develop a structured mindset with respect to RDM, which allows me to always implement best practices when dealing with data.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
[Riccardo - RDM101_Assignment1_Week1_DataFlowMap_v01.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12646221/Riccardo.-.RDM101_Assignment1_Week1_DataFlowMap_v01.pptx)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
[Riccardo - RDM101_Assignment2_Week2_DataFlowMap_Template.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12795013/Riccardo.-.RDM101_Assignment2_Week2_DataFlowMap_Template.pptx)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00** )
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**). Link: [Riccardo - RDM101_Assignment3.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12853717/Riccardo.-.RDM101_Assignment3.pptx)

**Comment by RiccardoDalMas** [comment]
Hey, here is my [Assignment 2: Data Flow Map 1]([Riccardo - RDM101_Assignment1_Week1_DataFlowMap.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12617166/Riccardo.-.RDM101_Assignment1_Week1_DataFlowMap.pptx))


Cheers,
Riccardo

**Comment by RiccardoDalMas** [comment]
> Hi Riccardo,
> 
> Feedback on your Assignment 2: It feels like some datasets are missing. For example, will you be writing documentation for the analysis code? Also, will you be creating figures, charts, data visualizations of any kind? How will you store your simulation parameters?
> 
> Other than that, it looks good.

Hello Pjieter,

thank you for your valuable feedback! You raise some good points, which I had missed.
I have added a couple of items to my overview, in particular with respect to the figures and the documentation of the simulations. The simulation parameters will be stored in Excel files (under 'Input/output management').

Here is the updated overview:
[Riccardo - RDM101_Assignment1_Week1_DataFlowMap_v01.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12645854/Riccardo.-.RDM101_Assignment1_Week1_DataFlowMap_v01.pptx)

Cheers,
Riccardo

**Comment by EstherPlomp** [comment]
Thanks for the feedback @Pjieter and for updating your assignment @RiccardoDalMas! Well done on the assignment: it looks very clear and now also comprehensive.

I think from our email conversation you also changed your storage strategy to storing things on OneDrive and then backing them up to the Project Drive. This is better than storing it locally on your laptop as that local space is not automatically backed up, whereas the other two options are. 

I don't see any red flags - which should hopefully make your research life easier :) I'm just wondering whether it will be easy for you to collect the data from others (in the input/output management): is this easy to find and is it organised in a manner that is helpful to you?

**Comment by RiccardoDalMas** [comment]
> Thanks for the feedback @Pjieter and for updating your assignment @RiccardoDalMas! Well done on the assignment: it looks very clear and now also comprehensive.
> 
> I think from our email conversation you also changed your storage strategy to storing things on OneDrive and then backing them up to the Project Drive. This is better than storing it locally on your laptop as that local space is not automatically backed up, whereas the other two options are.
> 
> I don't see any red flags - which should hopefully make your research life easier :) I'm just wondering whether it will be easy for you to collect the data from others (in the input/output management): is this easy to find and is it organised in a manner that is helpful to you?

Hi @EstherPlomp,

thank you for the feedback!
In theory I would need to get some experimental data from some other researchers, but the data should not be very extensive (only some key performance indicators for their setups). I don't know at the moment how it is organised, but hopefully it should be manageable for me!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @RiccardoDalMas! It looks very clear, well done!

**Data organisation**
- Great file naming! Do take care that they also don't get too long.  

**Metadata**
- The Python version and libraries/dependencies you used for your scripts are also metadata that are important to document!

**File Format**
- Indeed, sometimes it is not possible to convert files. As long as the software is broadly/commonly used this should not be a problem. 

**Data Publication**
- Before your defense, at least the data/code underlying the chapters of your dissertation should be made available on a data repository. That may indeed not be all of the data/code that you have generated. 
- I did not see your preference for the license in this assignment, but [you indicated that in the license thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/66#discussioncomment-7032057) #66

**Comment by QingLi-11** [comment]
Hi Riccardo,

Thank you for sharing assignment 3. One question relevant to your data publication -  for the simulation results, will you make the original file (e.g., Aspen Plus .bkp file) open or just share the flowsheet and the parameters for the process?

Thank you!
Qing
