### ISSUE TITLE
Assignment 1 Michiel Dubbelman

### ISSUE THREAD

**Issue by Pjieter** [EstherPlomp/TNW-RDM-101#70]
### Introduction

Hi! I'm Michiel, I've started my PhD about 4 months ago at the Ali Lab at QN. Looking forward to learning more about RDM.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I will be researching the electrical and magnetic response and interplay of van der Waals materials. These are a relatively new group of materials which have promising properties for higher accuracy and low-energy sensing and computing. Also, they are just very fascinating and behaving in unexpected ways.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I did my thesis on this topic as well, and have data from that time that I still want and need to use. I did my best to store it systematically, but I am now noticing it was not in the best way. So what Florian said about your past self doesn't respond to emails already struck a chord with me.

### What would you like to learn during this course? 

How to store data about samples in an organized manner. How to create a good lab notebook.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
https://tud365-my.sharepoint.com/:p:/g/personal/mpdubbelman_tudelft_nl/ERYcvbnzA61BpQWKlMEKTaYB4FDOyn_9Q1POgd5Or7v2wQ

- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/mpdubbelman_tudelft_nl/ETQZKLWpTxtLrJyR3C8PdecBaAqg1f3p2bwlBS9WOLaihA?e=TZK4lL
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**) Link: https://tud365-my.sharepoint.com/:p:/g/personal/mpdubbelman_tudelft_nl/EQ2hgIypGztDrqtTtmY5d9UB7BiAQotR-xS0AftdjWVBdQ?e=Z59q3S

**Comment by cfprimavera** [comment]
Hi Michiel!
Your data flow map looks very complete to me; I like that you mention so many different types of data apart from your measurements. The only thing that raises some questions for me is the estimation of file sizes. >10 MB for .txt, .py, .json, or .csv files seems large to me. Perhaps you can double check those.
Best,
Christian

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 2 @Pjieter! It looks great - very comprehensive and clear, well done!

I don't think I have anything helpful to add - I like how you shared the Machine Learning parameters, even when you don't know the full details yet. 

I also commend @cfprimavera for finding something to provide feedback on - it is quite difficult for your assignment ;)

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 and 5 @Pjieter! It looks very clear and also concise: well done! I'm glad to see that you find cookiecutter helpful!

Some minor comments and thoughts from my side: 

**Data Organisation**
- very nice to see that you have a .json file with the metadata available for electrical measurements!

**Documentation**
- See the [code refinery materials on documentation](https://coderefinery.github.io/documentation/) for your future project!

**Metadata**
- version of programming languages and libraries/dependencies are also a form of Metadata for code

**File Formats** 
- I do see some proprietary file formats: pptx and docx are not open file formats as you can't fully interact with these file formats outside of the Microsoft office suit. They are openable by other software and very widely used, so that is not necessarily an issue. For my own data, and also presentations, I tend to share a pptx file as well as a pdf copy so that I have both the open file format and the most reusable file format available. I hope that makes sense!

**data publications**
- I don't see your license preferences in the assignment but saw that you went with CC-BY for data and MIT license in #66
