### ISSUE TITLE
Assignment 1 Esther Plomp

### ISSUE THREAD

**Issue by EstherPlomp** [EstherPlomp/TNW-RDM-101#71]
### Introduction
Hi all, my name is Esther Plomp and I'm the Faculty's Data Steward. I also have two cats!

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research focuses on the development of a new method to study the mobility patterns in humans. By analysing the neodymium isotope composition of the enamel of human teeth you can provide an approximation of where the individual grew up (as the isotopic composition is related to the food/water you consume.)

### My research entails the following aspects: 
Fill out Yes or No's to the aspects that apply to your research project.

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
I think RDM is very important in ensuring that you built your conclusions on the correct data. I haven't lost any digital data during my PhD but I guess I could have spent less time looking for the correct version!

### What would you like to learn during this course? 
I would love to learn about your challenges and see if there is anything I can do to make things easier. I'm also happy to receive any feedback about this course and the format - always happy to improve!

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [ ] Respond to the GitHub issue #65 
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: [link to assignment](link)
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #66
- [ ] Respond to the GitHub discussion #67
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)
