### ISSUE TITLE
Assignment 1 Miki Segami

### ISSUE THREAD

**Issue by msegami1** [EstherPlomp/TNW-RDM-101#73]
### Introduction
Hi, my name is Miki Segami, I am a PhD Candidate at the Bioprocess Engineering section, part of the Biotechnology department. One of my hobbies is photography.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
I am working on developing a "hands-free" bioreactor with Chinese Hamster Ovary cells for the production of monoclonal antibodies (biopharmaceuticals). For this purpose, I will use Raman spectroscopy to monitor and control the concentration of different nutrients. In addition, I will use Computational Fluid Dynamic models to investigate the scaling- down and scaling-up of such bioreactor.  

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
I can be a bit paranoid so the stories told in the video, like getting the laptop stolen or the building burning down, really justify my fears and motivates me to improve further how I store my data. I have never lost data like in the stories in the video, but the times where I didn't click save and the software crashed were already very bad moments for me.

### What would you like to learn during this course? 
The article on reproducibility really sparks my motivation to improve how I organize my data and how I keep a record of my experiments. I want to learn how to work faster and more efficient when processing large amounts of data.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/msegami1_tudelft_nl/EXf764oc0bRBokX_oKisLpMB7usrfvU48vhRnU204fE3mg?e=XxZMnW
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/msegami1_tudelft_nl/EUSCmkulmlpOnY2raUY2A54BD0cbsDw52sDg7a0n6k_3yA?e=Ykhfxc  
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by nnadalalemany** [comment]
Hi Miki :) 

Nice Data Flow Map! I really liked how you made many different categories of data and specified how was each type produced.
As feedback, I have three questions that could help completing the DFM:
- Are there any extra measures that you need to take to protect the confidential data?
- Will you write the values of the lab bench measurements yourself and where, or will you extract the measurements as a digital file? I am asking so that in case you write it down yourself in paper, transcribing it into your digital files would be an important step to prevent that any accident on your written data compromises it.
- Will you save different or the same things in the U and H drives?

Thanks and see you around,

Natalia

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @msegami1! I agree with @nnadalalemany that this looks very nice and comprehensive! Well done!

The only thing I might miss are some of the file formats of the data that you're producing: assignment 3 goes a bit more into file formats so it will become more relevant there. 

I think for the confidential data it is good that you're using the :H and :U/project drives - this will prevent access by any external parties. I do share @nnadalalemany question about what will be stored where - might it make more sense to just use the project drive or do you want to store some of your files/data indeed in a separate location?

And just for completeness as you mention you're using an ELN: [TU Delft provides licenses for RSpace and eLABjournal](https://www.tudelft.nl/en/library/research-data-management/r/manage/electronic-lab-notebook). I'm not sure if you're using these already, but just wanted to make sure you're aware of them.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @msegami1! Especially the data organisation part looks very well organised - well done! 

**Metadata**
- Is there really no additional metadata for the Raman spectroscopy? Similarly, it looks like the lab bench measurements already have some metadata in the description of the dataset (pH, osmo, conductivity). 
- What are the variables/column headers of the off-gas analyzer data? 
- And what version of MATLAB do you need? Which packages/libraries are needed? What are the dependencies?

**File Formats**
- Just a note that excel and .ppt files are not open: you cannot fully use these proprietary formats using other software programmes. An open alternative to this is .csv or OpenDocument Presentation (.odp), or pdf (although that is not as reusable unfortunately). Microsoft formats are widely used and to some degree also interoperable with other software - so it might not make sense to convert them to these open file formats. (I tend to share both the Microsoft file formats and the open formats to ensure that the files can be opened in the long term, but to also keep the full functionalities of the Microsoft files. I would only do that with data that isn't GB/TB in size though, otherwise you're using a lot of storage space for the same information. I hope this consideration makes sense!)

**Access/Data publication**
- Indeed, industry partners may not always be enthusiastic about sharing data. I hope at least the data/code underlying publications could be shared, but this should always be run past all collaborators!
- Should the access be restricted you can always add the contact details of your supervisor to README files, to make it easier for people to find out how they should get access to the restricted data. 

I hope you got a spot for one of the programming workshops!
