### ISSUE TITLE
Assignment 1 Hua Chen

### ISSUE THREAD

**Issue by HuaChenTUDelft** [EstherPlomp/TNW-RDM-101#74]
### Introduction

Hello, everyone! I am Hua Chen from the Opto-electronic Materials group in the department of Chemical Engieering. I love playing football and pool. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I mainly work on quantum dots-based light-emitting electrochemical cells. I am investigating the working principle of these devices and figure out ways to optimize them. I am also trying to control the p-n junction in the cell.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No |
| Write/develop software as the main output of the project  | No |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

Losing data is absolutely horrible to everyone in academia. It is of great importance to make backup for all the data on a regular basis. Actually I have not encountered this situation because the supervisor during my bachelor period required us to make backups once a month and I keep doing this since then. However, it is still necessary to be careful to aviod losing all the data.
### What would you like to learn during this course? 

I would like to learn about the best way to make data backups. Now I use mobile hard disk drive to make backups and what if it is broken suddenly. And I want to learn about the TU regulations of data for my thesis. I want to prepare a reliable and practical data management plan after this course.
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/q2rLLBcx4967429
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by EstherPlomp** [comment]
Copied from #93 

Hi all,

Below is my data flow map. Feel free to comment on it.

[RDM101_Assignment2_Week1_DataFlowMap_Hua Chen.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12665044/RDM101_Assignment2_Week1_DataFlowMap_Hua.Chen.pptx)

Best,
Hua

**Comment by msegami1** [comment]
Hi Hua,

I checked your data flow map and I was wondering: how much do you depend on the data collected by colleagues and students? do you have a plan to discuss together how they back-up their data?

Also, why did you decide on SURFdrive? I had the idea that it is not a super long-term solution.

**Comment by HuaChenTUDelft** [comment]
> Hi Hua,
> 
> I checked your data flow map and I was wondering: how much do you depend on the data collected by colleagues and students? do you have a plan to discuss together how they back-up their data?
> 
> Also, why did you decide on SURFdrive? I had the idea that it is not a super long-term solution.

Hi Miki,

Thanks for your comments.

Firstly, the data collected by colleagues and students is planned to be a little bit of my thesis and mainly it is from my students. The data for the papers and thesis will be mostly my own data collected from the experiments and the simulations. I plan to make backup of my students' data after they finish their project and of course they have their own plans for data storage during this 7 months.

Secondly, SURFdrive is one of the ways to make backup for my data. I have firstly all my data in the local drive. And also I will store the data for the papers and thesis on the project drive and group drive as well. I do back-up of my data once every two months on a hard drive of my own. This is my plans till now.

Best,
Hua

**Comment by HuaChenTUDelft** [comment]
> Thanks for sharing your assignment 2 @HuaChenTUDelft!
> 
> I agree with @msegami1 that reusing data of others, or collaborating with them, might be a concern for your project. You can also add a red flag to the assignment for this. Collaborating with others is great, but you can run into troubles if you don't have all the data you need, or the documentation needed to interpret it, or the person might at some point not respond to any emails you send them.
> 
> From your description I'm not entirely sure if you use SURFdrive for all your storage or whether you also use your local drives for data storage. I would recommend to stick with SURFdrive, because this is automatically backed up whereas your local laptop drive is not. SURFdrive is indeed not a long term solution as @msegami1 is mentioning, as it is a personal storage location linked to your netID. If your contract stops the SURFdrive storage will be deleted three months later (you should receive warnings, so I would not worry too much about this right now). A long term solution could be the [Project Drive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#project-drive) because that drive can be extended beyond the contract and you can also provide your collaborators with the same access rights as yourself. Backing things up to the Project drive might also be a more safe solution than an external drive because those can also be problematic in the long term.
> 
> I also don't see the file formats listed: this will become more clear/relevant for assignment 3!
> 
> And a final comment: if you want to organise your code you can consider the use of GitHub or GitLab!

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 3 @HuaChenTUDelft! It is very clear and it looks like a well structured workflow! 

I see you also added a personal data flag for the experimental data: What part of that would be personal data?

**File Formats**
- Very nice to see that you're only working with open file formats!

**Data publication**
- I don't see a licence choice yet! Do check out the [section on data licenses](https://estherplomp.github.io/TNW-RDM-101/07-FAIR-principles.html#data-and-code-licences) and don't forget to reply in the [discussion thread with your preferred licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/66). If you're not sure about this, I'm happy to have a chat about it!

**Comment by PJL-vandenberg** [comment]
Hi Hua,

I am sorry for doing this so late, but do you have plans to teach your students the metadata formats you are using now? Or to check their metadata to make sure they don't forget to place it, leaving you with their mess?
