### ISSUE TITLE
Assignment 1 Eugene Huang

### ISSUE THREAD

**Issue by eugenhu** [EstherPlomp/TNW-RDM-101#75]
### Introduction
Hello, my name is Eugene. I am a first year PhD student at QuTech in the Andersen lab. I like programming as a hobby, and that's about it.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research is on designing quantum computers using Fluxonium qubits, a type of superconducting qubit, with the aim of scaling up the qubit count on a chip. I mainly do calculations and simulation work, but I also help with measuring/characterizing devices that our lab fabricates.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
Having backups is important to prevent data loss, and having organised data/code helps others and your future self to reproduce results. I don't have any horror stories, but these are some problems I've encountered because of subpar data management.
I use a lot of Jupyter notebooks to interactively perform calculations and one bad habit I have is that the notebooks get very long and they have nonsensical names. In our lab, we use a lot of pre-release 0.x python packages, so compatibility breaks very easily every time we update our environment. This makes re-running experiments from a few months ago hard since we don't track the exact versions of our dependencies

### What would you like to learn during this course? 
Learn best/common practices for archiving research data in an organised way.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/loZ6AJOT4mvNla6
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/qJ2pSHOkmqybfbq
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by eugenhu** [comment]
Thanks for the feedback.

- Yes, SURFdrive or our group's SharePoint files.
- We use an electronic lab notebook. Usually just OneNote for recording experimental results which we store on SharePoint. I should've included this in the data flow map.
- When it comes time to write a manuscript, I'll probably make a folder in SURFdrive to keep the source .tex files and figures and a copy of the data to recreate the figures.

**Comment by EstherPlomp** [comment]
Thanks for following up @eugenhu! That sounds like a great strategy 👍

**Comment by EstherPlomp** [comment]
Thanks for handing in assignment 3 @eugenhu and for also updating your datasets! It looks fantastic so I don't have a lot of feedback, just some minor comments 👍 

**Data organisation**
- I didn't know about DrWatson.jl and will check that out! I'm not super familiar with Julia myself. 
- I really like your additional remark for Q3: yes, we should indeed delete old files to avoid clutter :) 

**Documentation** 
- Do you have experience with Sphinx and would you recommend it? Or is this only useful for large software projects like your comment suggests?

**File formats**
- Microsoft has indeed been opening up their file formats in the latest versions so that they can be more easily opened with other software. So it is still proprietary but at least more interoperable :) 
- Especially for ELNs it may not be needed to use open file formats if the point is to only share the files/notes with your colleagues: as long as they have access it fulfils the purpose. If you want to share the files more widely via a data repository, you can indeed consider alternative formats. 

**Data publication**
- indeed, for publications you already have the publisher taking care of long term preservation! Good to see that you're familiar with the Journal of Open Source Software - they have a very cool workflow using GitHub.

**Comment by eugenhu** [comment]
Hi Esther, thanks for the feedback.

I've used Sphinx once, a few years ago now, to generate documentation for a software project (published in JOSS!) I worked on as a research assistant during my bachelors. There's a bit of a learning curve, and the knowledge I acquired is probably all gone now. I want to try using Jupyter Book one day, which is based on Sphinx but looks like it has more usable defaults and is perhaps easier to use?

I'm not sure if I'll be publishing standalone software libraries during my PhD which would benefit from an actual documentation book, so I might just put everything in a one page readme file. I'll mainly need to provide documentation for some of the scripts we use to run experiments in the lab for my other labmates, and we already have an established GitLab wiki for miscellaneous stuff like that so I'll probably also write my docs there.

For the ELN, we just use OneNote as a quick way for pasting analysis figures from experimental results without following a strict layout. It's not a great experience but no one wants to invest the time into finding/making a better workflow.

**Comment by EstherPlomp** [comment]
I think Jupyter Book may integrate this better - not sure if it is then easier to use because I don't have a lot of experience with it (I'm more of an R user /hide). 

Very cool that you already published in JOSS! 

Not everything needs to become a library/package indeed - its very dependent on the intended use. A GitLab Wiki and README files sound great - sometimes 'easier' solutions work just as good, especially if you need to collaborate with others. 

I'm also not sure if there are much better solutions out there than using OneNote (or other similar solutions). Some of the ELN solutions that require separate licenses do provide more sophisticated workflow templates and connections between different experiments and sample tracking - but you indeed do need to set it up and what if you move institutes and you loose access to the software? It again all depends on your long term intended use of it. As long as you have the information and it is backed up, it is good enough :)

**Comment by Aleartulon** [comment]
Hi Eugene, I only have one question: is there any specific reason why you are using gitlab instead of GitHub?

**Comment by Aleartulon** [comment]
Regarding assignment 3 I agree on the Sphinx point, I was exposed to it during a code refinery course and it is indeed very well suited for code documentation. It is quite easy to use and has a lot of different themes. Github co-pilot is also very handy as it can write documentation for you while you write the code. 
I also think that Jupyter notebook can be more useful than a README file for showcasing main uses, although if it is not written well it can be quite messy.

**Comment by eugenhu** [comment]
> Hi Eugene, I only have one question: is there any specific reason why you are using gitlab instead of GitHub?

Hi, sorry @Aleartulon, just read this now. My notifications were full of replies to other threads since I hadn't turn them off haha.

I'm using the TU Delft gitlab since that's what my other lab members use and it makes it easier to collaborate with other TU delft people as well since everyone basically already has an account. I also use github for personal stuff though.

One feature I like about gitlab though is being able to make subgroups, I don't think github can do this yet. It's nice to have your own little subgroup in a larger group of other repos.
