### ISSUE TITLE
Assignment 1 [Fan Jiang]

### ISSUE THREAD

**Issue by FanJ-TUD** [EstherPlomp/TNW-RDM-101#76]
### Introduction
Hi all, my name is Fan Jiang and I'm from Faculty of Applied Science. I am losing hair now.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research focuses on the preparation of living materials, which are based on hydrogel and microorganism. We expect the device to have application in biomedical and computational scenarios.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I found this video quite inspiring. It actually reminds me of a bad previous story in my 4th year of Bachelor's study. My previous lab cannot afford to buy a equipment thus we always went to another Professor's lab and used the equipment with a hard disc storing our all data. Then one day, an accident happened that one of my senior fell and crashed the hard disc to the ground, which cannot be accessed on PC at all. This story ended up in recovering only 50% of data and delayed graduation of my seniors.

### What would you like to learn during this course? 
I'd like to learn how to store and arrange my data, as well as how to synchronize data on different devices. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/8OStVTR5NnvYldE
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/wD6RGJEK3qP6e7f
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide: https://surfdrive.surf.nl/files/index.php/s/14PP08oO6IGrGvh

**Comment by nnadalalemany** [comment]
Hi Fan, nice data flow map! Cool that you figured out how to back up your data.
A suggestion from my behalf would be to specify what is the actual data you will get from your experiments and how will you store it. For example, will the data from the gel consist of a picture? Or do you get a numeric value? Where will you keep the record of that value?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @FanJ-TUD! It looks very clear and concise, well done!

Regarding the storage solutions: 
- Is the TNW server the N: / M: drive? (Bulk or Group?)
- As I don't see confidential data red flags in your assignment, ICloud is indeed a solution to back up your data. With the backup on another laptop I assume that you have ICloud installed there as well? Or do you have to still manually transfer that backup? 

Related to what @nnadalalemany has already mentioned: do you keep a lab notebook and if so, is it physical or digital? How will you ensure this information is managed properly? 

I like how you have ideas/sketches listed separately! In the future you also have figures for articles, and the articles/chapters themselves, so that could be another 'dataset' to consider.

**Comment by FanJ-TUD** [comment]
> Hi Fan, nice data flow map! Cool that you figured out how to back up your data. A suggestion from my behalf would be to specify what is the actual data you will get from your experiments and how will you store it. For example, will the data from the gel consist of a picture? Or do you get a numeric value? Where will you keep the record of that value?

Hello @nnadalalemany, thanks for your comment! Yes, I have both pictures and quantitative data of my gel, I commonly just put in the slides of my weekly meeting, which are only preserved in my iCloud. That would be a thing to think about. Thanks!

**Comment by FanJ-TUD** [comment]
> Thanks for sharing assignment 2 @FanJ-TUD! It looks very clear and concise, well done!
> 
> Regarding the storage solutions:
> 
>     * Is the TNW server the N: / M: drive? (Bulk or Group?)
> 
>     * As I don't see confidential data red flags in your assignment, ICloud is indeed a solution to back up your data. With the backup on another laptop I assume that you have ICloud installed there as well? Or do you have to still manually transfer that backup?
> 
> 
> Related to what @nnadalalemany has already mentioned: do you keep a lab notebook and if so, is it physical or digital? How will you ensure this information is managed properly?
> 
> I like how you have ideas/sketches listed separately! In the future you also have figures for articles, and the articles/chapters themselves, so that could be another 'dataset' to consider.

Hello Esther. Thanks for your suggestion!
>* Is the TNW server the N: / M: drive? (Bulk or Group?)
The server is the M: drive, I put the data in the shared group folder. 
>     * As I don't see confidential data red flags in your assignment, ICloud is indeed a solution to back up your data. With the backup on another laptop I assume that you have ICloud installed there as well? Or do you have to still manually transfer that backup?
It's a shame that I still transfer data manually to my backup laptop. But now I am gradually using Citrix to connect my school PC to my personal laptop for data sharing. 
>Do you keep a lab notebook and if so, is it physical or digital? How will you ensure this information is managed properly?
Yes I have a physical notebook. Well, I just try to keep my hand writing clear and easy to review

**Comment by EstherPlomp** [comment]
Thanks for following up @FanJ-TUD!

It seems like you're slowly improving the data transfer workflow so that is good! I think for backups it is indeed ideal if it hapens automatically. 

For your physical notebook: Try to set a regular date where you scan the pages of your lab book so that you also have a backup of this. What if you loose your physical notebook? Or someone spills coffee or something on it? How much data/information would you loose if this information is not available anywhere else?

**Comment by EstherPlomp** [comment]
Hi @FanJ-TUD: I don't see a link or comment for assignment 3 - can you please still share your assignment or let me know if you need any help? Thanks!

**Comment by EstherPlomp** [comment]
Thanks again for sharing the assignment @FanJ-TUD! I have a couple of points to consider further, which you may also need for your Data Management Plan / Assignment 4: 

**Documentation**
- What information will be in the .xls/.opi/.tif files that are accompanying the data? 

**Metadata**
- I'm sure you already thought about this, but it would be good to connect the metadata from the powerpoint to the raw data (from the imags and videos of cells)

**File formats**
- Not all of your files are considered open files: Origin is a proprietary software, as well as Microsoft Word/Excel. Excel files can nowadays still be opened with open source software, but I don't think that is the case for Origin. Origin/Microsoft Office are widely used by universities, but anyone that does not have access to licenses for the software might run into issues with opening the files. 

**Data publication** 
- Q1: Which data repository will you use to share the data? You can always make use of 4TU.ResearchData but there might be other repositories that you could make use of. 
- Q4: What license will you choose for the data? You indicated CC-BY in the [license discussion](https://github.com/EstherPlomp/TNW-RDM-101/discussions/66)

**Comment by federa7** [comment]
Hi Fan! 
It was nice to see and learn a little more of how your project is by means of your data flow. I'm wondering how will you go around keeping data together and in context. What I mean is, I see that the names of you files seem to have some key reference (e.g. DA20MA08) and that it might be related to specific conditions that you are testing and I can tell that different types of data would generate from the one same condition/experiment. I see your folder structure indicates that you will store every type of file separately. I would suggest that you make sure you condensed all the information of a single experiment together so that the results can easily be put together in context and traced back.
I am also curious, you mention OriginLab a lot but when looking into it, it seems it is a data analysis and plotting software? Or is it more similar to a lab journal? How do you make sure to keep your data in context with your planning, experimental conditions, results, etc? You put everything down in your journal? You store it powerpoints?

Best,
Federico
