### ISSUE TITLE
Assignment 1 Peter van den Berg

### ISSUE THREAD

**Issue by PJL-vandenberg** [EstherPlomp/TNW-RDM-101#77]
### Introduction

Hi everyone! My name is Peter van den Berg. I am a PhD student in the SEE group, specializing in hybrid solid-state electrolytes. I like playing basketball and playing (video/board/tabletop) games in my spare time.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is focused on replacing the liquid in commercial lithium-ion batteries with a solid polymer/metal blend, because it will reduce the risk of flammability that currently plagues batteries. We use a blend of polymer and metal, because polymers are physically stable, but not very conductive, while the metallic part is conductive, but not very stable, so we wish to combine the benefits of both.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

The main reason I think Research Data Management is necessary for proper scientific inquiry is the reproducibility of data, and the continuity of research. When my friend and I were doing our MSc research, we both had very different predecessors, whose research we were working off of. My predecessor had clearly written everything down, allowing me to find a tiny difference in the acidity level between my measurement method and his that sparked an entirely new area of investigation, while my friend's predecessor had written down mostly final answers, leaving my friend wracking his brain why his yield was much lower given the steps were the same. So that goes to show for me, that writing every step down is crucial, even if not for you, for those who come next.
  
### What would you like to learn during this course? 
 In this course I am hoping to learn a few more tricks on how to properly organize data. Right now I have folders for specific types of data, and when it gets too large, I try to subcategorize, but a good oversight of where everything goes could be improved upon.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/lskek95ozwUsS8f
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/TG46MbDpVVaq5rV 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by msegami1** [comment]
Hi Peter,

I like how you listed and detailed all the data you will handle and the flow. I was wondering about the membranes you are creating, would you also consider them as 'data' themselves?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @PJL-vandenberg! It looks very clear and comprehensive and I really like how you visualised the data collection process! Well done! 

- I also like @msegami1 's question about whether physical samples are data - this is a neglected area in data management which is very important if we build upon it with the rest of the data collection process! 
- Very logical that the Berlin team is responsible for the management of the data from that group. For the M: drive I do tend to recommend to check whether you don't have unauthorised access to it, simply because the :U/Project Drive is generally a bit more restrictive because you have to set it up anew. But if your supervisor is happy with the M: and the access rights there, you're sorted! 
- Is your lab logbook physical or digital? Is this information also backed up?
- Only thing that I'm missing is an indication of your data size, which from your assignment doesn't look like it will be TBs of data. So you should not run into any storage shortages!
- I also use Zotero! I'm a big fan of it compared to other reference managers :)

**Comment by PJL-vandenberg** [comment]
> Hi Peter,
> 
> I like how you listed and detailed all the data you will handle and the flow. I was wondering about the membranes you are creating, would you also consider them as 'data' themselves?

You're right. The membranes also degrade over time, so treating them as data themselves seems like a mistake on my part. The data I meant is the protocol for making the membranes so that the membranes can be reproduced.

**Comment by msegami1** [comment]
Hi Peter,

Nice explanations in all the themes!

Regarding, documentation and metadata, Do you think that, at some point, having a data dictionary would be useful to explain the variables in your excels? that is, if for example, you would use abbreviations for the column headers.

Regarding access, I see you would use SURFdrive to share documents. I am not super familiar with it, but could you modify documents in collaboration too? and be able to see the changes 'real-time'?

Miki

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @PJL-vandenberg! It looks very detailed, comprehensive and clear - so I actually don't have any feedback for you this time! The only thing I saw missing was the software license preference, but you indicated MIT license in #66. 

I would also be interested in @msegami1's question about a data dictionary: would you consider that helpful or not and why? 

I don't think you can use SURFdrive to collaborate in real time - maybe in the browser but I haven't tried this. This does seem to work well for documents on Teams/Sharepoint and perhaps Onedrive?
