### ISSUE TITLE
Assignment 1 Federico Ramirez

### ISSUE THREAD

**Issue by federa7** [EstherPlomp/TNW-RDM-101#79]
### Introduction

Hello! My name is Federico Ramirez and I am a new PhD student at the Bionanosciences department of the Applied Sciences faculty, I come from Mexico and have been in the Netherlands for three years already.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I am working in the field of synthetic biology, particularly on the project of developing a synthetic cell using a bottom-up approach. Basically, I take purified, non-living biological components, such as DNA, proteins and lipids, and put them back together to from cell-like compartments capable of mimicking cell-like activities. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

What I get the most out of the videos is the importance of DM for the transparency and ethics in science. Also, the importance for reproducibility in general, together with overall science quality. I did my Master thesis in this same lab and I already can see what I could have done better with managing data by seeing how my old-supervisor (now co-worker) has to ask me on how to interpret, or where to find, information. I think of what it would be like for her if I was not here and it seems scary.

### What would you like to learn during this course? 

I look forward to learn good practices and recommendations on how to standardize data storing and management. I hope to also find introductory steps and information of how DM relates/bridges to open science. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: [Assignment 2](https://surfdrive.surf.nl/files/index.php/s/nfc0nBOW3Ly8T14)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  [Assignment 3](https://surfdrive.surf.nl/files/index.php/s/7K1tqgirzonBKk3)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by EstherPlomp** [comment]
Copied from #95: 

Hello everyone,

I share with you the link to my [assignment 2](https://surfdrive.surf.nl/files/index.php/s/nfc0nBOW3Ly8T14). I hope it is clear for everyone. In my case, I couldn't think of particular flags for the type of data I will be working on.

Let me know if you identify any point of improvement or if you have any comment.

Best,
Federico

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @federa7! It look very clear and comprehensive, so I have little feedback! Well done!

- With 'A significant amount of my data remains stored in the source equipment for one month.' do you mean that after you transfer the data it will still be there on the source equipment for a month? Or do you only transfer the data after a month? I hope the former? I suppose it will have to be removed because of the size involved?

**Comment by nnadalalemany** [comment]
Hi Fede, very nice DMP!
I really liked how you carefully entered all information associated to each dataset.
As a suggestion, maybe you could order the actions associated to each dataset in chronological order if possible, or even number them! That would make it easier to follow your workflow.
Cheers,
Natalia

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @federa7! It looks very clear and extensive! Well done especially on the data publication part where you have looked into the various options available to share the data!

**Metadata**
- I'm glad to see that you found some standards/repositories that are more tailored for your needs ([SBOL Visual](https://fairsharing.org/FAIRsharing.dg76vs), [SynBioHub](https://synbiohub.org)https://synbiohub.org/ and [The Synthetic Biology Open Language (SBOL)](https://sbolstandard.org/)! Were you already aware of these before or did FAIRsharing help you find these? (Is FAIRsharing easy to use and helpful?)

**file format**
- I'm not entirely sure whether .FCS and .sky file formats are open: it looks like you do need a specific software to fully interact with the files so they might be proprietary. As long as that is the main file format in use for these type of files/analysis that is also not a problem. .RIF does appear to be proprietary, so .TIF would be the open alternative. 

**Data publication**
- [Flowrepository](http://flowrepository.org/), [LIPID MAPS](https://www.lipidmaps.org/resources/data),  and [PRIDE](https://www.ebi.ac.uk/pride/) look like great solutions, if they are indeed compatible with your data
- I guess you would make use of the [European Nucleotide archive](https://www.ebi.ac.uk/ena/browser/home) as part of the [INSDC](https://www.insdc.org/)?
- [Cytobank](https://support.cytobank.org/hc/en-us) looks more like a solution for active data management, not necessarily publication. They do state the following: "_Cytobank fills a key NIH mandate for making published data and results available to the scientific community, and has a Reports system for hosting an interactive analysis to accompany a journal publication_." I find it a bit difficult to assess this since there is no browsing of these reports.
- Do note that supplementary materials are not following the FAIR principles - so pending on your project's funding requirements this may not be sufficient. This is because these supplementary materials do not have their own identifiers/DOIs. You can always make use of [4TU.ResearchData](https://data.4tu.nl/) for these types of large files, since this repository allows you to upload 1 TB per year for free.

**Comment by federa7** [comment]
> Thanks for sharing assignment 2 @federa7! It look very clear and comprehensive, so I have little feedback! Well done!
> 
> * With 'A significant amount of my data remains stored in the source equipment for one month.' do you mean that after you transfer the data it will still be there on the source equipment for a month? Or do you only transfer the data after a month? I hope the former? I suppose it will have to be removed because of the size involved?

Hi Esther, 
A little later on but I would still like to respond to your comments! Indeed, the former: the data is so large that it has to be erased frequently from the equipment's memory. I transfer the data to my U: drive right after I finished my experiment. In some particular cases (microscopy) I've noticed that the data gets corrupted during the transfer (I usually might realize immediately or the day after, when starting to analyse the data) so it is good that I have some days to still retrieve it properly.

**Comment by federa7** [comment]
> Thanks for sharing assignment 3 @federa7! It looks very clear and extensive! Well done especially on the data publication part where you have looked into the various options available to share the data!
> 
> **Metadata**
> 
> * I'm glad to see that you found some standards/repositories that are more tailored for your needs ([SBOL Visual](https://fairsharing.org/FAIRsharing.dg76vs), [SynBioHub](https://synbiohub.org) and [The Synthetic Biology Open Language (SBOL)](https://sbolstandard.org/)! Were you already aware of these before or did FAIRsharing help you find these? (Is FAIRsharing easy to use and helpful?)
> 
> **file format**
> 
> * I'm not entirely sure whether .FCS and .sky file formats are open: it looks like you do need a specific software to fully interact with the files so they might be proprietary. As long as that is the main file format in use for these type of files/analysis that is also not a problem. .RIF does appear to be proprietary, so .TIF would be the open alternative.
> 
> **Data publication**
> 
> * [Flowrepository](http://flowrepository.org/), [LIPID MAPS](https://www.lipidmaps.org/resources/data),  and [PRIDE](https://www.ebi.ac.uk/pride/) look like great solutions, if they are indeed compatible with your data
> * I guess you would make use of the [European Nucleotide archive](https://www.ebi.ac.uk/ena/browser/home) as part of the [INSDC](https://www.insdc.org/)?
> * [Cytobank](https://support.cytobank.org/hc/en-us) looks more like a solution for active data management, not necessarily publication. They do state the following: "_Cytobank fills a key NIH mandate for making published data and results available to the scientific community, and has a Reports system for hosting an interactive analysis to accompany a journal publication_." I find it a bit difficult to assess this since there is no browsing of these reports.
> * Do note that supplementary materials are not following the FAIR principles - so pending on your project's funding requirements this may not be sufficient. This is because these supplementary materials do not have their own identifiers/DOIs. You can always make use of [4TU.ResearchData](https://data.4tu.nl/) for these types of large files, since this repository allows you to upload 1 TB per year for free.
> * Microscopy repositories that I'm aware of are:
>   
>   * [IDR](https://idr.openmicroscopy.org/)
>   * [Electron Microscopy Data Bank (EMDB)](http://www.emdatabank.org/)
>   * [EMPIAR](https://www.ebi.ac.uk/pdbe/emdb/empiar/)
>   * [Cell Image Library](http://www.cellimagelibrary.org/)
>   * [BioImage Archive](https://www.ebi.ac.uk/bioimage-archive/)
>     But I'm not sure if any of those are relevant to your research unfortunately :(

Hi Esther,
**Metadata**
I was indirectly aware of this standard mostly by exposition to them (SBOL ones), since they are very well established in the field. It is good to now be aware of their full extent and application.

**file format**
You are right about .sky format. It is proprietary and requires of a specific software (although this software is free access). The right open format that is fully and directly interchangeable is mz formats (.mzXML, .mzML, etc.). Regarding .FACS files, I would insist it is the standard used for the technology to the extend that differents equipments from different brands generate their data with this format and it is readable by different propietary and free access softwares. There are several open source python libraries that allow the analysis of the data. I believe this data can be converted to .CVS format, but I'm not entirely sure if would really represent an advantage in accessibility given that this format is already highly compatible. 

**Data publication**
* The European Nucleotide archive looks indeed like a good option. 
* You might be right about Cytobank. Everyone can access to any given data sets by creating an account, but I'm not aware of the use of DOIs in it and I realized recently that the data is only conserved for a certain amount of time, while the account maintains activity. Flow repository would indeed be a better candidate for a more trustworthy and stable data repository.
* Interesting. At least in my field, supplementary information is made directly accessible together with the original publication and is associated to the DOI as the main paper. Also, some journals have supplementary information not as a separate document but as an additional section of the paper. Nevetheless, I agree that having data in a repository is easier and probably has less capacity limitations. Yet, it will depend on the data set since, as I have mentioned, some of my data can reach 1tb per experiment (RAW). In these cases even 4TU.ResearchData might fall short to our needs. 
* I looked and BioImage Archive seems like a good candidate. I will look more into it as an option for the future.

Thank you for your comments! 
Federico
