### ISSUE TITLE
Assignment 1 Enya Berrevoets

### ISSUE THREAD

**Issue by enyasb** [EstherPlomp/TNW-RDM-101#80]
### Introduction

Hi there, I'm Enya Berrevoets and I started my PhD at the department of Imaging Physics in May 2023. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

In my research, I focus on imaging 3D biological structures at high resolution. Such imaging requires an understanding of the behaviour of light as it propagates through a sample, as well as an understanding of the used imaging system (typically a microscope). I use computational modelling and simulations to establish this understanding. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I have frequently run into the issue of not being able to find past data and not understanding code I had written previously. Additionally, it was difficult for successors to pick up where I left of due to poor documentation. Because of this, I would like to improve my DM practices. 
### What would you like to learn during this course? 

I would like to get more comfortable with using Git. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [ ] Respond to the GitHub issue #65 
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #66
- [ ] Respond to the GitHub discussion #67
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by EstherPlomp** [comment]
And now also feedback for your assignment, which is not going to be extensive because your assignment looks great! It is very concise and clear - well done! 

- Do you take any notes about the image analyses and if so, where are those stored? 
- I appreciate the red flag for the usage rights: yes!
- You could also consider figure and article text as another dataset

**Comment by EstherPlomp** [comment]
Hey @enyasb! Thanks for sharing assignment 3! It looks very clear and concise: well done!

Regarding the last theme, **data publication**: 
 * [4TU.ResearchData](https://data.4tu.nl/info//en/) repository does allow you to assign a license to data/code, and the repository will assign a DOI to any upload shared. 
 * Does the consortium has its own repository or will a preferred repository for the consortium be chosen? A data management plan is where such questions are addressed: perhaps the consortium has one? 
 * Regarding the licenses, [the RDM101 materials have some more information about this](https://estherplomp.github.io/TNW-RDM-101/07-FAIR-principles.html#data-and-code-licences), or if it is easier we can have a short chat about this? You can also checkout what your peers preferred licenses are in the [license discussion thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/66) - perhaps you agree with their reasoning and their license choice.

**Comment by ieacdroste** [comment]
Hi @enyasb, your assignment 3 looks very clear! I was wondering what the output of your image analysis code will be like. Will this be only images or do you need so save other output as well? Maybe you can see this as a separate dataset?

**Comment by enyasb** [comment]
Thanks for the feedback @EstherPlomp and @ieacdroste ! The output of my code is indeed an important part of my data flow. I do not know exactly how I will present and store them, but this will likely be a combination of images, graphs and data sheets.
