### ISSUE TITLE
Assignment 1 Lloyd Mallee

### ISSUE THREAD

**Issue by Lloyd537** [EstherPlomp/TNW-RDM-101#82]
### Introduction

Hi, my name is Lloyd Mallee and I am a PhD candidate in the Biocatalysis group, although my project is much more focused on energy & materials science. I have two very needy cats. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is focused on the development of a solar cell using waste/recycled/circular materials and sustainable processes. I am currently using an enzyme from papaya (fruit) to deposit a semiconductor layer onto glass, after which I apply fruit juice (at the moment pomegranate) and a few other layers to complete the solar cell. My goal is to replace every component/process of solar cell production with a sustainable alternative.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I think it is very important to make sure your research data is safe and backed up in order to prevent situations in which you might lose everything. Our department has had to deal with lost or hard to find data on multiple occasions and, speaking from experience, this can significantly (and unnecessarily) delay research projects.

### What would you like to learn during this course? 

I am hoping to learn some good strategies and organizational structures for a logical data flow and security. I would like to end up in a place where no matter what experiment or how long ago I performed it, I - and any people working on this project after me - will be able to find the data I produced within a short amount of time.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: [Lloyd Mallee - Assignment 2](https://surfdrive.surf.nl/files/index.php/s/bQOzjEiizSyq6Ss)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link: [Lloyd Mallee - Assignment 3](https://surfdrive.surf.nl/files/index.php/s/4THmliwKYFXZdqm)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by QingLi-11** [comment]
Hi Lloyd,

Here are the comments for your data flow map: 

It is clear that you create data from different measurements, and you will have numbers, figures and tables based on the data that you get. A question is that what type of files that you need to store and analyze your data (e.g., Excel. origin)? Where do you export your data to?

Best,
Qing

**Comment by Lloyd537** [comment]
Hi Qing,

Thanks for your comments, I didn't think about specifying this but you make a good point. It would be useful to determine what kinds of files I will get from each type of experiment and specify how I will store each of them.

Best,
Lloyd

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @Lloyd537! It looks very clear, well done!

- I'll echo/agree with your own comments about the confidential data: Project Drive / U: is indeed a better solution for this in terms of access management
- I'll also repeat @QingLi-11's comments about the file formats - file formats are an important theme in assignment 3!
- I also don't see file size estimates, but I assume that you won't work with TBs of data since you did not indicate you work with large data - so hopefully you do not run into storage space shortages!
- Will you have to take any lab notes and if yes: where will you store those?

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 3 @Lloyd537! It looks great - well done! I also appreciate your file naming used to share the assignments 👍 

Just a thought: 

**Data Publication**
- I had a look at [Open Energy Data Initiative (OEDI)](https://data.openei.org/) and it doesn't seem like they use DOI's or other persistent identifiers, but they do have unique identifiers for each of the datasets uploaded. I think that is fine: if this initiative makes your data more discoverable because people expect the information to be there it outweighs the benefits of the DOI in my opinion. They might add this later if the platform continues to develop. Very cool!

**Comment by Lloyd537** [comment]
Thanks for the insight! OpenEI is a repository that I've decided to use up until now, but I still have to discuss this more thoroughly with my supervisor & promotor - we might decide to use a different one after all - perhaps one that does provide a DOI. I do agree that it is more important for the information to be discoverable, whether that includes the use of a DOI or not.
