### ISSUE TITLE
Assignment 1 Christian Primavera

### ISSUE THREAD

**Issue by cfprimavera** [EstherPlomp/TNW-RDM-101#84]
### Introduction

Hi all, I'm Christian, currently in the first year of my PhD at QuTech. I recently moved to Rotterdam, and since then I have enjoyed cycling to and from the university!

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I focus on creating quantum particles in silicon, which interact strongly with light. The long-term goal of this is to transfer quantum information over long distances, eventually trying to build a quantum internet.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes (probably, but not yet)  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

Measurement outcomes in quantum mechanics are inherently probabilistic. Results always follow from statistical analyses of large datasets and need to be interpreted. It is therefore very important that anyone else is able to reconstruct the same conclusions from the original dataset.

### What would you like to learn during this course? 

I would like to learn how to organise recorded data in a way that anyone can understand later on, and how to avoid common mistakes that can lead to loss of progress.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/cfprimavera_tudelft_nl/Edx9uy1M-U5IvoVw84_Jh7kB-KABjj84kxpw7RAdQ04_zg?e=fcGPMo
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/cfprimavera_tudelft_nl/Ea9ei841m2lFlWyXgoaW9PMBXNdajm9_IxVV45eivtavpw?e=RFsJwc 
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**) Link: https://tud365-my.sharepoint.com/:b:/g/personal/cfprimavera_tudelft_nl/Eb9FrCKKDwFBl3pTwBbLLeMBTb6Nh65aL_SNawIuQWKg1w?e=ZMUQkz
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/cfprimavera_tudelft_nl/ERVI-nqaKv1AtA4KkLiDlnUBjtHEXBwjnT0P6ZOW06wONw?e=4CfCoi

**Comment by eugenhu** [comment]
Hi Christian, looks like a good data flow map. It's funny to think that in the event the TU Delft gitlab server permanently loses everything, the code is still mirrored onto the local computer of your collaborators as extra redundancy.

Maybe one thing you could detail is whether the measurement data is automatically or manually backed up to this online datastore folder, and how often this is done.

**Comment by pietro-sillano** [comment]
Hi Christian! I reviewed your data flow map, and I find it well-structured. I imagine that you will deal with several designs for experimental setups, how do you track and store the design files? Could you put them under version control using tools like git?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @cfprimavera ! It looks very concise and clear - well done! 

- Prompted by feedback from @pietro-sillano I want to point you to [dataled](https://www.datalad.org/). This is not a TU Delft solution but so far I received positive feedback. [Subversion](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#subversion-at-tu-delft) could be a TU Delft solution for data versioning. 
- I assume that with a TU Delft datastore folder you mean the Bulk/Project/Group drives? For confidential data it is important to consider who has access to the data - so the Project Drive may be a good solution there.
- Will you have to take any notes or set up documentation for the steps taken to create the processed data? If yes: where will this information be stored?
- I hope your storage solutions are sufficient to cover your needs? I don't see the specific sizes listed - hence the question
- I also don't see specific file formats listed: file formats are an important theme in assignment 3!

**Comment by Pjieter** [comment]
Hi Christian,
Overall your data flow map looks good! I have a few points which might clarify some stuff.
Data organisation:
- It looks like all in all you thought about where to save what. If you show the complete structure, this would make it clearer where to find what for others. You can even add this in your documentation for example in a README-file.

Documentation:
- You are using notebooks to write stuff down when doing manual processing. Will the be jupyter notebooks or other types? Where are you going to store them?

Acces:
- Who are the people with access to the project drive? Group members, only your supervisor. outside collaborators? It is good to specify especially since you are dealing with confidential data.
- You describe that the dataset can be described as open at the end of the project, but it is also confidential. Is this confidentiality only temporary?

Data publication:
- You write a question mark for the designs of the heat shields for how somebody could request access. I think the question is about who should they contanct, or what procedure to follow if someone wants access.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @cfprimavera! Looks great again - well done! Thanks also for adding the file sizes and formats!

I have very little feedback: 

**Data organisation**
- Just out of curiosity: why the difference between camel and snake case in your experiment type and analysis times? Is that to keep the two apart?

**File format**
- hdf5 is indeed an open format!

**Access/Data publication**
- Similar comment to what @Pjieter already brought up: is the data/code confidential until it can be published together with the publication? 
- And regarding @Pjieter's feedback for access requests: 4TU.ResearchData has such a functionality built in where you could share data/code under restricted access and then grant access to individuals when this is requested. This is generally more intended for personal data as confidential data should eventually be able to be shared (since you're also publishing) - but it could be a solution for data/code that has a long embargo period before it can be shared publicly. You can also only share parts and describe in the README file who people should contact for more information/data/code.
