### ISSUE TITLE
Assignment 1 Yutong Wang

### ISSUE THREAD

**Issue by Upsiton** [EstherPlomp/TNW-RDM-101#85]
### Introduction

Hi there, my name is Yutong Wang. I'm a first-year PhD student in the ImPhys department. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I work on 3-dimensional super-resolution microscopy, which is an advanced light microscope technique that enables the imaging of structures at nanometer scale. I devote myself to pushing the limit of the light microscope further to make the tiniest structure of the cells visible. My work focuses on developing optical hardware and image reconstruction techniques.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  Share data and co-work with colleagues/ external collaborators | Yes  |
### What would you like to learn during this course? 

1. How to handle and organize large (experimental) data well.
2. How to share the data with colleagues/ external collaborators well and efficiently. How to co-work for data analysis. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/Aptf7EO7tjqqje5
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/PkoiKPimoMK22JS
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by EstherPlomp** [comment]
Copied from #99: 

Hey, here is my data flow map: https://surfdrive.surf.nl/files/index.php/s/Aptf7EO7tjqqje5
Please feel free to give me any feedback. Thanks!

Best,
Yutong

**Comment by ieacdroste** [comment]
Hi @Upsiton, your data flow map looks very good! Here is some feedback:

- Did you also consider storing your data on a project drive(U:)? You can request project data storage of 4TB and you can give others access to it. This data is automatically backed up every day. I am not sure if this is also the case for the Staff Bulk Data (N:)
- Is there also metadata belonging to the microscope images and the simulated data such as the miscroscope settings and experiment parameters? How do you save this data?
- Do you keep track of different version of your programming code?

**Comment by EstherPlomp** [comment]
Hi @Upsiton: I don't see a link or comment for assignment 3 - can you please still share your assignment or let me know if you need any help? Thanks!

And thanks @ieacdroste for your feedback!

**Comment by EstherPlomp** [comment]
And here your feedback for assignment 3 @Upsiton! Thanks for sharing!

**Data organisation**
- Do be careful that you do not have file names that get too long: this may result in corrupted files/issues when you transfer data, and will also make your file names more difficult to read (it won't be quickly apparent what the file contains, so then you would still have to open it)

**File formats**
- Python/ImageJ is indeed open, for MATLAB/Zemax and I think LabView you do need a license so that is proprietary! Microsoft office is also not open source - you need licenses for it as well. Though these formats (pptx/xlsx) are increasingly more interoperable with different types of software luckily :) 

**Access**
- You can also use [SURFfilesender](https://filesender.surf.nl/) to send files around to others!

**Data publication**
- What is this online server used in your field? Or do you mean a discipline specific data repository? 
- GitHub/Lab is great for collaboration and software management, but not used for long term preservation and it also doesn't assign DOIs to your repositories. For this the link/connection you will need to use a data repository such as [Zenodo](https://zenodo.org/). See [here for more information about Zenodo and GitLab/GitHub](https://the-turing-way.netlify.app/communication/citable/citable-cite.html#citing-software). 

I hope that helps!
