### ISSUE TITLE
Assignment 1 Isabel Droste

### ISSUE THREAD

**Issue by ieacdroste** [EstherPlomp/TNW-RDM-101#87]
### Introduction

Hi, my name is Isabel Droste. I am a second year PhD Candidate at the Department of Image Physics.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focusses on algorithms for super-resolution microscopy. I am working on an algorithm that can detect optical aberration from microscopy data and correct for it, to eventually improve the resolution of microscopy images.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### What would you like to learn during this course? 

I am currently working with large (TB) datasets. I would like to learn the best practices how to handle (large) datasets, how to collaborate with other on this, and make it understandable for others that may continue on it in the future.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [ ] Respond to the GitHub issue #65 
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #66
- [ ] Respond to the GitHub discussion #67
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by enyasb** [comment]
Hi @ieacdroste ! I looked at your data flow map and was wondering whether any flags apply to the data you receive from other groups, e.g., is any of it confidential?

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @ieacdroste! It looks very concise and clear - well done! 

Just two questions from my side:
- Will you also get any documentation/information about the experimental data? Or is all the information you need included within the images themselves?
- Will you also generate your own figures? That could be seen as a new/separate dataset, along with article/chapter texts.

**Comment by ieacdroste** [comment]
> Hi @ieacdroste ! I looked at your data flow map and was wondering whether any flags apply to the data you receive from other groups, e.g., is any of it confidential?

Hi @enyasb, thank you for your feedback! The data that we receive from other groups indeed needs a flag because they asked us to wait till publication until they have published this data themselves.

**Comment by ieacdroste** [comment]
> Thanks for sharing assignment 2 @ieacdroste! It looks very concise and clear - well done!
> 
> Just two questions from my side:
> 
> * Will you also get any documentation/information about the experimental data? Or is all the information you need included within the images themselves?
> * Will you also generate your own figures? That could be seen as a new/separate dataset, along with article/chapter texts.

Thank you for your feedback @EstherPlomp! There indeed is metadata alongside the images and we create our own figures. I will add these to my data flow map

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @ieacdroste, as well as for incorporating the feedback! It again looks very clear - well done!

Just some minor comments/thoughts from my side: 

**File formats**
- I think your considerations regarding MATLAB and Python are fair: there needs to be a balance between the costs and benefits for this. MATLAB is still widely used and most research groups do have access to these licenses - unfortunately not all. This is much more of a long term consideration that you may not address during your PhD project which is only meant to last 4 years!

**Access**
- Just for my own curiosity (so feel free to ignore) - what external programmer are you using? Is this a freelancer or company that helps with data analysis? 

**Data publication**
- GitLab is a great platform to manage code, but not a 'data repository' in the sense that they do not assign DOIs and don't have a long term preservation policy. It is important therefore to share a snapshot/release of your repositories to a data repository. More information on how to do this for GitLab and Zenodo can be found here: https://the-turing-way.netlify.app/communication/citable/citable-cite.html#citing-software (select the GitLab header there instead of the GitHub one). 
Zenodo is a great repository to use!

**Comment by ieacdroste** [comment]
Thanks @EstherPlomp for your feedback and helpful comments on Matlab and GitLab/Zenodo.

About the external programmer: This is a freelancer that helps us to implement part of the Matlab code in C++/cuda to speed up the code. In the past, we have worked with a programmer from the eScience center, but now we chose to hire a freelancer because of time constraints

**Comment by msafariii** [comment]
Hi @ieacdroste, your Assignment 3 appears well-defined and thoroughly explained.

I saw that your experimental microscopy data is quite extensive, totaling 10 TB in size and kind of confidential.
You mentioned that you're unable to publish it until other research groups do so, but you also mentioned that it's in an open file format. This raised some confusion for me. Could you please clarify how it can be an open file format yet not allowed for publication?

**Comment by ieacdroste** [comment]
Thanks for you comments @msafariii. The data is saved as .tiff, which is an open file format because no commercial software is needed to read the .tiff format. Currently, the data is stored in our project storage, so it is not accessible for the public. After publication, it will be in a public data repository.

**Comment by Upsiton** [comment]
Hi @ieacdroste , you have a very good plan for backup and versioning of the code. As we discussed, transferring the big data stored in the U drive could be slow. You could also consider copying the frequently used data to the local drive for fast access during processing.
