### ISSUE TITLE
Assignment 1 Rozalia Persiani

### ISSUE THREAD

**Issue by RozaliaP** [EstherPlomp/TNW-RDM-101#88]
### Introduction

Hi, my name is Rozalia Persiani and I'm a PhD candidate at the Environmental Biotechnology group. I come from Cyprus. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on the extraction of extracellular polymeric substances (EPS) from activated sludge, and the in-depth characterization of these biopolymers. Activated sludge is a byproduct that requires costly disposal or additional treatment with an annual production of 30 kg/person/year. By extracting these high-value biopolymers and understanding better the exact composition, we can find new applications as well as control their production in bacteria metabolism. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

All the reason of why research data management is important seem valid and I am happy that through this course I can prevent losing data and have reproducible data that I can recall on when I need to. 
I remember how I lost my bachelor's thesis three days before I had to submit it.   

### What would you like to learn during this course? 

First of all, understand what I can learn through this course. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by EstherPlomp** [comment]
Hi @RozaliaP! Could you please still share assignment 2? Let me know if you need any help with this!

**Comment by RozaliaP** [comment]
https://surfdrive.surf.nl/files/index.php/apps/richdocuments/index?fileId=13628841980&dir=%2FDocuments

**Comment by EstherPlomp** [comment]
Hi @RozaliaP - I think the link worked earlier this week but now I'm stuck on a loading screen. Can you please try to re-share it? I tried multiple times now so I think this might be the link and not my computer/internet. Thanks!

**Comment by RozaliaP** [comment]
https://surfdrive.surf.nl/files/index.php/apps/richdocuments/index?fileId=13628841980&dir=%2FDocuments

**Comment by RozaliaP** [comment]
I am not sure if I am sharing it the right way. 

I added the ppt on surf drive. I open the file and I copy the link.

**Comment by EstherPlomp** [comment]
@RozaliaP I'm running into the same issues: do you have some time tomorrow morning so we can have a look together how to share the link? I can pass by a bit before 10, or around 11ish if you have five minutes to spare!

**Comment by RozaliaP** [comment]
https://surfdrive.surf.nl/files/index.php/s/qklRbblQa6S23ps

**Comment by EstherPlomp** [comment]
Yes, this works! Thanks very much for following through with the SURFdrive sharing - well done!

Your assignment looks very clear and I really like the flow between the different datasets - great job! 

Just some minor pointers from my side: 

- Just for clarity: with personal drive you mean the H drive? Or maybe the OneDrive? All of these drives can be confusing :) I assume you're using the staff drive because that is how your lab/group is managing the data and that is how your PI will access data?
- Would it be an option to use [GitLab](https://gitlab.tudelft.nl) to manage your code?
- I do not see file formats listed and/or file sizes: Project drive should be helpful if you run into any storage issues. The file formats will become more important for assignment 3.

**Comment by msafariii** [comment]
Hi @RozaliaP 

I have a question about your backup plan.
You mentioned that you are using the personal, staff group, and project drives. 
Is there any backup plan for any of them?

**Comment by EstherPlomp** [comment]
Hi @RozaliaP: I don't see a link or comment for assignment 3 - can you please still share your assignment or let me know if you need any help? Thanks!

**Comment by RozaliaP** [comment]
https://surfdrive.surf.nl/files/index.php/s/cnAr1LZhXR3rmRi

**Comment by EstherPlomp** [comment]
Awesome, thank you! 👍
