### ISSUE TITLE
Assignment 1 Qing Li

### ISSUE THREAD

**Issue by QingLi-11** [EstherPlomp/TNW-RDM-101#89]
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | No  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
[RDM101_Assignment2_Week2_DataFlowMap_QingLi.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12804423/RDM101_Assignment2_Week2_DataFlowMap_QingLi.pptx)

- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)
[RDM101_Assignment5.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/13024788/RDM101_Assignment5.pptx)

**Comment by EstherPlomp** [comment]
Hi @QingLi-11! Could you please still share assignment 2? Let me know if you have any issues or need help with that!

**Comment by QingLi-11** [comment]
Yes, I am currently out of the office for a conference, I will get it done
by today, sorry for the inconvenience.

Best,
Qing

**Comment by EstherPlomp** [comment]
Thanks for the update! And good luck/have fun at the conference!

**Comment by QingLi-11** [comment]
Hey, here is my Assignment 2: https://we.tl/t-Wi0pg2W4BD 

Thank you!
Qing

**Comment by EstherPlomp** [comment]
Thanks Qing! By the way: A more secure solution compared to wetransfer would be [SURFfile sender](https://filesender.surf.nl/)! For this assignment it does not matter much of course, but if you want to share other files it may provide a nice solution.

**Comment by EstherPlomp** [comment]
Now also with feedback for your assignment 2 @QingLi-11: 

You indicated earlier that you don't have personal data, but I see red flags with personal data in your assignments - do you maybe mean confidential data? If you do have personal data I wouldn't recommend to transfer any of that with wetransfer, or USB sticks, for example. 

You do not mention any file formats or file size estimations for your data - I think the Project drive should be sufficient to provide you with enough data storage. The file formats, and which programming languages you're using, are going to be more important for assignment 3!

**Comment by RiccardoDalMas** [comment]
Hi @QingLi-11!

I see that you have personal data flags, as @EstherPlomp pointed out above: how are these data going to be organised, assuming they come 'before' the simulation data?

Regarding the file formats, you have optimisation code in Matlab, which is not an open format, being Matlab a commercial software. Do you think it would make sense for your project to invest the time to convert the scripts, etc. to an open programming language (e.g. Python)?

Cheers,
Riccardo

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @QingLi-11! It looks very clear. 

**Data organisation**
- Your file naming convention looks very clear! Do take care that the file names do not become too long, then they may become difficult to read and it may also cause problems if you transfer files.

**Data publication**
- Unless you have reasons like confidential data or personal data, you're can't say that all the data as 'available upon request'. As a minimum, you would at least have to share the code and data underlying your thesis and articles. See the [summary of the policies that we have at TU Delft](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary) for more information on this. I would like to check with you whether you're indeed generating personal data - because that seems unlikely based on your research topic.
