### ISSUE TITLE
Assignment 1 [Ziqing Yuan]

### ISSUE THREAD

**Issue by ZQYZQYZQ** [EstherPlomp/TNW-RDM-101#90]
### Introduction
Hi all, my name is Ziqing Yuan. I have four cats!

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
Reliable hydrogen sensors are essential for the safe implementation of a large-scale green hydrogen economy. Optical fiber hydrogen sensors seem the perfect candidate from a practical perspective; they are small, relatively cheap to make, and do not require an electronic detection device in the measurement area. My work presents research on the realization and optimisation of such a system utilizing metal hydride thin film as a sensing layer.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes|
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
RDM is very important. It gives us the skills to handle research data more securely and reliably
### What would you like to learn during this course? 
More scientific and effective management of data, better analysis of data, and more visualization of the show

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion #66
- [ ] Respond to the GitHub discussion #67
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [ ] Respond to the GitHub discussion #68 if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)
