### ISSUE TITLE
Assignment 1 Natalia Nadal

### ISSUE THREAD

**Issue by nnadalalemany** [EstherPlomp/TNW-RDM-101#91]
### Introduction

Hello there, my name is Natalia Nadal and I'm a PhD candidate at the Faculty of Applied Sciences. There are three cats at my place but I'm actually a dog's person...

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focusses on understanding the selection of metabolic pathways in anaerobic fermentations. I will grow the anaerobic bacteria Clostridium pasteurianum in a bioreactor, and apply different conditions to see how different metabolic pathways are activated. By analyzing the products, proteins and metabolites, I hope to learn more about the underlying principles of metabolic pathways selection.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | Yes |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

A bad data management poses a great risk to your research: from accidents to mistakes.
A nightmare for me would be that the results I have obtained are not truthful because of inadequate data management.

### What would you like to learn during this course? 

I would like to make my Data Management Plan for my PhD.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **12 September, 10:00**)
- [x] Respond to the GitHub issue #65 
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **20 September 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/rcabaleirogonz_tudelft_nl/EeEQJJj8i81MueoS4NFP67IBl6Hn6GIBWxlxYk2NOzY4MA?e=4Vnezb
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion #66
- [x] Respond to the GitHub discussion #67
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **4 October 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/rcabaleirogonz_tudelft_nl/EedfFUFYUllOlAwN06elb_YB7CAskFcPcOosIuy30J5s0Q?e=4DUrAo
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **11 October, 13:00**)
- [x] Respond to the GitHub discussion #68 if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **17 October, 17:00**)

**Comment by EstherPlomp** [comment]
Copied from #92: 

Dear all,

Here is my Data Flow Map. Looking forward to your feedback!

[RDM101_Assignment1_Week1_DataFlowMap_Template.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12608490/RDM101_Assignment1_Week1_DataFlowMap_Template.pptx)

Kind regards,

Natalia Nadal

with feedback from @TimTheChemist123 

>>
> Hi Natalia!
> I think your data flow map looks nice, with the conversion of one form of data into another included. One point of feedback would be to perhaps also include a further step going from the concentration calculation to the figures/data visualizations you will create.
>
> -Tim

And a thanks from @nnadalalemany : 

>>
> Hi Tim, very good point! Thanks for your feedback :)

**Comment by federa7** [comment]
So, I'm not entirely sure if this is the right place to comment after the issue was moved and linked to the main page but here is my comment! 
I had completely forgot about writing Protocols as a type of data! It is a good point to remember, that we design and optimize our working protocols as we develop our work. And I agree with @TimTheChemist123 , I like how you tackled the data "life-cycle" flowing from generated to converted. Always nice to see things in a graphic way. 
I am curious I didn't see much regarding data analysis and the information/conclusions you generate after the conversion of your raw data. Do you generate reports of your experiments after you have done this? Or maybe it becomes part of your journal in the form of notes. I personally like to generate small reports where I write my overall observations and conclusions on specific data analysis tasks, so it becomes easier to re-utilize later. Although, of course, this would generate a new form of data. I tackle this by having a special section for results reports in my eJournal. 

-Fede

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @nnadalalemany - I really like how you visualised your workflow - well done! 

And yes @federa7 - this is indeed the right place to comment. Apologies about the moving around stuff! And thanks for sharing your experiences with generating small reports - sounds helpful! 

Thanks also for your feedback @TimTheChemist123 - that is indeed another potential dataset!

I only have minor further feedback on your assignment: 
- You can also use your own OneDrive account to store data, but ideally you share the data with your supervisor indeed so if it works like this you can also disregard this comment :)
- I'm curious what you mean with 'sensitive to collapsing': I'm not sure that I want to find out - it sounds like this happened before?
- You can try out the [electronic lab notejournals that TU Delft has licenses for](https://www.tudelft.nl/en/library/research-data-management/r/manage/electronic-lab-notebook): setting up an account is free!

**Comment by nnadalalemany** [comment]
Hello all,

Here is my assignment 3.
[https://tud365-my.sharepoint.com/:p:/r/personal/rcabaleirogonz_tudelft_nl/Documents/r.gonzalezcabaleiro/d.Research/RGC_Group/RGC_GROUP/PhD%20Students/CURRENT_Students/Natalia/2.%20Graduate%20school/7.%20DMP/RDM101_Assignment2_Week2_DataFlowMap_Template.pptx?d=w41155fe752584e59940c0dd3a7a56ff6&csf=1&web=1&e=a6hUeU](url)

Looking forward to your thoughts!

Natalia

**Comment by Lloyd537** [comment]
Hi Natalia,

I think you've created a pretty clear folder structure that will make it easy to find everything later on, both for yourself and for others. One question: you indicate to use a naming convention starting with E1 (in your example), which I assume means experiment 1. Will this numbering correspond to the numbering you use in your lab journal?

**Comment by nnadalalemany** [comment]
> Hi Natalia,
> 
> I think you've created a pretty clear folder structure that will make it easy to find everything later on, both for yourself and for others. One question: you indicate to use a naming convention starting with E1 (in your example), which I assume means experiment 1. Will this numbering correspond to the numbering you use in your lab journal?

Dear Lloyd, thanks for your comment!

You guessed it right, E1 stands for Experiment 1.
The same numbering will indeed be used in my Laboratory Journal.

Cheers,

Natalia

**Comment by nnadalalemany** [comment]
> Thanks for sharing assignment 3 @nnadalalemany! It again looks great!
> 
> **Data Organisation**
> 
> * Really nice overview and file naming. I am curious about the answer to @Lloyd537's question as well!
> 
> **Data Documentation**
> 
> * No worries if an ELN does not seem helpful: loads of people are still working with paper lab note books. As long as you have a backup of this information somewhere it also works!
> 
> **Metadata**
> 
> * Is there any metadata you need from the proteomics/metabolomics data?
> 
> **file formats**
> 
> * Actually, Microsoft file formats are not open: you cannot fully use these proprietary formats using other software programmes. Open format alternatives would be markdown, .txt files for word, and .csv files for Excel. Microsoft formats are widely used and to some degree also interoperable with other software - so it might not make sense to convert them to these open file formats. I tend to share both the Microsoft file formats and the open formats to ensure that the files can be opened in the long term, but to also keep the full functionalities of the Microsoft files. I would only do that with data that isn't GB/TB in size though, otherwise you're using a lot of storage space for the same information. I hope this consideration makes sense!

Dear Esther,

Thank you for your feedback!
As I just answered to Lloyd, E1 stands for Experiment 1 and the same numbering is used in my lab journal.
There is probably metadata for the proteomics and metabolomics analysis. However, I do not know about them yet as I am not going to conduct those analysis any time soon. I will certainly keep it in mind, though!
Good to know that Microsoft file formats are not open file formats. I definitely did not consider that. In that case, I will do the same as you and upload to the repository the data in both Microsoft files format and the open version (.txt for word and .csv for excel).

Kind regards,

Natalia

**Comment by EstherPlomp** [comment]
Thanks for responding @nnadalalemany! No worries of course if you don't know yet - do indeed keep it in mind! 

And happy to hear that you find the advice helpful to share both file formats! 

See you next week!

**Comment by TimTheChemist123** [comment]
Hi Natalia,

Your flow map looks even better now! and I like the point implemented by you from @federa7. I  also write quarterly reports which can be considered a type of data output, which indeed help in periodically organizing all the experiments I have done instead of after a long time.

-Tim
